### ISSUE TITLE
[iOS] unregister for a topic: do not call success/error callback

### ISSUE THREAD

**Issue by hungdoan2** [phonegap/phonegap-plugin-push#1040]
### Expected Behaviour
Run this Code 
````
push.unregister(function successCallback(){}, function errorCallback(){}, [ios_abcdef123456])
````
`successCallback` will be called if the task is success

`errorCallback` will be called if the task is fail

### Actual Behaviour

Either `successCallback` and `errorCallback` were not be called

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce 
Scenario  1

1. Login
2. Subscribe for topic `ios_abcdef123456`
3. Logout
4. unsubscribe for topic `ios_abcdef123456`
5. unsubscribe fail 
6. `errorCallback` is not called (it must be called)
7. End

Scenario  2

1. Login
2. Subscribe for topic `/topics/ios_abcdef123456`
3. Logout
4. unsubscribe for topic `topics/ios_abcdef123456`
5. unsubscribe successfull
6. `successCallback` is not called (it must be called)
7. End

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 9.3

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
iPhone 5

#### Cordova CLI version and cordova platform version
Cordova 6.2.0

#### Plugin version
v1.7.2

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

I looked at the source code. I seem in iOS It doesn't add '/topics/' to the input (which It did in Android)

**Comment by skyprimer** [comment]
Unsubscribing from a specific topic or from an array of topics does not work. I've asked so many times no happy ending.. My solutions is;

If there is 10 topics that a user is subscribed to when he clicks "topic unsubscribe" i am Unsubscribing from all of them and subscribing 9 of them again. Ugly but it is working ı do not know why macdonst does not fix the code for that or just cancel the array part in code.. We can process our array on javascript...

**Comment by macdonst** [comment]
@skyprimer do not attribute to malice which one can attribute to complete lack of time on my part. Pull requests are always welcome.

**Comment by skyprimer** [comment]
Oh i willing to help but i do not know objective / c coding. Somebody wrote here when he turns the code line from array to single variable `push.unregister(function successCallback(){}, function errorCallback(){}, [ios_abcdef123456])` works. So i think no need to use array (bec. not working) in that we can use loop on javascript side...

**Comment by macdonst** [comment]
@skyprimer you should check out the latest code as @hungdoan2 may have fixed your issue.

**Comment by skyprimer** [comment]
Not working at my side;

**Subscribe code:**
```
var push = PushNotification.init({
            "android": {
                "senderID": "xxxxxxxxxx",
				 "topics":["topicandroid"]
            },
            "ios": {
                    "gcmSandbox": "true",
	            "senderID": "xxxxxxxxxxx",
                    "sound": "true",
                    "alert": "true",
                    "badge": "true",
                    "clearBadge": "true",
                    "vibration":"true",
                    "content-available": 1,
                    "delayWhileIdle" : "false",
                    "priority" : "true",
		    "topics":["topicios"]
            }
        });
```
**UnSubscribe code:**
```
function topicer(){
 push.unregister(function() {
alert('done');
}, function() {
alert('not done');
},["topicios"]);
}
```
When i click the button with topicer() function nothing happens. No error no sucess messages. What is wrong with my code?

**Comment by hungdoan2** [comment]
@skyprimer @macdonst, So sorry, I haven't fixed this issue yet, because of breaking change. 

I think It's not a good idea to unsubscribe topics in push.unregister(). 

It's better to leave `unregister` alone, and add a new function called `push.unsubscribe(string topic)`

**NOTE** : `string topic` not `Array<string> topic`. Because in native API they do not support to unsubscribe for multiple topics. And `unsubscribe` function is async, so It's not a good choice to support `unsubscribe multiple topic` without promise / rollback / callback feature!

@macdonst If you agree about adding a new function( `push.unsubscribe(string topic)`) I could create a pull request.

**Comment by skyprimer** [comment]
Yeah yeah this what i was talking about we can do the loop on javascript side no need for arrays..

**Comment by macdonst** [comment]
@hungdoan2 yeah, I'm good with adding methods to do `push.subscribe(string topic)` and `push.unsubscribe(string topic)`. Leave the topics array in `push.init()` for backwards compatibility and `push.unregister` should unsubscribe from all topics. Make sense to you?

**Comment by skyprimer** [comment]
Version: 1.7.3
Build: Phonegap Build

Throws out error with Android: Oh geez. Your build failed. Sorry, but a problem occurred on the build server

Log:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:9.0.2+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
     Required by:
         :project:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

And i think with hungdoan2's update the unregister function is completely lost :) I can not unregister with/without (,topic) 

My third determination is when notification arrives Android (Without 1.7.3 update) sounds both app and default sound.. Mixing each other.. I will investigate this furthere...

**Comment by gustavocampos** [comment]
Same build problem here on Phonegap build 6.1.0

**Comment by skyprimer** [comment]
@hungdoan2 any progress?

**Comment by hungdoan2** [comment]
Sorry you guys for the late response. I have just started to [working on  it](https://github.com/hungdoan2/phonegap-plugin-push/tree/issue-1040) now.  
I'm testing it carefully. A pull request would be available on next Monday.

@skyprimer 

> And i think with hungdoan2's update the unregister function is completely lost :) 

Actually we need `unregister ` function. When you forgot which topic you have subscribed, then `unregister` function will save your life.

**Comment by macdonst** [comment]
@hungdoan2 awesome, looking forward to the PR. 🙏

**Comment by hungdoan2** [comment]
PR is delayed because of #1098

**Comment by skyprimer** [comment]
I've identified when a user is unregistered from a topic with server side action (googleapis.com) it becomes something like "banning from the topic" bec. user side registration again to that topic does not work.. The user must be added to that topic again from server side action.. @hungdoan2 we are looking forward for your update :)

**Comment by skyprimer** [comment]
push.unregister(function() {
alert('done');
}, function() {
alert('not done');
},array);

Unregister function with array is working now (i don't know since which version update).. But no callback on error or success..

**Comment by m0n01i7h** [comment]
Hi,
Met same issue

seems `successWithMessage` if topics array present missed
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L125
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L149

**Comment by bardu** [comment]
I'm using phonegap-plugin-push 1.8.2 

To unregister one or more topics I do this:
```
reinitPushNotification = (topics) => {
        window.gcmPush.unregister(
            function() {
                console.log('Push has been unregistered');
                initPush(topics);
            }, 
            function() {
                navigator.notification.alert(
                    config.alerts.reinitPush.message,
                    null,
                    config.alerts.reinitPush.title,
                    config.buttonLabels.gotit   
                );
            }
        );
    }
```
I call unregister and on success do init push again with the new array of the topics a user has opted in.
For example if the user has opted out of electronics-ios  I see this in the Xcode console which seems to be right:

> 2016-10-04 20:46:56.200 LookInside[186:4096] subscribe from topic: accommodation-ios
2016-10-04 20:46:56.201 LookInside[186:4096] subscribe from topic: arts-ios
2016-10-04 20:46:56.202 LookInside[186:4096] subscribe from topic: auto-ios
2016-10-04 20:46:56.202 LookInside[186:4096] subscribe from topic: toys-ios
2016-10-04 20:46:56.203 LookInside[186:4096] subscribe from topic: beauty-ios
2016-10-04 20:46:56.204 LookInside[186:4096] subscribe from topic: fashion-ios
2016-10-04 20:46:56.204 LookInside[186:4096] subscribe from topic: food-ios
2016-10-04 20:46:56.205 LookInside[186:4096] subscribe from topic: health-ios
2016-10-04 20:46:56.206 LookInside[186:4096] subscribe from topic: home-ios
2016-10-04 20:46:56.206 LookInside[186:4096] subscribe from topic: jewlery-ios
2016-10-04 20:46:56.207 LookInside[186:4096] subscribe from topic: services-ios
2016-10-04 20:46:56.207 LookInside[186:4096] subscribe from topic: sports-ios
2016-10-04 20:46:56.208 LookInside[186:4096] subscribe from topic: transport-ios
2016-10-04 20:46:56.209 LookInside[186:4096] subscribe from topic: vacation-ios
2016-10-04 20:46:56.212 LookInside[186:4096] Already subscribed to accommodation-ios
2016-10-04 20:46:56.212 LookInside[186:4096] Already subscribed to arts-ios
2016-10-04 20:46:56.213 LookInside[186:4096] Already subscribed to auto-ios
2016-10-04 20:46:56.213 LookInside[186:4096] Already subscribed to toys-ios
2016-10-04 20:46:56.213 LookInside[186:4096] Already subscribed to beauty-ios
2016-10-04 20:46:56.214 LookInside[186:4096] Already subscribed to fashion-ios
2016-10-04 20:46:56.214 LookInside[186:4096] Already subscribed to food-ios
2016-10-04 20:46:56.214 LookInside[186:4096] Already subscribed to health-ios
2016-10-04 20:46:56.216 LookInside[186:4096] Already subscribed to home-ios
2016-10-04 20:46:56.216 LookInside[186:4096] Already subscribed to jewlery-ios
2016-10-04 20:46:56.217 LookInside[186:4096] Already subscribed to services-ios
2016-10-04 20:46:56.217 LookInside[186:4096] Already subscribed to sports-ios
2016-10-04 20:46:56.218 LookInside[186:4096] Already subscribed to transport-ios
2016-10-04 20:46:56.218 LookInside[186:4096] Already subscribed to vacation-ios              

The user is not subscribed to electronics-ios anymore one would think.
The call to unregister caused two problems on iOS:

1. the user still gets notifications for electronics-ios
2. for this and any other topics the user is subscribed to she gets the notification **twice**                   

I would suspect that there is a new GCM pushID assigned and GSM now keeps two for the same device, however, for iOS is looks like no new pushID is assigned after unregister/re-register.

On Android it is working as expected, except the user doesn't get  a notification anymore when the device is in sleep mode. However, I'm not sure this is due to the call to unregister.

@macdonst Do you have any clue what's going on here?

**Comment by macdonst** [comment]
Merged PR
