### ISSUE TITLE
How forceshow ture on ios

### ISSUE THREAD

**Issue by GurubakshSingh** [phonegap/phonegap-plugin-push#1045]
I have to make functionality  forceShow : "true", on ios but it is not working how can i

**Comment by macdonst** [comment]
@GurubakshSingh `forceShow` is not supported on iOS. It is actually impossible, that is why it is not [documented](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions).

**Comment by GurubakshSingh** [comment]
So what should i do if i want notification when app is open.   Please ...............................

**Comment by macdonst** [comment]
@GurubakshSingh as I said in my previous comment it is impossible on iOS. The OS will not show anything in the notification center when the app is in the foreground. When the app is open you get your `on('notification')` event handler called. You can use the information within in order to show your own UI.
