### ISSUE TITLE
Push notification not get when app is running

### ISSUE THREAD

**Issue by js12690** [phonegap/phonegap-plugin-push#1046]
Hello,

I am using this plugin for receive push notification in android and ios platform. its working fine for me but i have one issue with this plugin

When my app is closed and running in background state then i got notification but when my app in running state then i got notification from GCM and APNS but cant see in notification tray or not get alert on screen for push notification receive.

Please give me solution as soon as possible

Thanks in advance

**Comment by macdonst** [comment]
@js12690 so you want the notification to appear in the notification tray when your app is in the foreground?

**Comment by js12690** [comment]
Thanks for your quick response macdonst

yes i want notification appear on screen and in notification tray when app is in running or used mode

**Comment by macdonst** [comment]
@js12690 Right and I'm going to try and not sound like an asshole here but if you would have [read the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#android) or [searched the past issues](https://github.com/phonegap/phonegap-plugin-push/issues/1045) you would know the answer to that question. That's why I have a [Reporting Issues](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/ISSUES.md) document.

My question to you is what can I do to make this more obvious to people opening issues? Obviously you did not find this information when you went to look for it. How can I portray the information better so that people can find their answers quicker?

**Comment by macdonst** [comment]
@js12690 Please click on the `searched the past issues` link in my previous comment.

**Comment by js12690** [comment]
@macdonst Thanks again for your quick answer

I read Searched the past issues and you told that "forceShow is not supported on iOS. It is actually impossible," and i also tested in whatsapp app. when app is running then cant get notification but they display some popup on screen so that logic we need to define at our side. am i right?

but can we get any flag value for application is in running mode or in background or closed?

Thanks in advanced

**Comment by macdonst** [comment]
@js12690 WhatsApp creates their own UI for when you are in the app. You'd have to write your own similar functionality. 

Once again [please read the docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback) as it describes how to tell if the push data arrived in the foreground or background by using the data.additionalData.foreground property.

**Comment by js12690** [comment]
@macdonst Thank you so much for your perfect answer

**Comment by js12690** [comment]
@macdonst 

One more question push.on('notification') event is not fired in android device. am i right?

**Comment by ajaysaini95700** [comment]
i tried this (forceShow : true) for android. it is not working when app is in foreground .
is there another way to solve it ?
