### ISSUE TITLE
Problem with notifications stacking

### ISSUE THREAD

**Issue by tomilenko** [phonegap/phonegap-plugin-push#1118]
Hello,

I have a problem with stacking push notifications.
I have set "notId" in the notification (as described in https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking ) but anyway, the second message replaced the first one. The "notId" field didn't work in my app.
How I can send the notifications that they have not replaced and I will see all notifications (e.g. 20), not just the latest one?
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Samsung, LG, Lenovo
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.2.0
cordova platform version android                     # e.g. 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```
#### Sample Code

```
"notification": {
        "title": "My Title",
        "message": "My 99 message",
        "notId": 99
    }

```

```
"notification": {
        "title": "My Title",
        "message": "My 100 message",
        "notId": 100
    }
```
#### Init code in app.js file in Ionic:

```
   var push = new Ionic.Push({
        "debug": false
    });

    push.register(function(token) {
        console.log("Device token:", token.token);
        LocalStorage.set('device.token', token.token)
    });
```

**Comment by macdonst** [comment]
@tomilenko Send the following payloads:

```
"data": {
        "title": "My Title",
        "message": "My 99 message",
        "notId": 99
    }

"data": {
        "title": "My Title",
        "message": "My 100 message",
        "notId": 100
    }
```

**Comment by tomilenko** [comment]
Hello @macdonst These examples are not working as needed. The second notification is still replaced the first one.
Do you have any idea what I can fix this?

**Comment by tomilenko** [comment]
Hello @macdonst !
Did you check this issue? Do you have any solution for this?

**Comment by macdonst** [comment]
@tomilenko sorry, I haven't been able to get to re-test this one yet.

**Comment by macdonst** [comment]
@tomilenko sorry, I just can't reproduce this bug. Can you provide me with a more detailed reproduction scenario?

**Comment by BSchwetzel** [comment]
I have the same problem. I'm using Phonegap Build (cli-6.3.0) and plugin version 1.8.2 from npm. The following payloads lead to the problem:

`{"title":"eSuite","message":"Something1","additionalData":{"link":"open?Doc1","notId":"1473922167836","google.message_id":"XXX","coldstart":false,"collapse_key":"do_not_collapse","foreground":true}}`

`{"title":"eSuite","message":"Something2","additionalData":{"link":"open?Doc2","notId":"1473922194606","google.message_id":"YYY","coldstart":false,"collapse_key":"do_not_collapse","foreground":true}}`

As can be seen, notId is a string, which is due to Googles GCM client (https://github.com/google/gcm/blob/master/client-libraries/java/rest-client/src/com/google/android/gcm/server/Message.java#L122) seemingly only being able to add string data. I'm wondering if that is something you can fix on your side (which would be quite awesome as the successor fcm, or rather it's plugin, won't compile with Phonegap Build). This assumes the problem is even related to that, of course.

**Comment by macdonst** [comment]
@BSchwetzel your problem is you are using a `notId` that is larger than the MAX_INT value on Android so when the plugin converts the string to an integer it throws an exception and uses 0 as a default.
