### ISSUE TITLE
Multiple instances of push notifications

### ISSUE THREAD

**Issue by tberne** [phonegap/phonegap-plugin-push#1127]
Hi guys,
I'm developing an app that deals with more than one site. Because of that, I need more than one instance of push notification (each will be attached to a given project id).
The structure of my app is something like (written in Typescript):

    class Site {
        private push;
        initPush() {
            this.push = PushNotification.init({...});
            this.push.on("notification", function(data){
                // do stuff
            });
        }
    }

When I have more than one instance of Site class, the push plugin always invoke callback in one of the instances. It only happens if the app is closed and reopened. If it never closes, the correct object receives the message.

Is it an issue or is it by-design?

**Comment by fredgalvao** [comment]
It is by design that an app installation should only deal with one push project configuration. Most java classes used by this plugin are registered in a way that will make them work as per-event instances or singletons, which would make your scenario not work or at the very least present some serious conflicts during runtime, thus your experiences. Regarding the work needed to enable the plugin to work in a multi-tenant scenario, I'd say @jcesarmobile or @macdonst  would have to pitch in.

**Comment by macdonst** [comment]
@tberne actually, you should be able to do this but I've never tested it so YMMV. If you pass in your multiple senderID's to the into the init method separated by comments it might just work.

```
var push = PushNotification.init({
    android: {
        senderID: "12345679,234567890,3456789012"
    }
});
```

The problem is you'll only be able to initialize one Push Notification instance to handle all incoming pushes. So, you'll have to differentiate which project it is coming from in the payload.

Try it out and let me know if it works.

**Comment by tberne** [comment]
@macdonst I'm already able to identify from which server the message comes from. It is not a problem. I didn't know that I could pass more than one sender ID a time.

The big catch that I see is that every time user change his sites (by removing, editing or adding a new one) I will have to recreate the push instance. 
The other thing is that I'll change from n instances to a single push instance, but it should not be a problem.

Thanks for the tip. I'll post here whether it worked or not. 

Another thing, do you see any possible problem with iOS? I'll use GCM in iOS either.

Thanks again!

**Comment by macdonst** [comment]
@tberne any update?

**Comment by tberne** [comment]
@macdonst, sorry for the delay on answer. In the end we decided (for other reason) to rollback the multiple-sites feature. So, I didn't even tried your suggestion.
