### ISSUE TITLE
sendResponse called twice

### ISSUE THREAD

**Issue by cburghardt** [phonegap/phonegap-plugin-push#1150]
### Actual Behavior

Plugin crashes with the following stack trace:

```
Fatal Exception: NSInternalInconsistencyException
this request has been neutered - you can't call -sendResponse: twice nor after encoding it

3
Foundation  
-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4   BaseBoard   
__40-[BSAction sendResponse:withCompletion:]_block_invoke
5
libdispatch.dylib   
_dispatch_barrier_sync_f_invoke
6   BaseBoard   
-[BSAction sendResponse:withCompletion:]
7   UIKit   
-[UIHandleRemoteNotificationAction sendResponse:]
8   UIKit   
__91-[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]_block_invoke_32897
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 9
#### Cordova CLI version and cordova platform version

```
cordova --version                                    # e.g. 6.0.0
```

6.3.0
    cordova platform version android                     # e.g. 4.1.1
iOS 4.1.1
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3
```

1.7.4
#### Sample Code that illustrates the problem

```
        pushNotification.on('notification', function (data) {
            if (data.message && !isEmpty(data.message)) {
                    if (!data.additionalData.foreground)
                        pushNotification.finish();
            }
        });
```

**Comment by macdonst** [comment]
@cburghardt I need a more specific reproduction scenario, please provide more details.

**Comment by cburghardt** [comment]
Unfortunately I don't know how it can be reproduced. I only see in Fabric that this crash is happening very often.

**Comment by macdonst** [comment]
@cburghardt I need more info in order to be able to help with this one. What leads you to believe it is the push plugin?

**Comment by cburghardt** [comment]
Well the crash emerges from UIHandleRemoteNotificationAction sendResponse
Your plugin is the only place where this is handled. At some point the completionHandler seems to be called twice.

**Comment by macdonst** [comment]
@cburghardt are you sure that is the only place it is being called? It is possible that another library you are using is also calling the completionHandler? I ask because I know nothing of your setup and since you are including Fabric could it be possible it is also calling the completionHandler?

**Comment by cburghardt** [comment]
Your plugin is the only place. Fabric only catches the exception.
Maybe let's tackle this from a different perspective: I have seen that your plugin calls finish with a notification ID. By default this is simply set to 'handler'. What is the recommended way to get the notification ID and pass this to the finish method? I am just wildly guessing here though.
Also, should finish only be called when the app is not in foreground as in my code? That whole iOS finish stuff is poorly documented so I am just making assumptions.

**Comment by macdonst** [comment]
@cburghardt just making sure. So if you send a notification ID in your push payload it will end up at `data.additionalData.keyName` whatever your key name is. Then you call:

`pushNotification.finish(data.additionalData.keyName);`

I tend to call `finish` all the time to make sure it's handled.

Please suggest ways I can make the docs less poor as I'm often too close to the subject.

**Comment by cburghardt** [comment]
So it is an arbitrary key and the plugin does not store it somewhere.
As you are calling the completionHandler async would it be possible that several notifications come in and the completionHandler is called several times when there is no notification ID?

If you look for this exception and the completionHandler you get several cases where it all boils down  to the same issue - the completion handler is called twice. Example:
http://stackoverflow.com/questions/25809191/ios-8-nsinternalinconsistencyexception

**Comment by macdonst** [comment]
@cburghardt the key is used in the map of completion handlers. When you call finish with a parameter it will look up and remove that completionHander. If you don't have a parameter it'll just pop the last one off the stack which can be problematic if you send two background pushes in short order.

**Comment by cburghardt** [comment]
OK and how do I set this notification ID in the payload so that it is recognized as key for the completion handler lookup? If that is already explained somewhere I apologize.
Also I just stumbled over AppDelegate+notification.m which already calls the completion handler in didReceiveRemoteNotification. So is the finish call actually necessary?

**Comment by macdonst** [comment]
@cburghardt I do a really crappy job of documenting it but look at: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1

Yes, you should always call finish. If you don't signal to the OS that you are done with background processing it will think your app has gone run-away and kill it.

**Comment by rmoolenaar** [comment]
I've seen this on my iPhone happening after sending 1 single push notification:

Nov 10 11:41:16 iPhone Vely[630] <Warning>: didReceiveNotification with fetchCompletionHandler
Nov 10 11:41:16 iPhone Vely[630] <Warning>: app in-active
Nov 10 11:41:16 iPhone Vely[630] <Warning>: this should be a silent push
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin notId handler
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Notification received
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: data
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: content-available
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: moredata
Nov 10 11:41:16 iPhone Vely[630] <Warning>: didReceiveNotification with fetchCompletionHandler
Nov 10 11:41:16 iPhone Vely[630] <Warning>: app in-active
Nov 10 11:41:16 iPhone Vely[630] <Warning>: this should be a silent push
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin notId handler
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Notification received
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: data
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: content-available
Nov 10 11:41:16 iPhone Vely[630] <Warning>: Push Plugin key: moredata
Nov 10 11:41:17 iPhone Vely[630] <Warning>: Push Plugin finish called
Nov 10 11:41:17 iPhone Vely[630] <Warning>: Push Plugin finish called
Nov 10 11:41:17 iPhone Vely[630] <Warning>: Finish push successfull
Nov 10 11:41:17 iPhone Vely[630] <Warning>: Finish push successfull
Nov 10 11:41:17 iPhone Vely[630] <Warning>: Push Plugin stopBackgroundTask called
Nov 10 11:41:18 iPhone Vely[630] <Warning>: Push Plugin handlerObj
Nov 10 11:41:18 iPhone Vely[630] <Warning>: Push Plugin: stopBackgroundTask (remaining t: 38.735368)
Nov 10 11:41:18 iPhone Vely[630] <Warning>: Push Plugin stopBackgroundTask called
Nov 10 11:41:18 iPhone Vely[630] <Warning>: Push Plugin handlerObj
Nov 10 11:41:18 iPhone Vely[630] <Warning>: Push Plugin: stopBackgroundTask (remaining t: 38.728700)
Nov 10 11:41:18 iPhone Vely[630] <Warning>: *** Assertion failure in -[UIHandleRemoteNotificationAction sendResponse:withCompletion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/BaseBoard/BaseBoard-175.24/BaseBoard/BSAction.m:322
Nov 10 11:41:18 iPhone Vely[630] <Error>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'this request has been neutered - you can't call -sendResponse: twice nor after encoding it'
	*** First throw call stack:
	(0x242fb91b 0x23a96e17 0x242fb7f1 0x24adf529 0x25931d09 0xa0d377 0x25931c5f 0x28e3a1f3 0x28b2689b 0xa03b7f 0xa03b6b 0xa08655 0x242bdb6d 0x242bc067 0x2420b229 0x2420b015 0x257fbac9 0x288df189 0xcecc3 0x23eb3873)
Nov 10 11:41:18 iPhone debugserver[629] <Error>: assertion failed: 13G36: libsystem_trace.dylib + 15927 [E82A6F2D-873A-39AD-8014-EDEB52248157]: 0x0
Nov 10 11:41:18 iPhone Unknown[629] <Error>: 
Nov 10 11:41:18 iPhone debugserver[629] <Error>: assertion failed: 13G36: libsystem_trace.dylib + 15927 [E82A6F2D-873A-39AD-8014-EDEB52248157]: 0x0
Nov 10 11:41:18 iPhone Unknown[629] <Error>: 
Nov 10 11:41:18 iPhone debugserver[629] <Error>: assertion failed: 13G36: libsystem_trace.dylib + 15927 [E82A6F2D-873A-39AD-8014-EDEB52248157]: 0x0

**Comment by rmoolenaar** [comment]
This is the JSON data of the message I send (background message):

{ "data": "Background push", "moredata": "data", "content-available": 1 }

**Comment by rmoolenaar** [comment]
This happens on irregular intervals
