### ISSUE TITLE
Cla

### ISSUE THREAD

**Issue by kctang** [phonegap/phonegap-plugin-push#1157]
The [documentation](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md) says:

"It is absolutely critical that you call push.finish() when you have successfully processed your background push data."

Why is it so? What's the impact if we don't?

I am asking this because i am troubleshooting some background notification processing on iOS (sending to APNS via GCM). Foreground messages no issue but events don't get trigger when app is in background.

**Comment by ef33zy** [comment]
@kctang In the paragraph above the one you've copied...

When you receive a background push on iOS you will be given 30 seconds of time in which to complete a task. **If you spend longer than 30 seconds on the task the OS may decide that your app is misbehaving and kill it. In order to signal iOS that your on('notification') handler is done you will need to call the new push.finish() method**.
