### ISSUE TITLE
Why can the SENDER_ID specified in config and API?

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#1175]
I wonder why you have to specify the SENDER_ID in `config.xml` and also again in the APIs `init` options?
Why this redundancy. Can we omit the `config.xml` variable and only use it in the `init` call instead?

**Comment by macdonst** [comment]
As described in #679 the ability to set the SENDER_ID will be going away in 2.0.0. I started requiring it as a variable so people would get used to it before the API change. Also, the switch to FCM from GCM will only read the SENDER_ID from a specific XML file on Android so I need to know that value in order to write the file correctly at plugin install time.

**Comment by pke** [comment]
I see, sorry didn't see that it has been asked before.
