### ISSUE TITLE
Has anyone tested the plugin on Android 7.0 Nougat already?

### ISSUE THREAD

**Issue by samplezzz** [phonegap/phonegap-plugin-push#1184]
I'm experiencing a problem that registered device token is not recognised by GCM while sending a notification. Same app works correctly on Android 6.0.1.

Also, by each installation of the app on Android 7 the device token remains the same, whereas on Android 6 it's different after reinstalling the app.

**Comment by macdonst** [comment]
@samplezzz yes, I have tested on Android 7. I cannot reproduce the issue.

**Comment by NamrataBagerwal** [comment]
Even I am facing the same problem. While sending push notification in devices having OS <=6.0.1, push notification is received successfully while in case of Nougat GCM does not recognize the device token.

**Comment by NamrataBagerwal** [comment]
Finally after searching so much found the below answer:
Reboot your device since it must have got OTA update for Nougat. System's cache partition might not have been  cleared. Seems to be an issue in Nougat. Below are the steps for rebooting and found the same Push Notification code working in Nougat as well:

Power down your device
Press and hold Volume Down and Power simultaneously until you see the boot screen
Use Volume Down to navigate to Recovery Mode
Press Power to confirm
Wait until you see the Android robot then hold down Power. Press and release Volume Up
Navigate with Volume Down to the Wipe Cache Partition option
Press Power to select
Use Volume Down to highlight the Yes option
Press Power to select
Press Power to reboot

Reference Link: [https://productforums.google.com/forum/#!topic/nexus/xEssjbdwpgk
](url)
