### ISSUE TITLE
Suggest a single payload for ios and Android for running, background and Closed apps

### ISSUE THREAD

**Issue by santhoshscs** [phonegap/phonegap-plugin-push#1200]
### Expected Behaviour
**Case1**. App running in Foreground : When a push is sent from server the notification should be accepted by the 'on Notificaton' Event on both android and Ios
**Case2.** App Runing in Background : When a push is sent from server, the notification should be displayed in the shade and on clicking on the notification in the shade   the 'on Notificaton' Event should be executed both android and Ios 
**Case3.** App not running (Closed) :
 When a push is sent from server, the notification should be displayed in the shade and on clicking on the notification in the shade   the 'on Notificaton' Event should be executed both android and Ios 
### Actual Behaviour
Case 1 and Case 2 works 
Case 3 works on ios but on in Android
I see several issues related to this in discussed here but didnt get a clear idea on wheather this particulatr issue is already resolved
I have to use different payloads for achieving case1 and case 2 on Ios vs Android
Also Let me know wheather  **single payload** is capable of achieving case 1, case 2 and case 3 on ios and Android

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@santhoshscs so I'm unclear what did not work for you in case 3, can you please elaborate? Also, telling me what payload you used is helpful.

**Comment by alertops** [comment]
@macdonst I have been facing the same issue as @santhoshscs for case 3, when the app is completely closed, on Android, all action buttons cannot work the same as case 2, it is related to web view javascript cannot be executed in this case. I have seen several discussions related to this but still  could not find a solution.

**Comment by andreszs** [comment]
**Case 3** means that when the app is started from **coldstart** by clicking a notification in the shade, the `push.on('notification')` event is never fired up. Not until the app has re-registered with GCM at least, so that's the first thing I do then the app is restarted (always).

The only way to have the `push.on('registration')` event fired from coldstart is by registering for a **new token**, which is not very practical because _the user must wait until the token arrives_. Immediately after that, the event is fired normally, and we use the `data.coldstart=true` parameter to find out that the app was (most likely) launched from the shade.

Notice I said _most likely_ because in practical terms the plugin doesn't provide any means to find out if the app was launched from the shader or the icon. Your best guess is to check if a push was just received.

**Comment by jhlee8804** [comment]
+1

**Comment by jcesarmobile** [comment]
Closing because the Payload is not something we can control from the plugin, you have to send the right payload from the server to each platform following the platform rules and there is no universal Payload that you can use and works on both. 

Read https://github.com/phonegap/phonegap-plugin-push/issues/1249 for more reasons and possible workarounds.
