### ISSUE TITLE
How to Implement Push Notification in iOS ?

### ISSUE THREAD

**Issue by Chitranjanbariya** [phonegap/phonegap-plugin-push#124]
Please give me a step of How to create in IOS. How i put apns app id in this.
please help me.....

**Comment by macdonst** [comment]
@Chitranjanbariya on iOS you don't need to send the apns app id as part of the options. You just need to make sure your iOS certificate is setup correctly. There is a good tutorial over here:

http://code.tutsplus.com/tutorials/setting-up-push-notifications-on-ios--cms-21925

**Comment by leonardopaiva** [comment]
thanks  @macdonst the tutorial helped alot

**Comment by leonardopaiva** [comment]
@Chitranjanbariya i`m just starting with push notification, this is my experience so far:

you can use the tutorial that @macdonst spoke http://code.tutsplus.com/tutorials/setting-up-push-notifications-on-ios--cms-21925 
you will use step 1 then 4 to 6, you can jump step 2 and 3 (thats what worked for me)

you can use this tutorial too: http://www.apptuitions.com/generate-pem-file-for-push-notification/
since it covers the part where you need to generate the "pushcert.pem" file, when you have the pushcert.pem file you can send the push using this: 
https://github.com/phonegap/phonegap-plugin-push/blob/master/example/server/pushAPNS.rb
or with php using this https://github.com/GustavoCostaW/PushNotificationBackendSamples/blob/master/ios.php
(i used the last one)

this line will have the .pem file directory:
"stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');"
so replace by "pushcert.pem" and put the pushcert.pem file on same directory from your server file:
"stream_context_set_option($ctx, 'ssl', 'local_cert', 'pushcert.pem');"

$passphrase = the .pem file password (step 8 from the last tutorial)

**Comment by colonna-mike** [comment]
Hello,
Are you saying the pem file does not have to part of the phone build but on the PHP server ( in my case. So on the app side nothing is needed to get the IPhone id  correct?.

**Comment by bobolat** [comment]
heelo there..im build an ios app use cordova..can i use this plugin too?on android version seems i dont have any problem ..when it come to ios..my head already explode try to configure how to use this plugin..can someone help me?there any setup need to configure besides install this plugin?

**Comment by leonardopaiva** [comment]
@colonna-mike yes... but i`m not sure about that, because i haven't made tests on a production app, only on development using a localhost server.

@macdonst can you aswer this question?

**Comment by fredgalvao** [comment]
The only thing needed on the app itself for push notifications to work on iOS is to **sign it with proper certificates and provisioning profiles, generated with a valid push notification certificate**. The pem/key files need only to go on the server, you'll neem to feed them to the APNS api to send notifications.

**Comment by leonardopaiva** [comment]
thanks @fredgalvao

**Comment by bruno-serfe** [comment]
Hi Guys,

I've configured the APNS certificate for iOS and obtained the GCM API KEY and SENDER ID for iOS (are the same of Android) the issue is that the notifications arrives in android devices but not in iOS.

during the debugging of my server implementation with GCM I can see that the issue seems to be with the following error: "invalidRegistration" (from GCM) but the register id seems to be correct, can this issue be related with the APNS certificate configuration in XCode?

Any help will be appreciated a lot!

Best regards

**Comment by lddd** [comment]
```
 setup
2016-06-20 18:18:46.933 Dead Stock[363:260565] GCM Sender ID (null)
2016-06-20 18:18:46.933 Dead Stock[363:260565] Using APNS Notification
2016-06-20 18:18:48.412 Dead Stock[363:260369] Push Plugin register success: <0bad3d9b beeebd26 6d207450 3e1714fc bbb71d11 71294562 36adc080 68808558>
2016-06-20 18:21:38.092 Dead Stock[363:260369] active
2016-06-20 18:21:38.093 Dead Stock[363:260369] PushPlugin skip clear badge
```

Hooray. Now can anyone explain the "PushPlugin skip clear badge" to me? Why its doing that?
