### ISSUE TITLE
[Question] why different payload format on Android and iOS

### ISSUE THREAD

**Issue by jhlee8804** [phonegap/phonegap-plugin-push#1249]
I don't understant follow behavior...

```java
// works on Android (foreground, background)
// not works on iOS
{
   'registration_ids': [ ...],
   'data': {
      'title': 'my title',
      'message': 'my message'
   }
}
```

```java
// works on Android (background ok. but foreground not showing large icon and not firing 'notification' event)
// works on iOS
{
   'registration_ids': [ ...],
   'notification': {
      'title': 'my title',
      'body': 'my message'
   }
}
```

How do i send to both two platforms with single palyload?
I read some threads ([#897](https://github.com/phonegap/phonegap-plugin-push/issues/897), [#960](https://github.com/phonegap/phonegap-plugin-push/issues/960), [#967](https://github.com/phonegap/phonegap-plugin-push/issues/967)), but i can't find a conclusion.

Please help!

**Comment by jcesarmobile** [comment]
For iOS push to work you have to include a `aps` object/dictionary, so there is not real way of sending a single payplad that works for both. In your server you have handle it based on the OS.

You can search for push libraries that can help you with that (not sure if there is any)

Probably using GCM/FCM for iOS you can send them the same Android payload to them and they should create the right iOS Payload (didn't try)

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

Closing because the payload isn't something we can control from the plugin, it's Apple and Google who decided to use their own different incompatible payload.

**Comment by jhlee8804** [comment]
@jcesarmobile  Thanks to reply. I using `gcm`(for Android) and `gcm with apns`(for iOS). So I think it should be same format, but your advice is very helpful.

**Comment by jcesarmobile** [comment]
If you are using GCM, then the second one seems the one you have to use (the one with the notification object)
https://developers.google.com/cloud-messaging/http-server-ref
https://developers.google.com/cloud-messaging/concept-options
https://developers.google.com/cloud-messaging/ios/client

When the app is in foreground it works in a different way than when it's on background, the push message won't be displayed in foreground, but should fire the notification event.
