### ISSUE TITLE
[Fixed] iOS 10.0.1 - Plugin 1.8.2 - OnNotification event no more fired when app is in background

### ISSUE THREAD

**Issue by thsantac** [phonegap/phonegap-plugin-push#1265]
### Expected Behaviour

When the app is in background and a notification is received, app should wake up and do some actions based on the onNotification event.
### Actual Behaviour

App wakes up but doesn't do expected actions. If app is killed before receiving notification, expected actions are done.
### Reproduce Scenario (including but not limited to)

Put app in background and send a notification.
#### Steps to Reproduce

Put app in background and send a notification.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

iOS 10.0.1
#### Cordova CLI version and cordova platform version

```
cordova --version                                    6.2.0
cordova platform version android           android 5.1.1 - ios 4.1.1
```
#### Plugin version

```
cordova plugin version | grep phonegap-plugin-push   # e.g. 1.8.2
```
#### Sample Push Data Payload

Not available (WordPress notification plug-in)

**Comment by macdonst** [comment]
@thsantac Sorry, I need more information in order to debug this. When a notification is received on iOS the `on('notification')` event handler will not be called unless you are sending the property in your push payload to indicate it is a background message.

So, I'm a little confused as to what you are doing. Is it a background message, are you tapping the notification, etc? More information will help and the push payload is the key piece.

**Comment by thsantac** [comment]
All I have is the WordPress plug-in log:

INFO: Message : Array ( [MESSAGE] => ApnsPHP_Message Object ( [_bAutoAdjustLongPayload:protected] => 1 [_aDeviceTokens:protected] => Array ( [0] => 06b7c606722c76693c31b70e28feb406a152baa836135b1f3663df4b10d19ee3 ) [_sText:protected] => Postes ouverts à la CAP de décembre 2016 [_nBadge:protected] => 2 [_sSound:protected] => default [_sCategory:protected] => [_bContentAvailable:protected] => 1 [_aCustomProperties:protected] => Array ( [id] => 11833 ) [_nExpiryValue:protected] => 604800 [_mCustomIdentifier:protected] => ) [BINARY_NOTIFICATION] => 	W?5 ??r,vi<1?(???R??6[6c?K???{**"aps":{"alert":"Postes ouverts à la CAP de décembre 2016","badge":2,"sound":"default","content-available":1,"priority":"high"},"id":"11833"**} [ERRORS] => Array ( ) )

Is there a missing property I should add?

Sorry but I don't really know what is a background message. For me it is just a notification sent by WordPress each time a news is created. The subscribed phones receive the notification and then I tap the notification in order to launch the app I have developed and installed on my iPhone (via testfairy). When app is not running everything's OK but not when app is in background.

I don't know what more I could say :-)

Thank you

**Comment by macdonst** [comment]
@thsantac okay, so what you are saying is when you tap on the notification the app starts but the `on('notification')` event handler is not fired?

**Comment by thsantac** [comment]
Not fired only if the app was in background. When app wasn't running, it starts and the  on('notification') is fired.

**Comment by nigram** [comment]
I also experience this issue. When the app is "inactive", as in open but paused because another app is active or the phone is suspended, the callback is not fired when the push-notification is opened. 

When the app is entirely closed and the push-notification is opened, the callback does fire.

Im also using phonegap-plugin-push 1.8.2 but with Cordova 6.3.1.

Please let me know if you need any information.

**Comment by parkjungwoong** [comment]
i was same issue 
i solve issue remove <meta http-equiv="Content-Security-Policy" ....> tag in index.html

**Comment by thsantac** [comment]
@macdonst 

Hi, 

Did you have the time to debug the plug-in (my customer is waiting the issue to be solved before paying me...) ?
Also, what do you think of parkjungwoong's solution ?

Thank you

**Comment by kashyapmukkamala** [comment]
+1 same issue

**Comment by kashyapmukkamala** [comment]
Also, I none of the notifications were received on 1.8.2 so I went back to 1.6.3 on which only the notifications with app in background were an issue

**Comment by Lucklyric** [comment]
https://github.com/Lucklyric/phonegap-plugin-push
I tried to fix this issue in this fork, and it works for me. You can just replace these files (AppDelegate+notification.h,AppDelegate+notification.m,PushPlugin.h,PushPlugin.m) under "src/ios" to your iOS project under "Plugin/" folder.
Hope it could fix your problem.

**Comment by thsantac** [comment]
@Lucklyric 
Hi, 
Thanks for the suggestion. I did replace the four file with yours (after duplicating the src/iso folder) but unluckily it did not change anything... Still same issue. Is there anything more to do than just replacing those 4 files?
Thanks.

**Comment by Lucklyric** [comment]
@thsantac 
Right, just changed those 4 files, have you tried to uninstall the app and install it again to your device ?

**Comment by thsantac** [comment]
@Lucklyric 

Yes I did. Actually, it is a new version installed via TestFairy services which replaces the already installed one.

**Comment by thsantac** [comment]
@Lucklyric 

I just took your entire fork and put it in my project, did a new version of my app (xCode => Archive), removed the previous version on my iPhone and installed the new version.

Still having this f... issue !!! 

I am despaired... :-(

**Comment by thsantac** [comment]
By the way, there are a lot of warnings concerning PushPlugin.m when I build an archive in xCode 7.3.1... Lot of deprecated UIRemoteNotificationType, TypeNone, TypeBadge, ..., registerForRemoteNotificationTypes, ...And in PushPlugin.h : cannot find protocol definition for GCMReceiverDelegate.

**Comment by Lucklyric** [comment]
@thsantac Sorry to hear that.
Could you try it in debug mode, and send a notifiaction in development environment? Then can you check with the log in Xcode to see if the notificaiont has been handled by the native part? The corresponding log texts could be found in AppDelegate+notification.m. (eg. NotificationCenter Handle push from background or closed.)

**Comment by thsantac** [comment]
@Lucklyric 
I have thought of this but the xCode iOS emulator doesn't support notification push. And the only way I have to send notification (even test notification) is using the WordPress plug-in installed on an online blog which is in production. 
Maybe you know how to debug in another way ? This is my first Cordova app using xCode :-)
I am currently downloading xCode 8 with iOS 10 support and I hope this will solve the issue but I don't think it will, so I cross my fingers.
Thanks.

**Comment by thsantac** [comment]
@Lucklyric 
OK, I have have connected my iPhone on my Mac and launched the app from xCode and this is what I got:

2016-10-14 07:21:56.980139 SNCTA[1681:991400] didReceiveNotification with fetchCompletionHandler
2016-10-14 07:21:56.980318 SNCTA[1681:991400] app in-active
2016-10-14 07:21:56.980414 SNCTA[1681:991400] this should be a silent push
2016-10-14 07:21:56.980560 SNCTA[1681:991400] Push Plugin notId handler
2016-10-14 07:21:56.980664 SNCTA[1681:991400] Notification received
2016-10-14 07:21:56.980785 SNCTA[1681:991400] Push Plugin key: content-available
2016-10-14 07:21:56.981055 SNCTA[1681:991400] Push Plugin key: alert
2016-10-14 07:21:56.981155 SNCTA[1681:991400] Push Plugin key: priority
2016-10-14 07:21:56.981727 SNCTA[1681:991400] Push Plugin key: badge
2016-10-14 07:21:56.984102 SNCTA[1681:991400] Push Plugin key: sound
2016-10-14 07:22:03.728036 SNCTA[1681:991400] active
2016-10-14 07:22:03.728141 SNCTA[1681:991400] PushPlugin skip clear badge
2016-10-14 07:22:48.961166 SNCTA[1681:991400] checkLastUpdate
2016-10-14 07:22:48.982867 SNCTA[1681:991400] appNewLaunch=1
2016-10-14 07:22:48.983059 SNCTA[1681:991400] getLastRun - done
2016-10-14 07:22:48.988477 SNCTA[1681:991400] checkLastUpdate - Transaction success

"this should be a silent push" ??? Is it the problem ?

**Comment by thsantac** [comment]
OK now it works !!!

What I did:

- copy the 4 files from Lucklyric's fork (see above) : AppDelegate+notification.h, AppDelegate+notification.m, PushPlugin.h and PushPlugin.m under "src/ios" of my iOS project under "Plugin/" folder,
- copy the entire phonegap-plugin-push folder outside my project folder (parent folder of the project folder),
- remove phonegap-plugin-push with "cordova plugin rm phonegap-plugin-push",
- added the plug-in with cordova plugin add ../phonegap-plugin-push --variable SENDER_ID="xxx", this way I re-install the plug-in with the folder previously copied.

And now it works.

Why it didn't work before? Simply because when you do a cordova prepare ios, the plugins are not updated, you have to remove and install the plugin.

**Comment by jumamfa** [comment]
Hello,

I may be miss-understanding, but I have the same problem where the following occurs:

Send a push when the App is fully closed, it arrives and upon clicking the notification, the app opens up and the notification events are fired.

Send a push when the App is 'minimised' / 'in the background' and the notification arrived, but clicking it just opens the App with no event firing.

I can however get this to work if I enable background app updates in my device settings however not all of my users would have this enabled, so here comes the question...

Does the @Lucklyric fix solve this problem, or will it always be a problem for those with background app refresh disabled?

Thanks all

**Comment by thsantac** [comment]
@jumamfa 

Lucklyric did solve the problem with his own fork (link in discussion above) and if you follow exactly what I did it will fix yours :-)

**Comment by jumamfa** [comment]
Thanks, I may have to wait until the fix is applied here as I'm reluctant to jump onto a fork...

**Comment by thsantac** [comment]
You can apply it right now if you take Lucklyric's fork.

**Comment by thsantac** [comment]
Totally approved by macdonst :-)

**Comment by Lucklyric** [comment]
@thsantac 
Good to hear that you fixed your problem.

**Comment by jumamfa** [comment]
Will the fork be kept up to date and in line with the main repo? -  thanks

**Comment by macdonst** [comment]
@thsantac it's really weird, as I can't reproduce the problem with the main 1.8.3 or @Lucklyric fork. I will probably merge @Lucklyric fork once I can do some more testing.

**Comment by Lucklyric** [comment]
@macdonst  is that mean you can still get the onNotication event after tapping the notification while the app is in the background?

**Comment by macdonst** [comment]
@thsantac @Lucklyric I'm running iOS10 and plugin version 1.8.3. Here are the scenarios I'm testing:

* ✅ When I send a message with the app in the foreground I get the event. 
* ✅ When the app is in the background I send a message and when I click on it in the notification shade the event is fired. 
* ✅ When the app is in the background I send a message with `content-available: 1` and when I open the app the notification event has been fired.
* ✅ When I kill the app, I send a message and when I click on it in the notification shade the event is fired. 
* ❌ When I kill the app, I send a message with `content-available: 1` and when I open the app the notification event has **not** been fired. This is kinda expected behaviour considering there is not web view to run the JS.

If I switch to @Lucklyric fork this is what I see:

* ✅ When I send a message with the app in the foreground I get the event. 
* ✅ When the app is in the background I send a message and when I click on it in the notification shade the event is fired. 
* ❌ When the app is in the background I send a message with `content-available: 1` and when I open the app the notification event has been fired.
* ✅ When I kill the app, I send a message and when I click on it in the notification shade the event is fired. 
* ❌ When I kill the app, I send a message with `content-available: 1` and when I open the app the notification event has **not** been fired. This is kinda expected behaviour considering there is not web view to run the JS.

Can you let me know exactly what scenario is not working for you and possibly some reproduction code? I have a feeling that the problem is in this line https://github.com/phonegap/phonegap-plugin-push/blob/bb0d3ed087e13e24af57e682776930cea2f577a8/src/ios/PushPlugin.m#L375 where the delay is not long enough when firing the event.

**Comment by jumamfa** [comment]
Thanks @macdonst 

I'm using the basic example code and running a test in the following scenarios:

1. Receive a push notification when the App is open and running (works fine, good news).
2. Receive a push notification when the App is fully closed (works fine, good news).
**3. Receive a push when the App is 'minimised', in the background (notification arrives, and upon clicking the notification, the App opens and the event handlers do not fire).**

As discussed, I am using the basic example code provided and I am not sending content-available at all as my impression is that the content-available setting is used for background notifications (maybe to update some data or similar).

Thanks

**Comment by macdonst** [comment]
@jumamfa do me a favour and go to line 375 of PushPlugin.m and increase the delay from 0.5 to 2.0 then retest to see if it resolves the issue.

**Comment by jumamfa** [comment]
@macdonst that seems to have done the trick! Previously, I had to have background app refresh enabled on the device to force it to work (sorry I forgot to mention that in the above comment) however I can now disable background app refresh and receive a push while minimised / in the background correctly.

**Comment by macdonst** [comment]
@jumamfa okay thanks for that info. I think the root cause of all these problems are startup time related. I need to figure out a way to delay until the app is ready to receive the data.

**Comment by jumamfa** [comment]
Great, let me know if I can help (testing etc).

**Comment by fredgalvao** [comment]
If I can read that code correctly, that block would only apply to the scenario of a `coldstart:true` startup with a pending notification, right? If that's the case, I don't see how that applies to the background-notification scenario.

Considering I'm as illiterate in Objective-C as I think I am, I'll consider that this is indeed a case of a coldstart-related notification, and say that [this suggestion of mine](https://github.com/phonegap/phonegap-plugin-push/issues/501#issuecomment-250630474) could fix this.

The more we increase that delay timer, the harder it will be on users to detect whether the app was started by a push notification. They're mutualy exclusively solvable issues.

We don't need to guess when it'll be okay to trigger a notification receipt, or make the user guess when it's okay to proceed with the app flow and consider "this as not a coldstart from a push notification". I don't see any way to fix this on both sides consistently without changing the API.

@macdonst  please let me know what you think of that suggestion.
@jumamfa I'd also like to know if your case would be fixable if the implementation suggested at my comment (linked above) was done.

**Comment by macdonst** [comment]
@fredgalvao I like you suggestion but we should handle it on a separate thread.

You are correct in saying that the code I suggested changing only applies to a coldstart situation. I think a few problems are popping up here. First we have a number of folks experiencing this problem but none can give me a solid reproduction scenario. I need to see some code and a push payload here folks or I can't proceed on this as I can't reproduce it. Second, I do believe the root cause is a race condition between when the Obj-C gets the notification and sends it along to the JS layer but I need a better reproduction scenario. Thirdly, if folks are setting `content-available: true` and not calling `push.finish()` then everything could totally screw up but since I don't have code or a payload I'm just guessing.

**Comment by sri3650** [comment]
@macdonst  Can you please let me  know if the above issue is fixed. I am still facing the issue. I installed latest version of the plugin(1.8.3) but the event handlers are not firing when I click on the push notification when the app is running in the background.

**Comment by crashlab** [comment]
> You are correct in saying that the code I suggested changing only applies to a coldstart situation. I think a few problems are popping up here. First we have a number of folks experiencing this problem but none can give me a solid reproduction scenario. I need to see some code and a push payload here folks or I can't proceed on this as I can't reproduce it. Second, I do believe the root cause is a race condition between when the Obj-C gets the notification and sends it along to the JS layer but I need a better reproduction scenario. Thirdly, if folks are setting content-available: true and not calling push.finish() then everything could totally screw up but since I don't have code or a payload I'm just guessing.

@macdonst I always had this working until few days ago when I tested on IOS10. I installed the version 1.8.3. I'll try to provide you a payload and more details hoping to help you to solve the issue.
What I don't understand is what is the relation of this specific issue with calling or not `push.finish()`.
For example:
1. I start the app and I don't send any push notification to the device.
2. I put the app in background
3. Finally I send a push notification to the device
4. I tap the notification
5. The app resumes but the notification event is not triggered
In this example you will never reach `push.finish()` because is the first notification and the notification event was never triggered. Am I understanding right?

**Comment by mbaggott** [comment]
I too am facing this issue, iOS only. It was working on a previous version (i'm not sure which one), but i did an update 3 or 4 weeks ago to fix an Android problem and then the background notifications for iOS stopped working. They work when the app is open, they work when i tap the notification, but if i receive a notification while the app is in the background, and then open the app, push.on is not fired. I can post my details:

PAYLOAD

{
      "to": "/topics/scheduleIOS", //Topic or single device
      "priority": "high", //If not set, notification won't be delivered on completely closed iOS app 
      "notification":{
        "title": "Appointment Request",  //Any value 
        "body": "Please confirm your preferred date and time",  //Any value
        "content-available": 1,
        "sound": "default",
        "badge": "1"
      },
      "data":{
         // various key pairs for data
      }
    }

INIT

var push = PushNotification.init({
      android: {
          senderID: "1062032799809",
          topics: ["scheduleAndroid"],
          clearNotifications: "true"
      },
      ios: {
          senderID: "1062032799809",
          gcmSandbox: true,
          alert: "true",
          badge: "true",
          sound: "true",
          clearBadge: "true",
          topics: ["scheduleIOS"]
      },
      windows: {}
    });

AS PER NEW DOCUMENTATION, push.finish running at end of push.on for ios:

push.finish(function() {
    console.log("processing of ios push data is finished");
}); 

Note i am using the new format for the payload for iOS background notifications: "content-available": 1
