### ISSUE TITLE
[Question] Unresolved issues unsubscribe/subscribe topics on iOS

### ISSUE THREAD

**Issue by bardu** [phonegap/phonegap-plugin-push#1268]
First of all, thanks for your hard work to make this an awesome plugin.

Sending messages to topics via GCM is a very powerful feature.
However, there seem to be some long lasting issues unregister/re-register topics on iOS, [500](https://github.com/phonegap/phonegap-plugin-push/issues/500), [906](https://github.com/phonegap/phonegap-plugin-push/issues/906), [915](https://github.com/phonegap/phonegap-plugin-push/issues/915), [1040](https://github.com/phonegap/phonegap-plugin-push/issues/1040).

To my experience everything works fine once a user has subscribed to one or more topics, the trouble starts after a call to pushnotificationInstance.unregister and invoking PushNotification.init again in the success callback.

Is there any possibility to make solving these issues a higher priority?

**Comment by hungdoan2** [comment]
It's mainly because the different between Android and iOS APIs. 
in Android : After unregistered: all your topics will be unsubscribe
in iOS : After unregistered: all your topics still be remained on the server. When you re-register, you will receive notification again. 

So, solution in iOS is unsubscribe topics one by one instead of unregistered (unregistered & unsubscribe are different)

Since this commit : https://github.com/phonegap/phonegap-plugin-push/commit/3a1eda75f5f6500e1d040b4908970d8127533587#diff-7f7180e57f8881f89da69aa7664ebedd

So, you can temporary fix this issue by: 
```
push.unregister(function() {
    console.log('success');
}, function() {
    console.log('error');
}, ['your-topic']);
```

Or checkout this pull request https://github.com/phonegap/phonegap-plugin-push/pull/1227  for subscribe & unsubscribe feature.

**Comment by macdonst** [comment]
@hungdoan2 yes, I will get to your PR shortly. I've been on the road for most of September/October.

**Comment by bardu** [comment]
@hungdoan2 Thanks for your explanation and the PR!

**Comment by macdonst** [comment]
Merged in @hungdoan2 PR.
