### ISSUE TITLE
Not able to both update the badge and suppress the sound (when Android App is closed)

### ISSUE THREAD

**Issue by robvandijk** [phonegap/phonegap-plugin-push#1350]
### Expected Behaviour
The badge should be updated and playing a sound should be suppressed (when the App is closed).

### Actual Behaviour
I can either get the badge updated, or suppress the sound, but not both 

### Reproduce Scenario (including but not limited to)
My App is registered with FCM (not the prevous GCM). The FCM payload can contain both a notification object and a data object (see [FCM documentation](https://firebase.google.com/docs/cloud-messaging/concept-options).
* If I include a data object containing the badge the badge is updated.
* If I include a notification object containing sound = nil the sound is suppressed.
* If I include both notification and data object the badge is not updated, but the sound is suppressed

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### Cordova CLI version and cordova platform version

    cordova --version      6.3.1
    cordova platform version android      5.2.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.8.1

#### Sample Push Data Payload
* data:{"message":"Hi","badge":22,"icon":"notification","title":"Hi"}
* notification:{"title":"Hi","sound":null}

Including the sound parameter in the data object (with values 'null' or '') and omitting the notification object does not seem to have an effect. Any ideas on how to get this done?

**Comment by fredgalvao** [comment]
FCM support is not out yet for this plugin. You might want to try the 2.0.x branch to test it, if you have the time and want to contribute to it being released faster and better.

The original issue for the topic is [here](https://github.com/phonegap/phonegap-plugin-push/issues/929), and you can install said branch with:
`cordova plugin add https://github.com/phonegap/phonegap-plugin-push#v2.0.x --variable SENDER_ID=API_KEY`

**Comment by robvandijk** [comment]
Hi Fred, thanks for responding. I don't think it is really specific for FCM though, GCM also accepts both data and notification payloads ([GCM docs](https://developers.google.com/cloud-messaging/concept-options). It seems that, when a notification payload is also provided, the badge in the data payload is ignored by the push plugin. Could that be the case?

**Comment by fredgalvao** [comment]
Yes it could, and actually it is.

It is known that this plugin expects and needs everything to be in the `data` portion of the payload to function perfectly, and the mere existence of the `notification` object makes android take over and not allow the plugin to do its magic. It's not well documented though, clearly we can improve there.

Take note, however, that this restriction applies to GCM on Android only, and quite the opposite happens with GCM on iOS: everything needs to be in the `notification` object.

You're right in saying that this restriction is currently not specific for FCM, but if you are indeed using FCM, I'd recomend following that issue anyway, and using the proper branch (2.0.x), otherwise you're sure to sooner than later be affected by uncovered spots.

I'll leave this closed for now, as it seems to me now that it's been properly handled. Please reopen it or create one anew if the issue persists or needs any other explaining.

**Comment by robvandijk** [comment]
Thanks for the tip about using the proper branch.
I get it now: when both notification and data payload is available and the app is not running, the notification payload is handled by Android and the data payload is handled only when the alert is clicked (as stated clearly in the Google docs, my bad).
So I'll be looking into using a workaround: send 2 notifications, one with a notification payload for suppressing the sound, and the other with a data payload to update the badge.

**Comment by robvandijk** [comment]
Just as feedback for others facing the same: it's working now (p.s. this is about Android, not iOS).

If you need to set both the badge and play a sound, sending 1 notification with a 'data' payload is sufficient.
However, if you need to set the badge and suppress the sound, you need to send 2 notifications:
* 1 with a 'data' payload containing just the badge
* 1 with a 'notification' payload containing e.g. a title and setting sound to null

**Comment by fredgalvao** [comment]
@macdonst Shouldn't a single payload be able to handle both of these at the same time? I smell a bug there, it shouldn't need 2 requests.

**Comment by macdonst** [comment]
@fredgalvao sadly, no. Once the OS sees the `notification` part of the message it just lets the OS handle it and the push plugin code never gets a crack at the `data` part to update the badge. For 1.9.0 and earlier @robvandijk will have to send two pushes but in order to get all the benefits of the push plugin he should be sending everything in `data`. It is my hope that things have changed with FCM but I've not had the time to look into it in depth.

**Comment by robvandijk** [comment]
I'm relatively new to this, but the docs in [GCM](https://developers.google.com/cloud-messaging/concept-options) and in [FCM](https://firebase.google.com/docs/cloud-messaging/concept-options) seem to be the same for messages containing both notification and data payloads: _When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification_.
So unless the OS starts to handle these payloads differently, switching to FCM will not help regarding this behaviour.

**Comment by macdonst** [comment]
@robvandijk yeah, that will suck then.
