### ISSUE TITLE
Older API Level Support

### ISSUE THREAD

**Issue by vbresults** [phonegap/phonegap-plugin-push#1370]
There are references to `android.os.Bundle.putBoolean` and `putString` which [do not exist until API Level 21](https://developer.android.com/reference/android/os/BaseBundle.html).  There's also a reference to `org.json.JSONArray` which doesn't exist until API Level 19.

I was experiencing strange issues where things wouldn't fire on older API levels (14, 15) a couple of months back, this is probably the source of all the problems.

**Comment by macdonst** [comment]
@vbresults I'm sorry but what you have posted is factually incorrect. The `android.os.Bundle` class has had the [putBoolean](https://developer.android.com/reference/android/os/BaseBundle.html#putBoolean(java.lang.String, boolean)) and [putString](https://developer.android.com/reference/android/os/BaseBundle.html#putString(java.lang.String, java.lang.String)) methods since API level 1 of Android. As well the entire [org.json.JSONArray](https://developer.android.com/reference/org/json/JSONArray.html) class was introduced in API level 1.

I'm not quite sure where you got that impression but both classes have been around since the first version of Android.

**Comment by vbresults** [comment]
@macdonst `putBoolean/String` was a snag in that documentation, it does not correctly list that these methods were in the Bundle class and moved to BaseBundle.

You are also right on JSONArray, I got this plugin mixed up with the other one; sorry.
