### ISSUE TITLE
Documentation of ANY kind on using plugin with FCM

### ISSUE THREAD

**Issue by themoneyfinder** [phonegap/phonegap-plugin-push#1394]
I've assigned 3 experienced developers to get push notifications set up using FIrebase and your plugin along with phonegap (CLI and Dev App).

They're new to phonegap, but have built out an entire app - but none of them can make your plugin work. They've wasted 2 full days trying to figure it out. What are you guys doing?

Requests for information seems to end in a referral to issue #929 - which isn't helping get set up. We cannot use GCM as we've been forced on to Firebase... so can you give us a hint? What are we supposed to do? Is there documentation? An example? Anything? 

The lack of documentation is astounding - basically, people new to phonegap can't expect to make this work.

**Comment by fredgalvao** [comment]
What piece of documentation exactly did you want done that isn't done? We try to make it as clear and detailed as possible, but we can always improve with the right feedback.

If you're refering specificaly and only to FCM support, #929 says it all: it's an *open issue*, which means it's still in development and discussion, and thus it's **not supported yet**, so no documentation for that until the 2.x branch comes out of dev status.

As to the "new to phonegap" topic, there are simple examples for the client code available [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md), two full tutorials used on international workshops available [here](http://macdonst.github.io/push-workshop/) and [here](http://macdonst.github.io/push-workshop-eu/) (both with full client and server code and usage guidance). There is full api documentation for the client code [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md), full installation guide using phonegap and/or cordova [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md), phonegap build guidance [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md) and extensive payload reference and list of example [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md).If you're using Typescript or an IDE that understands Typescript, you have typings available [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/TYPESCRIPT.md) which should make the way to production a lot faster and safer as a bonus. That covers pretty much everything a non-phonegap-developer would need to know to get a fully functional application up with GCM or APNS, which are the two services the plugin officially supports right now. And all of those links are on the main page README of the repository.

If you're stuck on FCM, a few options are:
- wait until support is out and stable
- try the 2.x branch yourself
- implement it on native code yourself and don't use this plugin


As for why FCM support isn't out yet, @macdonst  and @jcesarmobile might have more detailed technical information regarding the roadblocks and pending issues. It's a community effort, so everyone is welcome to try it and help make it stable.

Did any of your developers report the issues they had during the process of implementing it? If they haven't, it'd help if they did. We can't fix what we don't know about.

**Comment by macdonst** [comment]
@themoneyfinder I was typing a response but @fredgalvao beat me too it. We are working on FCM support and welcome all contributions to the `v2.0.x` branch. I sympathize with your frustration but you really haven't given us much to go on as you haven't mentioned what you tried. I suggest you give us more details as to what your issue is in #929 so we can make sure we cover your use case.

As always PR's are welcome, whether they be code or docs.

**Comment by jcesarmobile** [comment]
If you use the Phonegap developer app to test, FCM won't work because FCM support is only available on the v2.0.x branch, and the Phonegap developer app doesn't even use this plugin, it uses a fork  which is at 1.8.3 at the moment https://github.com/phonegap/phonegap-app-developer/blob/master/config.xml#L56
Phonegap developer app is a tool to **preview** the result of your app easily without the need of compiling your own app, but it has limitations, one of them is that the plugin versions are fixed, so you can't use the latest version, other is that it mostly only support core plugins, not 3rd party ones, and the few 3rd party supported might be forks (like the push).
Also, I don't think even GCM work on the Phonegap developer app with your own data (sender ID and API key), as far as I know it can "simulate" the push sending them from an adobe account.
If you read the Push Notification section on the Phonegap developer app you can read:

> NOTE: You may notice the senderID is set to XXXXXXXX. That is okay as the PhoneGap Developer App will intercept this request and use the correct value. When you build an app for yourself you will need to get a senderID when you setup a project with Google to use GCM.

If it's not clear, the Phonegap developer app will ignore whatever you put there and use a hardcoded value, and when you build your own app it will use the real value, so you won't be able to send push from your server, only from the Phonegap CLI
http://docs.phonegap.com/tutorials/develop/push-notifications/

Using v2.0.x branch, basic push from FCM sent from the Firebase console should work just fine on iOS and Android. For basic I mean, it can receive the fields that Firebase console send (label, message, title and personalized data), but you have to run you app to test it, you can't do it on the Phonegap developer app
