### ISSUE TITLE
What is the id in push.finish?

### ISSUE THREAD

**Issue by yosiat** [phonegap/phonegap-plugin-push#1415]
Hi,

I saw that when I send push notification when my app is on the background (on ios 10), I need to call - `push.finish(successHandler, errorHandler, id)` so it will be silent notification.

What is the `id` in those arguments? is there a code example?

Thanks!

**Comment by macdonst** [comment]
@yosiat yeah, I need to make the docs more clear on that. From my section on [Action Buttons](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1):

_As well you should set a notId property in the root of payload object. This is the parameter you pass to the finish method in order to tell the operating system that the processing of the push event is done._

```
{
    "aps": {
        "alert": "Test background push",
        "content-available": 1,
        "notId": "1"
    }
}
```

**Comment by yosiat** [comment]
@macdonst Ok, I get it now :) just to make sure - if I send **silent** background notification, I don't need to pass the id?

**Comment by macdonst** [comment]
@yosiat you don't specifically need it unless you are sending two silent/background notifications in short order. Whenever possible you should include the `notId` to prevent collisions.

**Comment by yosiat** [comment]
@macdonst ok, thanks! closing the issue ~

**Comment by macdonst** [comment]
@yosiat I'm re-opening as I want to add stuff to docs.
