### ISSUE TITLE
Notifs push created but not received on ios 10 +

### ISSUE THREAD

**Issue by amauryleproux** [phonegap/phonegap-plugin-push#1431]
Hello :)

I try to send notifications push with Ionic and this plugin.
On iOS < 10 it's alright but on iOS >= 10 it's not working.

I don't get logs errors and I get this in console: 

Request URL: https://api.ionic.io/push/notifications
Request Method: POST
Status Code: 201 CREATED 

But I don't receive any notifications, my token is good.

Notif push in xcode is turn on.

Any ideas?

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by amauryleproux** [comment]
seriously….



Amaury Leproux

**Comment by fredgalvao** [comment]
You didn't provide any of the following information:
- what version of the plugin you're using
- what version of cordova/phonegap you're using
- what push service you're using (APNS, GCM, FCM, Pushy.me, etc)
- what is the payload you're sending with your notification
- what is the code you're using to initialize the plugin on your app
- what logs xcode provided you when  you ran your app and reproduced the errors

Most, if not all of those topics are on the default issue template for this repository, and you put the effort to remove them instead of filling them. They are important, they're there for a reason. Please, help us help you and give us something to work on.

If you don't provide these, all we could do is wildly guess, and that's a loss of time for all of us.
