### ISSUE TITLE
Force app start

### ISSUE THREAD

**Issue by guestisp** [phonegap/phonegap-plugin-push#1471]
I'm trying to bring the app in foreground  (or opening it if forced close) on notification received with no success.

Is this possible ? I would like to create a sort of "alarm" that start when I send a notification but currently if the app is forced closed, only the notification in notification bar is shown

**Comment by fredgalvao** [comment]
Not possible yet. `notification arrival` doesn't wake the app up as the code is right now, you need `notification interaction` for that to be possible.

**Comment by jourdan-jobox** [comment]
One issue I'm running into would be solved if it was possible for the app to be awakened momentarily when the notification is received (if the app is killed); reason is because I want to store some data in the device's storage each time a notification is received (whether the app is in the background or the app is killed).

My question is, waking up the app when receiving notification: is this a feature that's going to be in the works or should I actually be taking a different approach here? Either way, at the moment I'm taking a different approach but I'm wondering if this is a great feature to have anyways.

**Comment by fredgalvao** [comment]
I think it's an amazing feature to have. Handle `notification arrival` and `notification interaction` as two different independent complete events, each of them with all of the behaviours the current normal `notification` event already has. I have some drafts of how those events could live on the client side scattered around on some semi-old issues, but I don't have the time to find them now.

It's mostly up to @macdonst to see if the API/plugin could support that separation of concepts completely and safely. I for one would love it.
