### ISSUE TITLE
Some help for a newbie? Installed okay, but Firebase notifications not coming through

### ISSUE THREAD

**Issue by jamminjames** [phonegap/phonegap-plugin-push#1513]
I have the plugin installed via Phonegap Build as per the instructions. I have Firebase set up with Google. I have the Firebase-generated google-services.json file in the root of the app. I have the push.js file in place and referred to in the index.html file.

But no notifications pushed from Firebase are coming through. 

I may be missing a step or two, not sure. Any help would be appreciated. 

### Expected Behaviour
Notifications on phone

### Actual Behaviour
No notifications

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG

#### Cordova CLI version and cordova platform version
cli-6.3.0

#### Plugin version
1.8.4

**Comment by malwatte** [comment]
What does FCM return? Success or error?
Do you get a GCM token in registration even handler?

**Comment by fredgalvao** [comment]
The section `Sample Code that illustrates the problem` of the issue template is empty, does that mean you have zero code on your cordova/phonegap application calling any plugin code? If that's the case, you should be calling `init` and registering a bunch of event listeners. If that's not the case, please provide whatever is your plugin initialization code and try to provide some more context, like the sister `Sample Push Data Payload` section, which is also empty.

**Comment by jamminjames** [comment]
@fredgalvao, Thanks for the response! So, are you saying something like this should be wrapped in a `function onDeviceReady()` (or something else) section on the index page? I'm not clear on where to put it or how to use it: 

`var push = PushNotification.init({
    android: {
        senderID: "382900667859" // HT's
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});

push.on('registration', function(data) {
    // data.registrationId
});

push.on('notification', function(data) {
    // data.message,
    // data.title,
    // data.count,
    // data.sound,
    // data.image,
    // data.additionalData
});

push.on('error', function(e) {
    // e.message
});`

**Comment by fredgalvao** [comment]
First and foremost, if you're using FCM, you need to be using branch v2 of this plugin.

Second, yes, you need to call `init` on the PushNotification global object to initialize and bind  stuff on the native side of the plugin, otherwise it won't know when to spin. You can check both tutorials linked at the root of our documentation, [[here. if you're lost](https://github.com/phonegap/phonegap-plugin-push/blob/master/README.md)], to get a grasp of all the workflow needed for the plugin to work.

For the `browser` thing, if you're not testing the plugin and push notification on an actual desktop browser, then you don't need to do anything with that (leave the `browser` section of the init object away).

As for localization, I'd blindly say that you don't need to worry about it right now, but @macdonst might have a more concrete answer. I have used this plugin for about 2 years now, and I am still to touch localization, and everything works, so...

**Comment by jamminjames** [comment]
So, to use v2, since I'm compiling with Phonegap Build, do I use this for the line in config.xml?
`<plugin name="phonegap-plugin-push" spec="~2.0" source="npm" />`

**Comment by macdonst** [comment]
@jamminjames version 1.x should work with PGB and GCM. Yes, I know that Google has moved to FCM and we have the 2.x branch that we are working on to fully support FCM. Right now the plugin won't build correctly on PGB and I'm working with them to fix it. When the 2.x branch is officially released it will work on PGB, PhoneGap CLI and Desktop App.

For now you'll either have to use GCM on PGB or FCM on the CLI.

**Comment by jamminjames** [comment]
Okay, thank you very much for the update.

**Comment by macdonst** [comment]
With 2.0.0-rc5 we should be able to support FCM on PGB
