### ISSUE TITLE
[Question] Get registration id whenever I want 

### ISSUE THREAD

**Issue by fgagneten** [phonegap/phonegap-plugin-push#1534]
How can I get the registration Id from my phone whenever I want? Now I only can get it like this:

> push.on('registration', function(data){ . . . }

I can't save it in local storage because the phone sometimes delete it. So I need to get it again when I have to use it.

**Example:** A user open my app and in the moment where the device is ready I got the registrationId and save it into local storage. The app automatically redirect to the login page. 
Up to this point everythings is right. Now the user must to go work, so he never logged in my app. 
When he come back, he remembered to use my app and logged in.
**And here is the problem:** Many hours passed and the local storage may be gone, so the user when try to logged in,  I sending to the server the registration id from the local storage, but the local storage is empty, so I sent to my server undefined value in my registrationId param.

So... to sum up How can I get the registrationId whenever I want?
Thanks!

**Comment by fredgalvao** [comment]
Everytime your user opens your app, you'll get that `registration` event triggered, and thus for every lifecycle of your application, you have access to that value as long as you keep it, even if it means **keeping it on memory**, like a static value on some object, or even like a property set on `window`. I still think localhost being erased is a much bigger issue than you think (and should be worried about), but that's not the matter. Nevertheless, as I said, you can fix it by just keeping the value in memory.

Now, even though there is that solution, I still agree with you that the plugin API should have a more programmatic way of obtaining that instead of **always waiting for an event**.

@macdonst this is one of the things that I have in mind for the bold **api overhaul** I mentioned I wanted to do a while ago.

**Comment by jcesarmobile** [comment]
I think FCM included a method to check the value. If I'm right, we can use that.
But for iOS users not using FCM it won't work.

**Comment by fredgalvao** [comment]
Even then, if we receive the value early once every app lifecycle, we can save it as a static value on native side and allow a getter for it through the js api.

**Comment by macdonst** [comment]
@fgagneten right now it is up to you to save the registration ID whether you use localStorage, the File API or another method is up to you.
