### ISSUE TITLE
Android: White square is shown instead of the notification icon

### ISSUE THREAD

**Issue by sidlauskaslukas** [phonegap/phonegap-plugin-push#1579]
### Expected Behaviour
White notifcation icon with the transparent background is shown when you get a push notification. The color of the notification circle is the one you set in the options.

### Actual Behaviour
White square is shown when you get a push notifcation. The color of the notification circle is not the one you set in the options.

### Reproduce Scenario
1. Copy x24, x36, x48, x72, x96 size .png push notification white icons with the transparent background to relevant "drawable-*" folders in the "platforms/android/res/" directory. The name of the icons is "ic_stat_notify".
2. Set the icon name and color in the options object which you pass as an argument to "init" function. E.g.:
```
{
      android: {
        icon: 'ic_stat_notify',
        iconColor: '#106A9E',
        senderID: XXXXXXXXX
      }
}
```
#### Platform and Version
Android 6.0.1

#### (Android) What device vendor
Sony Xperia Z3

#### Cordova CLI version and cordova platform version

Cordova CLI version 6.4.0
Cordova Android platform 6.1.0

#### Plugin version
1.9.2 / 1.9.1

It seems that the plugin is using the wrong icon for notifications. I managed to get the expected behaviour only after downgrading the cordova android platform version to 5.2.2 and the plugin to 1.3.0.

**Comment by gabrieldarezzo** [comment]
I think this can be useful for this issue:

https://github.com/phonegap/phonegap-plugin-push/issues/422#issuecomment-164415474

**Comment by sidlauskaslukas** [comment]
@gabrieldarezzo it seems that upgrading the cordova android platform version to 6.1.2 helped me to solve this issue and get the expected behaviour. Not sure how this could be related to Cordova itself. Any thoughts?

**Comment by gabrieldarezzo** [comment]
I guess the fault of White Square is because 'alfa layer' exactly like #422.

Im happy you fixed :)

**Comment by sidlauskaslukas** [comment]
@gabrieldarezzo but I haven't changed the icon. The icon I use is white with the transparent background as required.

**Comment by macdonst** [comment]
@sidlauskaslukas are you still running into this problem? If so can you reproduce the issue when running `adb logcat | grep PushPlugin`? As well I need to see the payload you send to the device.

**Comment by kadza** [comment]
Hi,

I've been experimenting with the plugin for two days and I was able to reproduce it. The configured color and icon are not used.

The app icon is used instead of the configured icon.
When I use my app icon, I have the white square.
When I use the Cordova default app icon, I can see the Cordova symbol.

Platform and Version
Android 6.0.1

What device vendor
Nexus 5

Cordova CLI version and cordova platform version
Cordova CLI version 6.5.0
Cordova Android platform 6.1.2

Plugin version
1.9.4

App first start

Logs:
02-28 12:11:02.550 19030 19203 V PushPlugin: execute: action=init
02-28 12:11:02.551 19030 19204 V PushPlugin: execute: data=[{"android":{"senderID":"***","iconColor":"#FF0000","icon":"kuku"},"ios":{"senderID":"***","gcmSandbox":true}}]
02-28 12:11:02.551 19030 19204 V PushPlugin: execute: jo={"senderID":"***","iconColor":"#FF0000","icon":"kuku"}
02-28 12:11:02.551 19030 19204 V PushPlugin: execute: senderID=***
02-28 12:11:02.576 19030 19204 V PushPlugin: onRegistered: {"registrationId":"***"}

App is in background
Push notification comes
I tap on the notification
App is brought to foreground
On "notification" callback is not called. 
(offtopic) On iOS the callback is called and here I would expect the same behaviour.

App is in foreground
On "notification" callback is called

Logs: 
02-28 12:11:58.346 19030 19872 D PushPlugin_GCMIntentService: onMessage - from: ***
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: normalize extras
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: key = google.sent_time
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: replace key google.sent_time with google.sent_time
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: key = google.message_id
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: replace key google.message_id with google.message_id
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: key = notification
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: notifkey = body
02-28 12:11:58.347 19030 19872 D PushPlugin_GCMIntentService: replace key body with message
02-28 12:11:58.349 19030 19872 D PushPlugin_GCMIntentService: no locale found for key = message, error Value aaa of type java.lang.String cannot be converted to JSONObject
02-28 12:11:58.349 19030 19872 D PushPlugin_GCMIntentService: key = collapse_key
02-28 12:11:58.349 19030 19872 D PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
02-28 12:11:58.349 19030 19872 D PushPlugin_GCMIntentService: foreground
02-28 12:11:58.349 19030 19872 D PushPlugin: convert extras to json
02-28 12:11:58.349 19030 19872 D PushPlugin: key = google.sent_time
02-28 12:11:58.349 19030 19872 D PushPlugin: key = google.message_id
02-28 12:11:58.349 19030 19872 D PushPlugin: key = message
02-28 12:11:58.349 19030 19872 D PushPlugin: key = coldstart
02-28 12:11:58.350 19030 19872 D PushPlugin: key = collapse_key
02-28 12:11:58.350 19030 19872 D PushPlugin: key = foreground
02-28 12:11:58.350 19030 19872 V PushPlugin: extrasToJSON: {"message":"aaa","additionalData":{"google.message_id":"0:1488280317987554%7a21adbc7a21adbc","coldstart":false,"collapse_key":"com.kuku","foreground":true}}

**Comment by kadza** [comment]
In my case the root of the problem is probably in the payload generated by the FCM test console.
After I switched to the node-gcm and the payload
    "data" : {
        "title": "Test Notification",
        "body": "This offer expires at 11:30 or whatever",
        "notId": 10,
        "surveyID": "ewtawgreg-gragrag-rgarhthgbad"
    }
the plugin works as expected.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
