### ISSUE TITLE
Badge increment in push notification on Android

### ISSUE THREAD

**Issue by madara134** [phonegap/phonegap-plugin-push#1597]
### Expected Behaviour
Badge not increment when receive more push notification on android 
### Actual Behaviour
Badge count allway some one
#### Steps to Reproduce 
i want badge auto increment when receive more push if notification not tap in background , foreground
Thanks (sorry my English is bad )
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.2
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
LG
#### Cordova CLI version and cordova platform version

    cordova --version                                    # 6.5.0
    cordova platform version android                     # android 6.1.2

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # 1.8.2

#### Sample Push Data Payload
    "data" : {
	  "title": "New title",
           "message": "New Message",
           "content-available": 21,
           "badge": "1"
      },
#### Sample Code that illustrates the problem
    push.on('notification', data => {
            let page = data.additionalData.page;
            let id = data.additionalData.id;
            if (!data.additionalData.foreground) {
                  push.getApplicationIconBadgeNumber(count => {
                  this.service.SendToken(count, Device.uuid);
                  push.setApplicationIconBadgeNumber(() => {
                   }, () => {
                  }, count + 1);
                }, () => {
               })
        this.platform.ready()
          .then(() => {
             if (!this.modal) {
              this.modal = this.modalCtrl.create(this.pages[page].pagechild, { id: id });
              this.modal.present()
                .then(() => {
                  this.content.insert(1, this.pages[page].component)
                })
                .then(() => {
                  push.setApplicationIconBadgeNumber(
                    () => {
                    }, () => {
                    }, 0);
                })
            }
          })
      }

**Comment by macdonst** [comment]
@madara134 do you ever get the badge updated on your icon? Have you checked to make sure your [device is supported by ShortcutBadger](https://github.com/leolin310148/ShortcutBadger#supported-launchers)? Did you try their [test app](https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking)?

**Comment by madara134** [comment]
yes, i was test my app. my device is supported by shortcutbadger, but it only receive badge number  when my server send.. I sent 2 times with the same payload with badge number : 1. but only badge is now 1 not 2

**Comment by fredgalvao** [comment]
Oh I see now.
Currently, you need to manage your badge number on your server alone, so that if you're sending your second payload and the user hasn't somehow notified the server back of the delivery and interaction of the first payload, you need to send `"badge": "2"`.

I agree though, that the best option would be to allow the api to change that programmatically by the user. @macdonst Do you see any reason why would it NOT be possible to implement the api like this? We've seen this topic on issues multiple times by now.

**Comment by falinsin** [comment]
What say fredgalvao is just my problem. We need decrease in the APP the badge wen users interact with de content of the push notification. For example, if users go into the App and read the details from that notification.

But We can´t decrease its badge form the APP itself. We are force to next notification in order to decrease / update the icon badge number.

Anybody found a solution to this? Thanks in advance

**Comment by macdonst** [comment]
Closing this as original issue has been answered.

**Comment by fredgalvao** [comment]
@macdonst Do you think this would fit into a valid feature-request issue?
> I agree though, that the best option would be to allow the api to change that programmatically by the user. @macdonst Do you see any reason why would it NOT be possible to implement the api like this? We've seen this topic on issues multiple times by now.
