### ISSUE TITLE
IOS PushNotification var in another page

### ISSUE THREAD

**Issue by Lulun10** [phonegap/phonegap-plugin-push#1649]
Hi,

I develop an app with push notification on IOS.
I load push on load in my first page : index.html with PushNotification.init().

I want to test my push on another page, then I call PushNoticiation.hasPermission() on my notifications.html page. But in notifications.html page script stop with this call. I think plugin is not load but I test with this code without solution :

```
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="myscript.js"></script>
```
and with :

```
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="plugins/phonegap-plugin-push/www/push.js"></script>
<script type="text/javascript" src="myscript.js"></script>
```
Do you have an idea ?

Thank.

**Comment by macdonst** [comment]
@Lulun10 my advice is not to do what you are trying to do. When developing a hybrid application it is best to follow the single page architecture in order to prevent you app from having to load and unload the Javascript all the time. 

https://medium.com/@NeotericEU/single-page-application-vs-multiple-page-application-2591588efe58#.u0pt6kp53
