### ISSUE TITLE
AndroidLaunchMode:singleInstance, tapping on notification does not bring app to foreground  in 

### ISSUE THREAD

**Issue by spakalnis** [phonegap/phonegap-plugin-push#1690]
### Expected Behaviour
Tapping on notification brings app to foreground 

### Actual Behaviour

Tapping on notification  starts app if it was not started as expected: 
    PushPlugin_PushHandlerActivity: isPushPluginActive = false
    PushPlugin_PushHandlerActivity:  forceMainActivityReload   

Tapping on notification if the app is in background:  
    PushPlugin_PushHandlerActivity: isPushPluginActive = true
    PushPlugin_PushHandlerActivity: don't want main activity  

New to Cordova hence please bear with my naive questions: 

1. Why setting AndroidLaunchMode to singleTop (which we can not use) fixes issue above

2. Why we do not forceMainActivityReload if isPushPluginActive = true? 

3. in PushPlugin,  "gWebView" gets set on "execute"  and gets cleared on "destroy"  does that mean gWebView will not be cleared as long as app is alive? 

Thanks!

**Comment by macdonst** [comment]
@spakalnis these are more Android questions than Cordova ones but here are the answers to the best of my ability.

1) If you set your activity to "singleInstance" then it can't start new activities in the same task space. In order to handle when the notification is clicked I need to start a new activity which brings the app to the foreground but "singleInstance" prevents this. https://developer.android.com/guide/topics/manifest/activity-element.html#lmode

2) We don't force the main activity to be reloaded if the push plugin is active because that means the main activity is already in memory.

3) Yes, and that is the behaviour we want. If the web view is not in memory it can't run javascript so things like action buttons, your on('notification') handlers, etc would not be called if we let the web view get garbage collected.

**Comment by spakalnis** [comment]
Thanks!  What people do if they want to use "singleInstance" ?    Would forcing isPushPluginActive = false. make sense in this case?

**Comment by macdonst** [comment]
@spakalnis not sure why you'd want to use "singleInstance" it's kinda a special case that is usually only used by launcher apps.

**Comment by spakalnis** [comment]
@macdonst Thanks for quick response Simon! Without "singleInstance" deep links would open multiple instances of the app, which we do not want.  Are there any other downsides of adding option to force mainActivity reload every time apart from slowness? (if that is not reasonable, will try to replace "singleInstance")

**Comment by macdonst** [comment]
@spakalnis You should switch to `singleTop`
