### ISSUE TITLE
No notification configure or show in iOS 10.3.1

### ISSUE THREAD

**Issue by rogerhaw** [phonegap/phonegap-plugin-push#1694]
### Expected Behaviour
Multiple phones iphone 6 and 7 running ios 10.3.1 should configure for and recieve push notifications.
User prompted to allow push notifications on app install and show settings in notifications area.

Works in ios 10.2.x and earlier on iphone 6 and iphone5s

### Actual Behaviour
User not prompted to allow push notifications
App in notifications area is not present (i.e. cant set push settings)
No push notifications appear

### Reproduce Scenario (including but not limited to)
Update iOS to 10.3.1 
Re-install app
Push notifications dont prompt user on install
Push notifications config dont appear in settings for app
Push notifications are not sent

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10.3.1

#### Cordova CLI version and cordova platform version
cordova ios 4.3.1

#### Plugin version

push plugin 1.9.4

**Comment by macdonst** [comment]
@rogerhaw I would guess that this is a certificate problem or the push permission is not turned on in your cert

**Comment by rogerhaw** [comment]
Hi
No same app works on different version and phone as described
Thx

Regards,
Roger

**Comment by eftas-apps** [comment]
I'm having the same issue.

**Comment by kingdark1234** [comment]
me too same issue.

**Comment by massimilianozilio** [comment]
I am having the same issue with Cordova 6.5.0 and  phonegap-plugin-push 1.8.1. 
Same app works  fine on Android and previous iOS version.

**Comment by guilhermelirio** [comment]
I'm testing my app through the Phonegap Developer App. Why can I get the push notification?

**Comment by massimilianozilio** [comment]
Hi,
Push notification work fine on iOS 10.3.1 if I use Distribution or AdHoc
certificate, however I still can't explain why on previous iOS versions I
am able to receive push notification with also a Development certificate.

I have updated the thread on Github.

**Comment by macdonst** [comment]
Folks, I wish I could help with this but in 99% of the cases it ends up being a problem with the certificate the app is built with not matching the certificate you are using to send the push notification. Often people are sending to a production app with a cert built for development. Even my team is not immune to this as we released the PhoneGap Developer App 1.7.7 built with the wrong cert.

One other thing you can try is opening the project in Xcode, go to the capabilities tab and make sure Push Notifications is turned on.

**Comment by eftas-apps** [comment]
Thanks for your answer first of all. 
I noticed some strange behaviour though. And this seem not related to wrong certs. 

When I start the app on iOS it does not receive push notifications. But once I unsubscribe and resubscribe to topics the push notifications all of a sudden come through. 

I'm currently not at my developing machine so I can not send you logs. Sorry for that. Will try to post them as soon as possible. But there was nothing striking.

**Comment by larssn** [comment]
We're seeing the same issues. Our certs seem correct (they work with other FCM cordova plugins). However we switched to this because the code base seem more mature and better maintained.

We're on 2.0.0RC3. Could it be related to fcmSandbox?

We've tried setting it to true when doing a normal dev build: no notifications.
Tried setting it to false when doing a production push to the app store: no notifications.

We have a dev cert and a distribution cert, which seem to do what they're meant to.

Kinda stuck, help appreciated.

**Comment by macdonst** [comment]
@larssn hard to tell as we can't reproduce the issue. Can you open the workspace in Xcode and make sure push is enabled in capabilities?

**Comment by larssn** [comment]
@macdonst We ended up having to fall back to the other FCM plugin, which we're kinda bummed out about, since we were eyeballing some of the nice features in this.

I can easily recall from memory that push was enable under capabilities, because we checked it ourselves many times.

Anyway, appreciate the reply.
