### ISSUE TITLE
I do not get push on Phonegap Developer App!

### ISSUE THREAD

**Issue by guilhermelirio** [phonegap/phonegap-plugin-push#1723]
I'm testing my app through the Phonegap Developer App. Why can I get the push notification via FCM?

In android, working perfectly, error only in iOS:

`results":[{"message_id":"0:1494692918002318%a69a7507f9fd7ecd"}]`

phonegap-plugin-push = 1.10.2

**Comment by jcesarmobile** [comment]
When you use Phonegap Developer App you are not really running your app, just previewing it.

Phonegap developer app includes a feature to preview push notifications, but they can be sent from the CLI only because on iOS you have to use certificates, and those certificates have to match with the provisioning profile, as you are not using your own app, but the Phonegap Developer App, you can't use your own certificates because the app belongs to Phonegap team, not to you. 

Run your app instead of previewing it and then it should work.

**Comment by macdonst** [comment]
@guilhermelirio 1.7.7 had a bug so make sure you are using 1.7.8.
