### ISSUE TITLE
How to use force-start: 1 to automatically bring to foreground on Android

### ISSUE THREAD

**Issue by snakeman21** [phonegap/phonegap-plugin-push#1779]
### Expected Behaviour
I'd like to be able to move the app to the foreground immediately on my Android. Ironically, this behavior has been raised as an issue https://github.com/phonegap/phonegap-plugin-push/issues/1402. But this is my intended behavior.

### Actual Behaviour
Right now you can only force open it in to background mode. However, I am not even able to use this plugin to switch it to foreground https://github.com/katzer/cordova-plugin-background-mode.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Motrolla Moto G5

#### Cordova CLI version and cordova platform version
Phonegap version 6.5.0 / Cordova-Android 6.0.0

#### Plugin version
1.9.0

**Comment by macdonst** [comment]
@snakeman21 sorry that is not good Android behaviour. I won't be implementing that as a feature.

**Comment by snakeman21** [comment]
Well how would I be able to do this? Facebook Messenger's video chat is like this. It makes the UI really nice because you can simply answer or reject the call. For iOS I'm using CallKit for my video chat, but this seems to be the best solution on Android. I just need an easy way on Android to answer video calls.

**Comment by snakeman21** [comment]
@macdonst Obviously you're the boss, since this is your plugin. But don't you think it should at least be an option, and let the developer decide whether or not it is good Android behavior? Your view is certainly not universal, as Facebook Messenger, Skype and Oovoo all do the behavior mentioned.

Just wondering, what is even the point of forcing the app open and not putting it in the foreground? You can't even do anything until the app is put in the foreground, so it seems like a pointless feature right now anyway.

**Comment by macdonst** [comment]
@snakeman21 well, this is an open source project so the code can freely be forked if someone wants to add this functionality and support it going forward. I can only put so much time/energy into this plugin and I don't feel what you are asking for is a good idea. 

Imagine this scenario, I'm playing Kwasey Cupcakes and you send a push notification to my device. All of a sudden my game goes away and your app is moved the the foreground. I might be a bit annoyed by this behaviour if I'm your user. IIRC Google documents somewhere not to do this.

The point of forcing the app open and putting it in the background is so that the service that handles the incoming push message and pass it to the web view to execute Javascript in the background.

For your particular case it seems like you want the notification to be shown to the user all the time which means you should be setting the priority of the notification to HIGH or MAX. Then you can put in some action buttons to have the user answer or reject the call.

**Comment by snakeman21** [comment]
Ya true, in most scenarios it's annoying and shouldn't be done. But if you were playing Kwasey Cupcakes and you received a phone call, wouldn't you be receiving a notification with the phone's native calling app in the foreground, so to speak?

Ah ok, I see why that could be useful. Ya, i think I'm gonna go with your suggestion for version 1. For iPhone, CallKit works a charm. Android has ConnectionService, but there aren't any Cordova plugins for it unfortunately yet.
