### ISSUE TITLE
Build iOS app without Firebase

### ISSUE THREAD

**Issue by netomia** [phonegap/phonegap-plugin-push#1825]
### Expected Behaviour
I wish to use this plugin for iOS without importing firebase plist.

### Actual Behaviour
If I do not include the firebase plist reference in my config.xml, I get this error: module FirebaseInstanceID not found

### Reproduce Scenario (including but not limited to)
Create app, add plugin, build

#### Steps to Reproduce 
Create app, add plugin, build

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Cordova 7.0.1
iOS platform 4.4.0

#### Plugin version
2.0.0-rc5

**Comment by macdonst** [comment]
@netomia when do you get the error? Is it build time or run time?

**Comment by netomia** [comment]
Build.

cordova create App debug.testing Debugtest
cd App
cordova plugin add https://github.com/phonegap/phonegap-plugin-push
cordova platform add ios
cordova build

Error: PushPlugin.m:30:9: fatal error:
module 'FirebaseInstanceID' not found
@import FirebaseInstanceID;
1 error generated.

** BUILD FAILED **

**Comment by macdonst** [comment]
@netomia did you install CocoaPods? It seems like you system fails to install the pods and that's why you are getting that error.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#cocoapods

**Comment by netomia** [comment]
I did install CocoaPods and run 'pod setup'.

Now I did the following:

cd App/platforms/ios
pod install

That seemed to install missing stuff, and now the app builds.

Sorry if this was implied. I didn't find it anywhere in the documentation.

**Comment by macdonst** [comment]
@netomia you should not need to do that step. Cordova-ios should do it for you.

**Comment by netomia** [comment]
Well... not on my system :) I did try with a completely fresh installation/app and updated Cordova-ios.

**Comment by macdonst** [comment]
@netomia yeah, sorry you ran into that. I will see if I can reproduce it.

**Comment by mthahzan** [comment]
I had to manually run `pod install` from inside ./platforms/ios.

My system info

**global packages:**

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

**local packages:**

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

**System:**

    Node       : v6.9.5
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : not installed

`pod --version` is `1.3.1`

**Comment by raghav-khunger** [comment]
It is a bug in cordova-ios in their current version:

Even after following tons of stuff here and there I was not able to remove that error.

Here are the steps I have tried

Navigating here will lead to similar documentation: https://github.com/phonegap/phonegap-plugin-push/commit/a747ec16c0bd0c80b3fbbdc13eeec7ee3f107f60

![image](https://user-images.githubusercontent.com/904902/33792851-c585fa0a-dcd0-11e7-9422-6e44c73d4263.png)

I was getting the similar error in my Xcode 

![image](https://user-images.githubusercontent.com/904902/33792858-0cc0e65a-dcd1-11e7-9ded-08e1a844fd27.png)

It happened after I built my Ionic app for release on ios platform with the following command
`ionic cordova build ios --release`

As per https://github.com/phonegap/phonegap-plugin-push/commit/a747ec16c0bd0c80b3fbbdc13eeec7ee3f107f60 documentation I tried running the follwing commands 

```
cd platforms/ios
pod install
```

but it didn't succeed and I got the following message: pod command not found

![image](https://user-images.githubusercontent.com/904902/33792875-bf365392-dcd1-11e7-8c7f-eeb0bba1d185.png)

After some research I found out that I need to run "sudo gem install cocoapods" command first

With the help of It is a bug in cordova-ios in their current version:

Navigating here will lead to similar documentation: https://github.com/phonegap/phonegap-plugin-push/commit/a747ec16c0bd0c80b3fbbdc13eeec7ee3f107f60

![image](https://user-images.githubusercontent.com/904902/33792851-c585fa0a-dcd0-11e7-9422-6e44c73d4263.png)

I was getting the similar error in my Xcode 

![image](https://user-images.githubusercontent.com/904902/33792858-0cc0e65a-dcd1-11e7-9ded-08e1a844fd27.png)

It happened after I built my Ionic app for release on ios platform with the following command
`ionic cordova build ios --release`

As per https://github.com/phonegap/phonegap-plugin-push/commit/a747ec16c0bd0c80b3fbbdc13eeec7ee3f107f60 documentation I tried running the follwing commands 

```
cd platforms/ios
pod install
```

but it didn't succeed and I got the following message: pod command not found

![image](https://user-images.githubusercontent.com/904902/33792875-bf365392-dcd1-11e7-8c7f-eeb0bba1d185.png)

After some research I found out that I need to run "sudo gem install cocoapods" command first
in order to make pod install work. Therefore, I ran that command first:
 
![image](https://user-images.githubusercontent.com/904902/33792891-422115c6-dcd2-11e7-817c-f02e74e91a77.png)

and when the "gems" installed I tried "pod install" command and this time it worked:

![image](https://user-images.githubusercontent.com/904902/33792899-8421d4c4-dcd2-11e7-82d5-c42081768fec.png)

After a long wait it installed and I got "Pod installation" message:
![image](https://user-images.githubusercontent.com/904902/33792910-b39a0564-dcd2-11e7-8c85-70490f60f1d9.png)

I have already added the two custom user settings in my Build Settings of Xcode

PODS_ROOT ---- ${SRCROOT}/Pods

PODS_PODFILE_DIR_PATH ---- ${SRCROOT}

**Comment by glebmachine** [comment]
any updates?

**Comment by kyale-mwendwa** [comment]
IF you have tried all the above methods to no avail try this. 

In your platform/ios you should have the following files pods-debug-xconfig and pods-release.xconfig if they are not present ensure you have cocoapods installed on your system then run the following commands and ensure the phonegap-plugin-push is still a plugin in the project 

cordova platform rm ios
cordova platform add ios

They should now be in the ios directory.
Go to the ios directory and run

pod install --verbose

Then navigate to the directory platform/ios/Pods/TargetSupport Files/Pods-yourproject and look for 
Pods-yourproject.debug.xconfig
Pods-yourproject.release.xconfig

you need to copy the content of these files into these files in platform/ios
pods-debug-xconfig and pods-release.xconfig respectively. 

This should solve the problem, it strikes me as a bug to be honest. Please let me know if this resolves your problem.
