### ISSUE TITLE
Use Google's InstanceID API

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#188]
https://developers.google.com/instance-id/guides/android-implementation

**Comment by bhaveshgohel** [comment]
:+1:

**Comment by bau720123** [comment]
if could
well..that will really awesome!!!

**Comment by miraculixx** [comment]
To add some perspective -- this is not an _awesome_ feature but a requirement by Google:

According to [this](https://developers.google.com/cloud-messaging/android/legacy-regid), the `gcm.register` is deprecated since May 2015:

_GCM register() is deprecated starting May 28, 2015. New app development should use the Instance ID API to handle the creation, rotation, and updating of registration tokens._

While there do not seem to be direct implications (it still works), it would be prudent to plan for migration for the day will come when GCM stops accepting new register() calls.

**Comment by macdonst** [comment]
@miraculixx Agreed, that's why I'm working on it. :smiley_cat:

**Comment by miraculixx** [comment]
@macdonst glad to hear :+1: thanks

**Comment by macdonst** [comment]
Anyone who wants to test it can check out branch `issue188`. It seems to be working just fine but I need to do more testing.

**Comment by macdonst** [comment]
Fix committed will be official in 1.4.0 release.

**Comment by bhaveshgohel** [comment]
Thanks @macdonst ! :+1: 
Can you please also update the README.md file to reflect the changes on how to use it. :smiley:

**Comment by bau720123** [comment]
+1

**Comment by macdonst** [comment]
@bhaveshgohel I already did under Android compilation. No changes to JS code are necessary.

**Comment by bhaveshgohel** [comment]
Ohh... Thanks @macdonst! :smiley:

**Comment by jayj** [comment]
It added the "Find accounts on the device" Contact permission. What is that permission used for, if it's used?

**Comment by macdonst** [comment]
@jayj Hmm...that is Google Play Services adding that. Lemme see if I can make that smaller.

**Comment by macdonst** [comment]
@jayj I just merged a PR from contributor @smdvdsn that should remove the need for the "Find accounts on device" permission.

**Comment by chrillewoodz** [comment]
@macdonst  I've looked everywhere but I cannot find how to get hold of an InstanceID using this plugin... Can you shed some light on it?
