### ISSUE TITLE
How to turn off (and on) push sound?

### ISSUE THREAD

**Issue by malwatte** [phonegap/phonegap-plugin-push#1891]
Hi,

How to turn off (and on) push sound? I want to allow users to turn on/off push sound in app setting screen. I can not change push payload. I want to do it in app itself.
Any help is greatly appreciated.

Thanks

**Comment by fredgalvao** [comment]
According to the docs:

- on Android you can already do it by specifying `"soundname": ""` on the payload, [see here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound)
- on iOS there is no documented way to do it, but I have a feeling it'd be either already available or easy to implement. @macdonst is the best bet to answer this

**Comment by fredgalvao** [comment]
Now, if you want to be able to programmatically enable/disable it, you'd have to save a preference for your user's data and send it to your server, so that when you send a notification from it you'd know which value to send on `soundname`. However, there is no way for you to send one single payload notification and have it play a sound for some users and not play for others.

**Comment by macdonst** [comment]
@malwatte For iOS you just have to omit the `sound` property from the payload. For Android it is as @fredgalvao mentioned and it's already documented. 

You will not be able to do it in the app yourself. You'll either have to direct the user to the settings section of their phone to turn off the sound of push notifications for your app or do it the right way. If you provide a setting in your app to turn off the sound then it sends a message to your app server to tell it not to send sounds to the registrationID of the user who just turned off the sound.
