### ISSUE TITLE
Background Notification: JS stops executing after around 2 seconds

### ISSUE THREAD

**Issue by superbigsoft** [phonegap/phonegap-plugin-push#1967]
### Expected Behaviour
JS keeps executing until **finish** is called or 30 seconds is over

### Actual Behaviour
JS execution is paused after around 2 seconds

#### Steps to Reproduce 

1. Debug app with XCode
2. Put app to background
3. Send a silent-push ('content-available': 1)
4. Observe the counter is printed up to 2 while it should print up to 9 

#### Platform and Version
iOS 11

#### Cordova CLI version and cordova platform version
7.0.1 & 4.4.0

#### Plugin version
1.6.2

#### Sample Push Data Payload
```
 aps =   {
        alert = "Hello world";
        badge = 1;
        "content-available" = 1;
        sound = default;
    };
```

#### Sample Code that illustrates the problem
```
pushNotification.on('notification', function (data) {
    // Print a counter every second
    var i = 0;
    var timer = setInterval(function() {
        console.log(i++);
    }, 1000);
    
    // Finish after 10 seconds
    setTimeout(function() {
        clearInterval(timer);
        pushNotification.finish()
    }, 10000)
});
```

**Comment by fredgalvao** [comment]
According to [this](https://stackoverflow.com/questions/6543325/what-happens-to-javascript-execution-settimeout-etc-when-iphone-android-goes) and to my interpretation of [some quirks of cordova events on ios](https://cordova.apache.org/docs/en/latest/cordova/events/events.html) that's almost *expected behaviour*. Could you try reproducing it with something other than a timer?

**Comment by uj** [comment]
I have the same problem, and I am doing it almost exactly like you are.  I have a "finish" timer set to 5 seconds (because 5 seconds is plenty of time, and makes it easy to always call finish).  However, I often find that my app has been forced-closed when I open it later, as though "finish" was never called and the OS forced closed the app after 30 seconds.  I'm wondering if timers don't work in the background, so finish never gets called, and the app is killed?

**Comment by macdonst** [comment]
@superbigsoft I'm pretty sure iOS will kill your setTimeout/setInterval when the app goes to the background. When I get a chance I'll verify.

**Comment by superbigsoft** [comment]
@fredgalvao Yes it's working with simple JS. For instance if i have a loop that prints the counter up to 9999 then it's working fine. All output are printed out correctly.
@macdonst Thanks. Do you know a list of things that iOS will kill?

**Comment by macdonst** [comment]
@superbigsoft based on all of my research on this topic it appears that iOS will pause your setTimeout/setInterval command when the app is in the background and won't fire until the app comes to the foreground again. There's nothing I can do about this quirk in iOS, sorry.

https://stackoverflow.com/questions/6543325/what-happens-to-javascript-execution-settimeout-etc-when-iphone-android-goes
