### ISSUE TITLE
Android + Firebase Cloud Messaging: Clicking tray notification doesn't call .on("notification") handler

### ISSUE THREAD

**Issue by shawnlan** [phonegap/phonegap-plugin-push#1969]
I'm using Firebase's Notification Composer. I filled in Message Text and Title, and in the custom data I also add "body" and "title" key-value pairs.

When the app is in the background, clicking the tray notification launches the app, but the "notification" handler is not called. Possible bug?

**Comment by macdonst** [comment]
@shawnlan in the future please fill out the issues template and search the past issues before you open a new one. The root cause of your issue is the FCM console sends everything in `notification` when this plugin needs it in `data`.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads

**Comment by shawnlan** [comment]
@macdonst sorry I did searched the past issues and read the docs you included before posting. I put "body" and "title" in the custom data as suggested in the docs. But still it didn't work as expected. Any idea?
