### ISSUE TITLE
push plugin says is not installed when it is (ionic 3)

### ISSUE THREAD

**Issue by francoro** [phonegap/phonegap-plugin-push#2125]
Native: tried calling Push.hasPermission, but the Push plugin is not installed.
(anonymous) @ ion-dev.js:156
ion-dev.js:156 Install the Push plugin: 'ionic cordova plugin add phonegap-plugin-push'
(anonymous) @ ion-dev.js:156
ion-dev.js:156 Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.

**Comment by macdonst** [comment]
Sorry to be a jerk but I'm now closing issues that don't follow the issue submission guidelines. This plugin takes a lot of work to maintain and I can't afford the time required to solicit the required info from everyone.

I'm closing this issue but please feel free to re-open the issue if you provide the requested details from the new issue submission guidelines.

https://github.com/phonegap/phonegap-plugin-push/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Michazzz** [comment]
### Expected Behaviour
Successfull device registration by the phonegap-push-plugin

### Actual Behaviour

> Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.
> pluginWarn @ main.js:58006

### Reproduce Scenario (including but not limited to)
Install plugin via instruction available here: [https://ionicframework.com/docs/native/push/](url)

run command: ionic cordova run android --device

check the logs in Google Chrome tab: chrome://inspect

#### Steps to Reproduce 

Same as above

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 6.0.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung Galaxy Note 4

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.0.1
    cordova platform version android           6.4.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push           2.1.2

#### Sample Push Data Payload
Not need to reproduce right now.

#### Sample Code that illustrates the problem
The code tag not working properly.... 
`  private pushInit() {
    let pushObject = this.push.init({
      android: {
        senderID: "559622574607",
        sound: 'true',
        forceShow: true,
      },
      ios: {
        alert: 'true',
        badge: true,
        sound: 'false'
      }
    });

    pushObject.on('registration').subscribe((registration: any) => console.log('Device registered', registration));
  }`

#### Logs taken while reproducing problem

> deviceready has not fired after 5 seconds.
main.js:143816 Ionic Native: deviceready event fired after 3970 ms
main.js:58006 Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.
pluginWarn @ main.js:58006
SQLitePlugin.js:175 OPEN database: _ionicstorage
SQLitePlugin.js:106 new transaction is queued, waiting for open operation to finish
SQLitePlugin.js:179 OPEN database: _ionicstorage - OK
SQLitePlugin.js:80 DB opened: _ionicstorage
