### ISSUE TITLE
Failed to install 'phonegap-plugin-push': undefined iOS @ionic 2 #2179

### ISSUE THREAD

**Issue by bhandaribhumin** [phonegap/phonegap-plugin-push#2180]
@jcesarmobile why my #2179 is closed ?

Error is 

Installing "phonegap-plugin-push" for ios

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /Users/bhuminb/Desktop/Projects/BLANKTest/node_modules/.bin in PATH, mode 040777

Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1 Error output:
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /Users/bhuminb/Desktop/Projects/BLANKTest/node_modules/.bin in PATH, mode 040777
    at ChildProcess.whenDone (/Users/bhuminb/Desktop/Projects/RTITest/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:2316) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: pod: Command failed with exit code 1 Error output:
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /Users/bhuminb/Desktop/Projects/BLANKTest/node_modules/.bin in PATH, mode 040777
(node:2316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

===>
Please help me! what exactly issue is?

**Comment by fredgalvao** [comment]
> Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1 Error output:
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:141: warning: **Insecure world writable dir /Users/bhuminb/Desktop/Projects/BLANKTest/node_modules/.bin** in PATH, mode 040777

It's right there. You still have your project's environment messed up on permissions/ownership, caused by the same mistakes discussed/pointed out on the previous issue (#2179). You need to either fix recursively the permissions on your project's folder, or recreate it on your machine somewhere else with proper permissions.
