### ISSUE TITLE
Push on('notification') not triggered, but on('registration') fired every time

### ISSUE THREAD

**Issue by andymurakami** [phonegap/phonegap-plugin-push#2241]
### Expected Behaviour
Call On('notification') event 

### Actual Behaviour
The event is not fired

### Reproduce Scenario (including but not limited to)
I´m try to send a notification with extra params to check what offer of my APP is send.

#### Steps to Reproduce 
www.loucosporofertas.com.br/vai.php -> try to send to my mobile.
When received, on tap, the App open but event on('notification') not fired, only on('registration') is fired every time.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android and IOS, many platforms have benn tested

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Samsung and Motorola

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 7.1.0
    cordova platform version android                     # e.g. 6.3.0

#### Plugin version

    cordova plugin version | 2.1.3

#### Sample Push Data Payload

```
$fields  = array(
        'data' => array(
          'title'     => 'Teste !',
            "badge" => 1,
            'sound'=>'default',
             'content-available'  => 1,
            'extra'=>array(
             "id_oferta" => '646',
            ),
            
          'body'    => 'Abre Oferta 646'
        ),
        'content-available'  => 1,
        'registration_ids' => $registrationIds,
                  'delayWhileIdle'=>true,
                  'timeToLive'=>3,
        'priority' => 'high',
    );
   
    
    $fields = json_encode ( $fields );

    $headers = array (
            'Authorization: key=' . MYKEY,
            'Content-Type: application/json'
    );

    $ch = curl_init ();
    curl_setopt ( $ch, CURLOPT_URL, $url );
    curl_setopt ( $ch, CURLOPT_POST, true );
    curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
    curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
    curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );
    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 ); // Be sure to use ipV4
    
    $result = curl_exec ( $ch );
    echo $result;
    curl_close ( $ch );
```

#### Sample Code that illustrates the problem

```
  $ionicPlatform.registerBackButtonAction(function (event) {
                if($state.current.name=="app.gallery"){
                  navigator.app.exitApp();
                }
                else {
                  navigator.app.backHistory();
                }
              }, 100);


            $ionicPlatform.ready(function () {

                if (window.cordova && window.cordova.plugins.Keyboard) {
                    cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
                }
                if (window.StatusBar) {
                    // org.apache.cordova.statusbar required
                    StatusBar.styleDefault();
                }

                var push = PushNotification.init(
                        {"android": {"senderID": "SENDER_ID",
                        "sound": "true",
                        "vibrate": "true",forceShow: "true" 
                    },
                                                 browser: {
                                                 pushServiceURL: 'http://push.api.phonegap.com/v1/push'
                                                 },
                            "ios": {"senderID": "SENDER_ID","gcmSandbox": "true","alert": "true", "badge": "true", "sound": "true"},
                            "windows": {}});




                push.on('registration', function (data) {
                                alert('registrou');
                                });


                push.on('notification', function (data) {
                    
                        alert('Notificação acionada, agora deve-se implementar a navegação no app de acordo com os dados: ' + JSON.stringify(data));
                    
                    
                    $state.go('app.detalhes({'+data.additionalData.id_oferta+'})',{redirect:true});
                    

                        });


                push.on('error', function (e) {

                    alert('registration error: ' + e.message);

                });
```

#### Logs taken while reproducing problem
I´m testing on device, I can´t to see the logs.

**Comment by macdonst** [comment]
@andymurakami I'll need to see some logs. On Android run `adb logcat | grep Push` when you send a push message to the device.

**Comment by andymurakami** [comment]
@macdonst  How to do this on Android ? Need ROOT access ?

**Comment by guilhermelirio** [comment]
It's the same with me!

Android 4.2.2
Phonegap-plugin-push 1.10.2
cordova -version 6.5.0

**Comment by AlbertoLuizRT** [comment]
Having a lot of problems with versions 1.10.7, 1.10.6, 1.10.5 and 1.8.0.
On iOS, not getting notifications with 1.8.0, and on Android can't use the additional info on notifications payload after restarting the app on various androids 7.0 and 6.0. I think we will need to find another push notification solution for ionic, suggestions?

**Comment by guilhermelirio** [comment]
Working now!!

My error: ";"

`var push = PushNotification.init(
                        {"android": {"senderID": "SENDER_ID",
                        "sound": "true",
                        "vibrate": "true",forceShow: "true" },
                            "ios": {"senderID": "SENDER_ID","gcmSandbox": "true","alert": "true", "badge": "true", "sound": "true"},
                            "windows": {}};
);`

I'm remove ; and works now!!

**Comment by andymurakami** [comment]
var push = PushNotification.init(
                        {"android": {"senderID": "SENDERID", icon: "icon"},

                            "ios": {"senderID": "SENDERID",
                                                 "gcmSandbox": "true",
                                                 "alert": "true", "badge":
"true", "sound": "true"},
                                                 "windows": {}});

And still not working

2018-03-26 16:25 GMT-03:00 guilhermelirio <notifications@github.com>:

**Comment by AlbertoLuizRT** [comment]
Since the OP didn't provide the logs, here are mine, in the hope @macdonst help us out: 

04-26 13:43:55.227  6034  6222 W PluginManager: THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 71ms. Plugin should use CordovaInterface.getThreadPool().

04-26 13:43:59.310  6058  6269 W fb4a.ServiceInfoParser: X.3kK: Service com.facebook.push.fbpushdata.FbPushDataHandlerService is missing meta key com.facebook.common.jobscheduler.compat.jobIds

04-26 13:45:24.576  6034  6222 V Push_Plugin: execute: action=init

04-26 13:45:24.577  6034  6114 V Push_Plugin: execute: data=[{"android":{"senderID":"611345096497","vibrate":true},"ios":{"alert":true,"badge":true,"sound":true}}]

04-26 13:45:24.581  6034  6114 V Push_Plugin: execute: jo={"senderID":"611345096497","vibrate":true}

04-26 13:45:24.582  6034  6114 V Push_Plugin: execute: senderID=611345096497

04-26 13:45:24.606  6034  6114 V Push_Plugin: onRegistered: {"registrationId":"deAk7GUm5MU:APA91bFcLmG526IXE2OfpGnllJd9TPQWYODX0GWoqt5YN4dUZ4iSa2K_GH5CbJtngRNMTMpa_cd-w5Qqj0YH48Rvku7SiBTm05ryqqe7FgfZTJwylgvmMO54fIICmsB_pKAVY41Ohd8K"}

04-26 13:45:24.606  6034  6114 D Push_Plugin: no icon option

04-26 13:45:24.607  6034  6114 D Push_Plugin: no iconColor option

04-26 13:48:57.340  8586  8617 D Push_GCMIntentService: onMessage - from: 611345096497

04-26 13:48:57.351  8586  8617 D Push_GCMIntentService: normalize extras

04-26 13:48:57.351  8586  8617 D Push_GCMIntentService: key = content-available

04-26 13:48:57.352  8586  8617 D Push_GCMIntentService: replace key content-available with content-available

04-26 13:48:57.352  8586  8617 D Push_GCMIntentService: key = google.sent_time

04-26 13:48:57.352  8586  8617 D Push_GCMIntentService: replace key google.sent_time with google.sent_time

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: key = google.ttl

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: replace key google.ttl with google.ttl

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: key = info

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: replace key info with info

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: key = title

04-26 13:48:57.353  8586  8617 D Push_GCMIntentService: replace key title with title

04-26 13:48:57.355  8586  8617 D Push_GCMIntentService: no locale found for key = title, error Value Protein of type java.lang.String cannot be converted to JSONObject

04-26 13:48:57.355  8586  8617 D Push_GCMIntentService: key = google.message_id

04-26 13:48:57.355  8586  8617 D Push_GCMIntentService: replace key google.message_id with google.message_id

04-26 13:48:57.355  8586  8617 D Push_GCMIntentService: key = message

04-26 13:48:57.355  8586  8617 D Push_GCMIntentService: replace key message with message

04-26 13:48:57.356  8586  8617 D Push_GCMIntentService: no locale found for key = message, error Value Avalie of type java.lang.String cannot be converted to JSONObject

04-26 13:48:57.357  8586  8617 D Push_GCMIntentService: background

04-26 13:48:57.358  8586  8617 D Push_GCMIntentService: message =[Avalie aqui seu pedido!]

04-26 13:48:57.358  8586  8617 D Push_GCMIntentService: title =[Protein Now]

04-26 13:48:57.358  8586  8617 D Push_GCMIntentService: contentAvailable =[1]

04-26 13:48:57.358  8586  8617 D Push_GCMIntentService: forceStart =[null]

04-26 13:48:57.358  8586  8617 D Push_GCMIntentService: create notification

04-26 13:48:57.375  8586  8617 E Push_GCMIntentService: Number format exception - Error parsing notId: null

04-26 13:48:57.393  8586  8617 D Push_GCMIntentService: stored icon=null

04-26 13:48:57.393  8586  8617 D Push_GCMIntentService: stored iconColor=null

04-26 13:48:57.393  8586  8617 D Push_GCMIntentService: stored sound=true

04-26 13:48:57.393  8586  8617 D Push_GCMIntentService: stored vibrate=true

04-26 13:48:57.393  8586  8617 D Push_GCMIntentService: no icon resource found - using application icon

04-26 13:48:57.397  8586  8617 D Push_GCMIntentService: create actions: with in-line

04-26 13:48:57.444  8586  8617 D Push_GCMIntentService: app is not running and content available true

04-26 13:48:57.444  8586  8617 D Push_GCMIntentService: send notification event

04-26 13:48:57.444  8586  8617 V Push_Plugin: sendExtras: caching extras to send at a later time.

04-26 13:49:06.907  1548 17427 I ActivityManager: START u0 {act=null typ=null flg=0x24000000 cmp=ComponentInfo{br.com.ideliveryapp.proteinnow/com.adobe.phonegap.push.PushHandlerActivity}} from uid 10316 on display 0

04-26 13:49:06.921  1548 17427 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x24000000 cmp=br.com.ideliveryapp.proteinnow/com.adobe.phonegap.push.PushHandlerActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }

04-26 13:49:06.938  1548 17427 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{85ac761d0 #2814 A=br.com.ideliveryapp.proteinnow U=0 StackId=1 sz=1} next=ActivityRecord{b744cdcd0 u0 br.com.ideliveryapp.proteinnow/com.adobe.phonegap.push.PushHandlerActivity t2814} mFocusedStack=ActivityStack{9cb03f3d0 stackId=1, 3 tasks}

04-26 13:49:06.955  1548  2490 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{2ae21b2d0 #2187 I=com.sec.android.app.launcher/com.android.launcher3.Launcher U=0 StackId=0 sz=1} next=ActivityRecord{b744cdcd0 u0 br.com.ideliveryapp.proteinnow/com.adobe.phonegap.push.PushHandlerActivity t2814} mFocusedStack=ActivityStack{9cb03f3d0 stackId=1, 3 tasks}

04-26 13:49:06.985  1548  2573 D GameManagerService: handleForegroundChange(). pkgName: br.com.ideliveryapp.proteinnow, clsName: com.adobe.phonegap.push.PushHandlerActivity,FgActivityName:br.com.ideliveryapp.proteinnow/com.adobe.phonegap.push.PushHandlerActivity

04-26 13:49:07.004  8586  8586 D Push_HandlerActivity: not id = 0

04-26 13:49:07.006  8586  8586 V Push_HandlerActivity: onCreate

04-26 13:49:07.006  8586  8586 D Push_HandlerActivity: callback = null

04-26 13:49:07.006  8586  8586 D Push_HandlerActivity: dismissed = false

04-26 13:49:07.009  8586  8586 V Push_Plugin: sendExtras: caching extras to send at a later 
time.

04-26 13:49:07.009  8586  8586 D Push_HandlerActivity: bringToForeground = true

04-26 13:49:07.017  8586  8586 D Push_HandlerActivity: isPushPluginActive = false

04-26 13:49:07.017  8586  8586 D Push_HandlerActivity: forceMainActivityReload

04-26 13:49:26.708  8586  8773 W PluginManager: THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 17ms. Plugin should use CordovaInterface.getThreadPool().

Sorry for improper formatting.
