### ISSUE TITLE
Dependency on cordova-android version 7.1.0

### ISSUE THREAD

**Issue by cbjerg** [phonegap/phonegap-plugin-push#2262]
### Expected Behaviour
Phonegap Build would suceed 

### Actual Behaviour
Phonegap Build fails
Installing "phonegap-plugin-push" at "2.2.2" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.1.0

It seems the plugin is now dependant on cordova-android 7.1.0 which is not even available to Phonegap Build users. Is it not meant to be dependent on cordova-phonegap version 7.1.0 (with cordova-android version 6.3.0)

**Comment by jcesarmobile** [comment]
The plugin requires cordova-android 7.1.0 because a bug on the gradle dependency.
You will have to use 2.2.1 version of the plugin until PGB allows to use cordova-android 7.1.0.

**Comment by cbjerg** [comment]
2.2.1 also has dependency on cordova-android 7.1.0, and wont build for iOS without voip

**Comment by macdonst** [comment]
@cbjerg because of an issue with Google support libraries and gradle I had to make a change in cordova-android which landed in 7.1.0. So in order for you to install 2.2.x of the plugin you'll need cordova-android 7.1.0 or later. 

If you are stuck with cordova-android 6.3.0 you'll need to use push plugin 2.1.x until PGB updates to the newest version of Android.

**Comment by jcesarmobile** [comment]
Ah, yeah, didn't notice 2.2.1 also had that dependency. As Simon said, you'll have to use 2.1.3 until PGB supports cordova-android 7.1.0.
For this to happen, first a new Cordova CLI is needed as PGB doesn't allow to specify the platform versions independently and there is no Cordova CLI with cordova-android 7.1.0 pinned yet.
