### ISSUE TITLE
Notifications not enabled by default in iOS Xcode Project with version 1.x + cordova 6.5.0 + cordova-ios 4.5.4

### ISSUE THREAD

**Issue by vdesaintpern** [phonegap/phonegap-plugin-push#2264]
### Expected Behaviour
Notifications enabled in XCode project by default

### Actual Behaviour
Notifications NOT enabled in XCode project by default

### Reproduce Scenario (including but not limited to)

Add platform, cordova build, open xcode project => notifications not enabled and not working when deployed on a device.

#### Steps to Reproduce 

See above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Build a simple with version 1.10.5 of the plugin and XCode 9

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

iOS only

#### Cordova CLI version and cordova platform version

    cordova --version                  6.5.0                  # e.g. 6.0.0
    cordova platform version ios        4.5.4             # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.10.5 # e.g. 1.5.3

#### Sample Push Data Payload
not relevant

#### Sample Code that illustrates the problem
Standard sample code behave this way.

#### Logs taken while reproducing problem
No logs. Notifications are disabled in the project and not working on iOS on a device.
![screen shot 2018-03-13 at 18 02 13](https://user-images.githubusercontent.com/5381717/37357424-b59a3aea-26e8-11e8-8093-c1b399bdddaf.png)

**Comment by twl-kmd** [comment]
We are seeing the same issue, tried with phonegap-push-plugin 2.1.3 and 2.2.2

**Comment by vdesaintpern** [comment]
twk-kmd, if you're looking for a quick solution, you can build a mini cordova plugin, basically a xml file in a repo. In the XML file, copy your entitlements files using what I put in my pull request . You'll need to find the right path for your entitlements files for the copy to work OR add your entitlement files at the root of your "mini"-plugin. Far from ideal but life has to go on despite bugs in the push plugin right ? :)

**Comment by jcesarmobile** [comment]
This is because Cordova uses entitlement.plist files instead of .entitlements file.
Xcode is not able to recognize those files and doesn't show the push notifications as enabled. But they should work anyway when running the app from the CLI if you use a provisioning profile with push notifications enabled.
There is an issue open for using .entitlement file, but it's still open.

**Comment by vdesaintpern** [comment]
Wow, issue closed, already... I'm a bit surprised... It's fairly easy to reproduce and a right pain for users. I guess I haven't done enough to explain the problem. So first _sorry about that_ and let me explain a bit more.

You already know that push notification capability was NOT required to be ON for push notifications to work in XCode 7, probably 8. Same here and for loads of people.

**Looks like It's not the case anymore with Xcode 9**. 

If you go ahead with default settings and files generated by the plugin, notification capability is OFF and registerDevice crashes on the device, no push_id, no push. If during the build you rename the generated .plist entitlement files to the new .entitlements name, capability is still off and notifications do not work.

But if you rename them to the new name AND add them to the generated pbx project file, the capability automagically switchs ON in XCode AND push notifications work on the device.

I even tried a command line version of the fix in your code : I added a <source-file> tag pointing at my .entitlements in your push plugin.xml => Capability is switched as ON expected PLUS notifications work on the device!

For time being, I have planned to create a small private plugin to rename the files and add them to the project. If you think this is not required, please let me know how you'd fix the problem.  

So, I'd like this issue reopened and hope the team have some time to implement a fix which would : 

1) generate .entitlements files instead of .plist files 
2) add the .entitlements files to the project like the other source files

Thanks,

**Comment by jcesarmobile** [comment]
As I said, that has to be done at cordova-ios level and there is an issue open for it.

**Comment by vdesaintpern** [comment]
If anyone needs a fix, here's my plugin : https://github.com/vdesaintpern/phonegap-plugin-push-fix

**Comment by jcesarmobile** [comment]
FYI, I've just created a new project with Cordova 8, cordova-ios 4.5.4, phonegap-plugin-push 2.2.2 and Xcode 9. I've used the identifier of an App Id I've configured to use push (from developer.apple.com website)
I've run from the command line with `cordova run ios --device` (after adding the build.json file so it uses automatic signing). 
Push notifications work just fine.
If I open Xcode and go to capabilities, the push notifications are off.
If I run from Xcode, it still works despite being off.

Looking at your plugin, what you do is to add new Entitlements-Debug.plist and Entitlements-Release.plist files that overwrite the Cordova ones.

Cordova uses a `build.xcconfig` file to sign the apps, and that file has this line `CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist`
That will read those files on build time, so they don't need to be included into the Xcode project.

Nevertheless, it's true that if you add those files to the project, the push capabilities become on, so might be a good idea to add those files to end with the confusion. But this should be done at cordova-ios level, not on the push plugin or with a 3rd party plugin, because as you said, it will replace existing files and make other plugins not work.
