### ISSUE TITLE
detect click on notification

### ISSUE THREAD

**Issue by blue4603** [phonegap/phonegap-plugin-push#2307]
Hi,
is there a way to know whether the notification received was clicked by the user or not?
Here is my scenario and I will be talking about android for now.
I have three push notification in the notification drawer and the app is in the background state
The user clicks the first one and the app is opened and the  on notification event is fired and the app execute some code (shows a pop up)
When the user pulls the drawer and clicks the second one, the app is now in the foreground and the on notification is fired and the app execute some code. (shows a pop up)
The problem with this is that when the user is using the app and the app receives a notification the on notification is fired and the code is executed.
I want to execute the code which shows a popup only when the user clicks the notification and not whenever the app receives a notification
Is that possible?

Thank you

**Comment by macdonst** [comment]
@blue4603 please follow the issue template in the future. Also, what you are looking for is the `data.additionalData.foreground` property, which is true when the app is in the foreground and false otherwise.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback
