### ISSUE TITLE
Failed to install 'phonegap-plugin-push':Error: pod: fatal: Not a git repository 

### ISSUE THREAD

**Issue by fgagneten** [phonegap/phonegap-plugin-push#2396]
On my ionic 1 project, I'm trying to fetch phonegap-plugin-push plugin version 1.11.1
My config.xml has the following code:

`<plugin name="phonegap-plugin-push" spec="1.11.1">
		<variable name="SENDER_ID" value="207258139553"/>
	</plugin>`

But I when I do
    Cordova platform add ios 

I get the following error:

`Failed to install 'phonegap-plugin-push':Error: pod: Command failed with exit code 1 Error output:
fatal: Not a git repository (or any of the parent directories): .git
  fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
    at ChildProcess.whenDone (/Users/folder/Proyectos/project/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

So I can't release my app because it produces this error:

>     'GoogleCloudMessaging.h' file not found

I think the error is related with cocoapods. 

If I do

    cd platforms/ios 

and then

    pod setup

Ionic version: 2.2.2
Cordova version 6.5.0

Thanks

**Comment by marcelaraujo** [comment]
@fgagneten I think this issue is related to Google deprecated GCM libraries and servers.

https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update_server_endpoints

I'm using the version 1.10.6 and I got this error on registration

![image](https://user-images.githubusercontent.com/421794/40920225-45efa488-67e2-11e8-8c0e-e2b206556eb0.png)

`Didn't find class "com.google.android.gms.common.util.zzv"`

**Comment by fgagneten** [comment]
I don't know why but it automatically fixed. May be was a temporary error
