### ISSUE TITLE
Need a fix for "+" input.

### ISSUE THREAD

**Issue by nathanmercieca0011** [phonegap/phonegap-plugin-push#2511]
Using: phonegap.
CLI: 8.
Version of plugin: 2.1.2.

```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
```

My plugins are:
```
    <plugin name="cordova-plugin-admob-simple" spec="3.3.4" />
    <plugin name="cordova-plugin-badge" spec="0.8.7" />
    <plugin name="cordova-plugin-camera" spec="4.0.2" />
    <plugin name="cordova-plugin-file-transfer" spec="1.7.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="2.0.2" />
    <plugin name="cordova-plugin-screen-orientation" spec="3.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="phonegap-plugin-barcodescanner" spec="8.0.0" />
    <plugin name="cordova-plugin-geolocation" spec="4.0.1" />
    <plugin name="cordova-plugin-globalization" spec="1.11.0" />
    <plugin name="cordova-plugin-file" />
    <plugin name="cordova-plugin-gallery-refresh" spec="1.0.55" />
    <plugin name="cordova-plugin-contacts" spec="3.0.1" />
    <plugin name="cordova-plugin-localization-strings" spec="2.0.0" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2"/>
    <plugin name="phonegap-plugin-push" spec="2.1.3 " />
```
I hope you don't tell me I need to uninstall admob, really, or any other plugin, most of these are essential.

Also tried:
```
<preference name="PlayServicesVersion" value="11.0.1"/>
```
...and didnt work.

You need a trouble shooting page. Searching the internet for hours and hours on end when you already have all the answers is much much more annoying for us than it is for you to see our annoying comments. Trust me. We need to rely on your plug-ins, and you have a team of around 100. I'm wasting a whole day doing one thing, losing a whole day's pay for no reason. Can't you just make a page filled with all the most common errors? You know what they all are already.

**Comment by jcesarmobile** [comment]
You are not using lates plugin, so...

About the trouble shooting page, PRs are welcome

**Comment by nathanmercieca0011** [comment]
@jcesarmobile 
You told me to use 2.1.3 in another issue, only an hour ago. But now you've closed the issue. Can you please reply when you see my comment. I don't know if when they're closed you still get notified.

**Comment by jcesarmobile** [comment]
No, I told you the last version supported by Phonegap Build is 2.1.3. If you want to use Phonegap Build then you have to use that version. But the bug was fixed later, so nothing we can do to help you with that.

As I told you in the other issue, you'll have to build locally or use other plugin which doesn't conflict.

**Comment by macdonst** [comment]
@nathanmercieca0011 _a team of around 100_ hahahahahahaha! I'm sorry my dude but you are incredibly mis-informed. This plugin is maintained by me and less than a handful of other folks as a labour of love. We don't get paid for this.

You step in and accuse us of wasting our time and you haven't done us the basic courtesy of filling out the issue template which really, really helps us give you a better answer. Also, you didn't even search past issues to see if this had been reported before, it has, [19 times](https://github.com/phonegap/phonegap-plugin-push/search?q=Failed+to+apply+plugin+%5Bclass+%27com.google.gms.googleservices.GoogleServicesPlugin%27%5D&type=Issues). 

We've even added a bit in our docs about [co-existing with other plugins](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#co-existing-with-plugins-that-use-firebase) that should help guide you to resolving your problem.

And I can tell you to uninstall `cordova-plugin-admob-simple` as it hasn't been updated in over a year and hasn't kept up with changes in technology. Instead of blaming this active plugin why don't you send a PR to fix the problem in that plugin.

**Comment by jcesarmobile** [comment]
wow, he deleted his account, it's the first time I see a github ghost

**Comment by macdonst** [comment]
@jcesarmobile wow, I'm kinda surprised. I didn't think we were that hard on him.

**Comment by fredgalvao** [comment]
Gee, I got to the party so late that the party had already been deleted.

**Comment by jcesarmobile** [comment]
He first added it as a comment and then created the issue with the same message, so you can see it here https://github.com/phonegap/phonegap-plugin-push/issues/2510
