### ISSUE TITLE
Phonegap Build error because plugin requires gradle.

### ISSUE THREAD

**Issue by kentmw** [phonegap/phonegap-plugin-push#257]
Using phonegap build, I am not able to build my application because of this error:

```
Error - One of your plugins required the gradle android build tool to build - You can fix this here
```

After doing some investigation, it seems that I need to get my android builds to be done through gradle. PGB says that they support it now: http://community.phonegap.com/nitobi/topics/gradle-support-enabled-for-android-builds as long as you have the right configuration in you config.xml

These are the preferences I'm using:
```
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-build-tool" value="gradle" />
```
which I think is enough to require gradle. I know this is mostly a PGB issue - it's not building with gradle like it says it should, but this plugin is the surface-level reason for this error and I'm wondering if any other users of this plugin have gotten it to work with PGB.

Side note that may be important is that I'm using 3.7.0 version on phonegap. Not sure if that is a requirement for gradle builds in PGB.
```
<preference name="phonegap-version" value="3.7.0" />
```

**Comment by fredgalvao** [comment]
First, the official post on PGB specifies that gradle builds only work on `PG.version >= 4.0.0`, [check here](http://phonegap.com/blog/2015/09/28/android-using-gradle/). As you said your project is using `PG.version === 3.7.0`, that's enough for it to **not** be officialy supported.

However, even if your PG.version matched the requirements, it seems like gradle builds on PGB went downhill after being enabled, as they found out stability wasn't on par. I saw you posted a comment on that thread, so you're actually following the situation (that is, considering [this post](http://community.phonegap.com/nitobi/topics/gradle-support-enabled-for-android-builds#reply_16248450) actually belongs to you).

I'm closing this since this is not really an issue with the plugin itself, but rather with PGB's support for gradle builds. If anything, you can specify version `1.2.3` of phonegap-plugin-push, as that was the last version of the plugin to **not require** gradle builds:

```xml
<gap:plugin name="phonegap-plugin-push" source="npm" version="1.2.3" />
```

**Comment by kentmw** [comment]
@fredgalvao, thank you for the info!
