### ISSUE TITLE
How many times I have to keep the data.registrationId.?

### ISSUE THREAD

**Issue by YeltsinReyes** [phonegap/phonegap-plugin-push#270]
I have this code but whenever the user opens the application will send the data.registrationId to my website  or just once.?

push.on('registration', function(data){
$.post('http://myweb.com/registration.php', { id: data.registrationId });
});

**Comment by macdonst** [comment]
@YeltsinReyes the way you have it coded it will send it every time. What would be better is if you store the registration ID locally, compare it on each start up and only send when it is different. The different push providers will periodically refresh their tokens.

```
push.on('registration', function(data){
    if (localStorage.getItem('registrationId') !== data.registrationId) {
         localStorate.setItem('registrationId', data.registrationId);
         $.post('http://myweb.com/registration.php', { id: data.registrationId });
    }
});
```

**Comment by YeltsinReyes** [comment]
Ok thanks and long last saved localStorate?

**Comment by macdonst** [comment]
@YeltsinReyes until you delete the app.

**Comment by alexislg2** [comment]
Is the plugin doing a registration to GCM each time the app starts? I couldn't tell from reading the JAVA code.

Because according to that post https://github.com/ToothlessGear/node-gcm/issues/176 , the plugin should not register at every start of the app

`@alexislg2 are you registering every time the app is opened? That's very bad and could be the reason you are getting this error. You should not be registering unless the app is fresh-installed or updated, or the IDListenerService invokes the registration service for some other reason.`
