### ISSUE TITLE
Get away from cocoa pods?

### ISSUE THREAD

**Issue by burtontanner** [phonegap/phonegap-plugin-push#2762]
### Expected Behaviour
"cordova plugin add phonegap-plugin-push" will install the plugin without any extra work.

### Actual Behaviour
after installing "cordova plugin add phonegap-plugin-push" you need to modify your xcode project with a cocoa pods command. 

I feel like this goes against the cordova model. To really remove the plugin, you have to also remove the platform. Also, if I come into a cordova project for the first time, I expect "cordova prepare" to install all the plugins that I need. 

As an example of this in action, I have forked your repo and cordova-push-notifications to make a mix of the two. This uses your version of FCM and cordova-push-notifications version of APN. https://github.com/burtontanner/cordova-push-notifications?organization=burtontanner&organization=burtontanner

**Comment by macdonst** [comment]
@burtontanner that's great work. Although the reason this repo needs cocoapods is so it can support FCM on both Android and iOS. If folks don't need that support then they can use another plugin like yours. As to why some folks need to modify their project by running the `pods` command manually I'm not sure what to tell you as Cordova should do that for you so that's more of a bug with the framework and we just provide a documented work around.
