### ISSUE TITLE
Where can i update the Sender Id or Project Name in Windows

### ISSUE THREAD

**Issue by sulthanallaudeen** [phonegap/phonegap-plugin-push#327]
I created a new app and installed the wp8 platform, and i wanted to use the examples provided by example. 

Like the android's SenderID, Where shall i give my app Sender ID to implement WPNS ? 

I have purchased Developer Account and i created a  sample app in my Dashboard. 

How can i do this. Please reply soon, i wanted to make the app working and i choosed this plugin because i got good support while implement gcm for android.

**Comment by macdonst** [comment]
@sulthanallaudeen sorry, this plugin does not support windows 8. Rather it supports Windows Universal where there is no need for a Sender ID/Project Name. I've assigned the issue to @rakatyal in case I've got some of the details incorrect.

**Comment by sulthanallaudeen** [comment]
@macdonst Thanks, i will follow up with @rakatyal

**Comment by sulthanallaudeen** [comment]
@rakatyal Is it possible to receive push notification for wp8 using Windows Universal ? Where can i know more about it ?

**Comment by bau720123** [comment]
hi @sulthanallaudeen 
if you really want a wp8 version
there is a deprecated one
https://build.phonegap.com/plugins/3960
https://github.com/phonegap-build/PushPlugin/blob/a172e19/README.md

I tried a long time ago，it's work
but said once again，it is deprecated

**Comment by rakatyal** [comment]
@sulthanallaudeen: Apologies for the late reply. I completely missed this issue. WP8 supports push notifications from MPNS only. Windows Universal platform(WP8.1+ and Windows 8+) can support both WNS and MPNS but WNS is preferred since it offers better functionalities. 

WP8 is deprecated and this plugin doesn't support it. Hence this uses WNS for the notification service. 

Links for details:
https://msdn.microsoft.com/en-us/library/windows/apps/hh913756.aspx
https://msdn.microsoft.com/en-us/library/windows/apps/ff402558(v=vs.105).aspx

**Comment by sulthanallaudeen** [comment]
@rakatyal  Okay, Thanks for the reply

**Comment by sulthanallaudeen** [comment]
@bau720123 Gotcha :)
