### ISSUE TITLE
Unregister does not seem to work on iOS

### ISSUE THREAD

**Issue by boboldehampsink** [phonegap/phonegap-plugin-push#33]
When using unregister, all switches are still on in the notification settings of iOS

**Comment by macdonst** [comment]
@boboldehampsink I researched this and it is actually expected behaviour on iOS. When you call the 'unregister' function the app sends a message to APNS so that it will no longer accept notifications. However the items in the Settings app are controlled by the user and enabled the first time the user is asked to enable push for the app. According to my reading if you unregister, delete the app, reinstall the app and wait two days it will go back to disabled.

Regardless, it is nothing to worry about that the app still shows up as Allows Notifications.
