### ISSUE TITLE
Init Error: Missing Instance ID Service

### ISSUE THREAD

**Issue by mariohmol** [phonegap/phonegap-plugin-push#334]
After init, using the same as the example (just changing senderID, it get in push.on('error',  showing this error:

* MISSING_INSTANCEID_SERVICE

Using Mac, with android emulator level 19 , with all pkgs installed in sdk and almost all extras (all required in readme)

Any ideas?

**Comment by fredgalvao** [comment]
When creating your emulator image, instead of specifying
`target="Android 4.4.2"`,
select
`target="Google APIs (Google Inc.) - API Level 19"`
so that it will have all **Google Play Services** available, which are needed to run this plugin.

I'll close this, but please re-open it if, after recreating your emulator, the issue still persists.

**Comment by mariohmol** [comment]
yeah thats true.. i was already stucked in a new bug  "Empty registration ID received from GCM"..

**Comment by rknell** [comment]
+1 Issue was using a simulator

**Comment by sinha40** [comment]
how i resolve this error "MISSING_INSTANCE_ID".
