### ISSUE TITLE
blank push notification icon on android when sdk > 20

### ISSUE THREAD

**Issue by michaelknoch** [phonegap/phonegap-plugin-push#345]
I'm trying to integrate push notifications into my ionic app with phonegap-plugin-push.

When I set my android:targetSdkVersion greater than 20, I'll receive a blank push notification icon. With SdkVersion 20 it's working properly.

Is there a fix for newer sdk versions or can i unproblematically use version 20? (performance, functionality)

**Comment by bau720123** [comment]
+1

**Comment by bau720123** [comment]
hi @michaelknoch 
did you mean that
SONY Android 5.1.1
![screenshot_2015-11-17-20-16-29](https://cloud.githubusercontent.com/assets/5110085/11211222/e2da3044-8d68-11e5-8a58-908107b52844.png)
![screenshot_2015-11-17-20-17-02](https://cloud.githubusercontent.com/assets/5110085/11211225/e8bf814e-8d68-11e5-9305-2fc219ea484f.png)

**Comment by macdonst** [comment]
@michaelknoch if you mean the blank white icon as @bau720123 pointed out it is all documented at:

https://github.com/phonegap/phonegap-plugin-push#images

You'll need to follow the Android guidelines when creating your icon.

**Comment by bau720123** [comment]
hi @macdonst 
just a question
in Android 4.4.2，the icon no mater desktop icon or system bar icon，all normal to show

according to this ("System icons" chapter，right ?)
https://www.google.com/design/spec/style/icons.html#
is you mean if "not follow" it's clue ，the icon will become white that only in Android 5.0 and greater，just like my [Screenshot 1] ?

**Comment by macdonst** [comment]
@bau720123 yes, if you build with Android 5 or later then the icon will show up completely white. So the icon you use should not rely on color but rather transparency to be distinct.

**Comment by bau720123** [comment]
hi @macdonst 
sorry for bother again
but in my PGB cli 5.2.0 (build.phonegap.com) + "android-minSdkVersion" => 15
it is...
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)

you said，if you build with Android 5 or later then the icon will show up completely white
I am a little confuse about "build with Android 5" true meaning，because in PGB，it is 4.1.1 for now

anyway...
according to my [Screenshot 1]，there are four icons in the Left corner
the first one and last one are all system app，them are all white (not happen in Android 4.4.2)
the third one is my app that made by PGB，still have white situation
but the second one "AirDroid" app that I download from GooglePlay still can have a "normal icon" (no white icon) in the system status bar

so my problem is，is there any way can know how "AirDroid" did this ?

**Comment by macdonst** [comment]
@bau720123 yes but if you look your target SDK will be greater than 20. You can see how the SDK levels map to API version numbers here: https://source.android.com/source/build-numbers.html

**Comment by bau720123** [comment]
thanks @macdonst 
I will try to figure out the target SDK

last question..
according to my [Screenshot 2]，you can see I have a background color "blue"，this is because I use "iconColor": "blue"
well...
but you can see the "AirDroid" seem have a "transparent" color
or maybe it just a coincidence (the small icon maybe "white" too) ?

**Comment by macdonst** [comment]
@bau720123 that version of AirDroid must be compiled with a lower target SDK version that still allows color in small icons in notifications.
