### ISSUE TITLE
[Question] about the action's icon color

### ISSUE THREAD

**Issue by bau720123** [phonegap/phonegap-plugin-push#348]
according to this
https://github.com/phonegap/phonegap-plugin-push/issues/345
thanks @macdonst let me know the "white" situation

well，it is my screenshot，left side is Android 5.1.1，right side is Android 4.4.2
![s__38993922](https://cloud.githubusercontent.com/assets/5110085/11216398/ea09bf0c-8d85-11e5-8547-ecde3014cbb1.jpg)
all code all the same
the icon in 5.1.1 will become gray but Android 4.4.2 is normal
is it a Android 5 "feature" just like the "white" situation ? (what a ugly feature XD...)

**Comment by fredgalvao** [comment]
### Android app built with target-sdk > 20, running on a device with android 5.0 or higher

Just as is the case on https://github.com/phonegap/phonegap-plugin-push/issues/345, as explained by @macdonst , every system wide icon will be manipulated by android so that it is composed of transparent and a single main color pixels. On stock android, these colors are white for the notification icons, and gray for action icons. That applies to any and every app, unless they are creating custom notification objects from the start.

### Android app built with target-sdk > 20, running on a device with android 4.4 or lower

The new apis are non-existant, so the icons will be shown AS IS.

### Android app built with target-sdk = 20, running on a device with android 5.0 or higher

Although the new apis are present, the app is demanding to be treated as if the device was on android 4.4 or lower, so **compatibility mode will apply, with the old (4.4) api taking place**.

### Android app built with target-sdk = 20, running on a device with android 4.4 or lower

The app is at home, there is no compatibility mode in place, so the icons will be shown AS IS.

**Comment by Telemakhos** [comment]
@fredgalvao Great explanation! I was looking for this... thanks

**Comment by bau720123** [comment]
awesome explanation @fredgalvao 
maybe you can update the readme
thanks your help and close it
