### ISSUE TITLE
Visit specific page after click on push notification.

### ISSUE THREAD

**Issue by KirillSuhodolov** [phonegap/phonegap-plugin-push#350]
Is it ability to open specific url in application after clicking on new push notification? 
iOS

**Comment by fredgalvao** [comment]
That is not in the hands of this plugin. What you need to do is read the `notification` event at the startup of your app on the main page (index.html, most probably), and then redirect it to whatever page you want (via javascript routing or via `window.open`, depending on how your app is structured).

**Comment by KirillSuhodolov** [comment]
This will not work for multiple push notifications and when app minimized.

**Comment by macdonst** [comment]
@KirillSuhodolov sure it will. Clarifying question, is it always the same url or are you sending the url you want to open in your push payload?

**Comment by KirillSuhodolov** [comment]
@macdonst there are many different urls and I send them in push payload.

**Comment by rwillett** [comment]
@KirillSuhodolov 

We send multiple notifications down to our iOS app. Each notification has a unique piece of information in it. When the user clicks a specific notification from the shade, our javaScript looks at the JSON data passed in and opens up a specific 'window' (I know its not really a window). 

This works fine in the background. We handle things differently in the foreground as we don't want the user app to jump around.

I'm not clear if you are saying there are lots of different url's in the same notification or across multiple notifications. However Simon is correct and I can confirm that technique works as we use it.

Rob

**Comment by yossale** [comment]
@rwillett what do you do until the 'notification' event is triggered? waiting for it causes us a race-condition :/

**Comment by rwillett** [comment]
The notification event is triggered. You should not be waiting for it. You run your code and a notification event may occur at some point. 

I'm unclear how you can wait for it. I'm assuming you are not polling for it. 

Rob

**Comment by yossale** [comment]
That's my point - If you want to jump to a certain page due to a click on a push notification, then this scenario is possible:
1. the user clicked the PushNotification
2. the app starts
3. the app loads the homescreen
4. the notification event is triggered - the app jumps to another screen

I'm wondering how to get over it

**Comment by rwillett** [comment]
@yossale 

I'm unclear as to the problem. I'm doing this from memory now as now near my main machine.

1. Your use-case is that the app is not running. 
2. A notification comes in.
3. You click on the notification.
4. The app starts up.
5. The plugin function onNotification (or whatever it is called) should be fired as the app starts up.
6. Some data attached to the Notification event shows the app which page to go to.
7. Your app goes to the right page based on $state.go (or whatever). I know we don't really have pages.

Thats how we wrote the code for using a separate commercial plugin, we're transitioning to a new Notification plugin which may or may not be this one, so we haven't figured out all the details here. 

So whats the issue?  I am still unclear.

Rob

**Comment by yossale** [comment]
@rwillett 
There are 2 cases: a user clicked the app to open it, or clicked a push notification. 
In the 1st case, you want to show her you "Hello Page"
In the 2nd case, you want to show her the page concerning the push she clicked.

We don't know until the notification-event which case we're at...

**Comment by rwillett** [comment]
@yossale 

Ok I *think* I understand. 

We are still working out how to use this specific plugin after coming from a previous commercial plugin and have not implemented the logic you are talking about with this specific plugin. However with the previous plugin we had a race condition that occurred in a similar situation.

We handled that by having each notification handler NOT actually handle a notification. Each notification handler would simply push the event to be handled onto a very small queue (an array really), each notification handler would then set a simple timeout which would call a function to work out the order of events that were pushed onto the queue.

This simple timeout would happen at the end of ALL the events in the Javascript run cycle, the queue manager would walk down the list and would work out the priority of the events to be run, it would then execute the events and if necessary would remove other events from the queue as they were not needed as other events would take precedence.  There was an explicit notion of precedence in the events and an explicit idea that one event could delete another event if it needed to (or could push another event onto the queue to be executed). 

This was quite simple to implement (took us an hour or so) and meant that no matter how many events would come in at startup (or at resume from background) we had a mechanism for managing the order and the priority of notification events. Its a simple queue which we would walk down one event at a time as we knew there would never be more than 2-3 events on it (we never saw more than 2).

Since each notification handler sets the same timeout to run exactly the same function, it doesn't matter which gets priority as they have the same effect on the queue. The second timeout that ran would simply find the queue to be empty as the first timeout had done all the work. 

Does that help?

Rob

**Comment by jigneshchudasama05** [comment]
Hello,

I have implemented the app using laravel and ember.js and I have implemented push notification successfully, but somehow I am not able to figure out how to link / redirect push notification to specified route?

Thanks!

**Comment by rwillett** [comment]
Sorry, you need to explain yourself more clearly.

If all you are doing is trying to trigger a specific action based on selecting a notification, e.g. go to a page, then simply provide a payload to your notification with more information in about what to do, in the notification handler function that is called, work out where to go based on the payload and do something like $state.go. Your method of jumping to wherever is dependent on your app.

Rob

**Comment by jigneshchudasama05** [comment]
Thanks for your reply.

One more doubt - How to use $state.go with route, e.g. on click of push notification i want app to load specified route.

Thanks!

**Comment by rwillett** [comment]
Since I have no idea how your app is set up, or the details of your framework, you need to investigate that. Google is your friend.

Rob

**Comment by jigneshchudasama05** [comment]
Thanks for your help !!

**Comment by WilsonFpz** [comment]
As @yossale said
There are 2 cases: a user clicked the app to open it, or clicked a push notification. 
In the 1st case, you want to show her you "Hello Page"
In the 2nd case, you want to show her the page concerning the push she clicked.
Does anyone know how the event handler tell which case was triggered by? Thanks 
(Not related to foreground)

**Comment by rwillett** [comment]
@WilsonFpz 

You know the user has clicked a notification as the notification handler is called. Otherwise the app starts as normal.

Rob

**Comment by WilsonFpz** [comment]
@rwillett 
thanks. But when the app is in the background, it would also trigger the notification handler, since I need to do some calculation (like update badge).If notification handler can not tell which case, the user would feel strange when click (resume) the app icon and found that the last view page has changed.

**Comment by rwillett** [comment]
If your app is in the background AND has not been suspended (don't forget IOS can move your app from background to suspended after some time, 15 mins seems normal), then when you get a notification your handler is still called in the background. Since you know you are in the background and can process it accordingly, e.g. don't change the page. If you are in the foreground then simply change the page as before.

Have I missed something? The key is that you know you are in the background and so handle the notification differently.

Rob

**Comment by WilsonFpz** [comment]
@rwillett 
Thanks. Our requirement is as follow
case1. when user is in Home and click the app icon, it would resume our app and show the page (last time remain view)
case2. when user is in other app, click on the notification, it would also resume our app and jump to a specified page (depend on the payload)
However , both these two cases on in the background...So I can not approach these two case by only one notification handler... Thanks again.

**Comment by rwillett** [comment]
Thats the behaviour we have for our app and what we would expect.

We only have one notification handler as well. If the user clicks our app icon then the notification handler is NOT called and the app resumes back to where it was before. 

If the user selects a notification then the notification handler is called. 

Why are you different?

Rob

**Comment by WilsonFpz** [comment]
@rwillett 
Thanks. Its not like your app`s behavior. The notification handler should be called even if the user clicks on the app icon!
Take chat app for example, if new message is coming,  it should trigger the notification handler (no matter on click app icon or on click notification) and the handler would add the message to the chat lines lists. The difference is the page should jump to  chat detail when the user click on the notification.

**Comment by rwillett** [comment]
Ok, thats not standard app behaviour (AFAIK). 

Isn't there a flag that shows if the app was running when the notification was clicked? Otherwise I'm not sure what else to suggest. 

Rob

**Comment by NishatJahan** [comment]
Hi i have single page JQM model for cordova iOS app. On click of the notification, inside notifcation handler, i am trying to change page using $.mobile.changePage("#pageid");
This works fine in android, but in ios, it always shows the page from which the app was closed and changePage doesnt work.

**Comment by rwillett** [comment]
This appears to be nothing to do with this thread. This thread was also closed some months ago. 

I would suggest you raise a new issue on a new thread and reference this one. 

Rob

**Comment by jcesarmobile** [comment]
Well, it could be some timing issue on the iOS implementation of the plugin, or a bug in JQM.

Does $.mobile.changePage("#pageid"); works fine if you use it elsewhere?

But agree with @rwillett, if you are sure that the problem is the plugins fault you should create a new issue.

**Comment by pradosh05** [comment]
I am using phonegap-plugin-push plugin for FCM push notification,

Here I am able to get notification when app is running in background or app is in active status notification is working fine in this state.

But when app is in background state and any notificaiton came in that condition if any user click on the notificaiotn he must be redirect on any spacific page, for this I try so many way but its not working . 

I am using following code to initialize notification

var push = PushNotification.init({
    android: {
        senderID: '436009364694',
        alert: true,
        badge: true,
        icon: 'icon',
	    sound: true,
	    vibrate: true
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true",
        vibrate: true,
	    clearBadge: true
    },
    windows: {}
});


And I am using following code to trigger the notification

push.on('notification', function(data) {
});

above code is only working when app is in running state but its not working when app is in background, 

Any one know how to trigger click event if app in background state

**Comment by rwillett** [comment]
This thread was closed 18 months ago. I'd suggest you open a new thread and start again as things have moved on.
