### ISSUE TITLE
Two in app notifications being fired. (ios)

### ISSUE THREAD

**Issue by wallstudios** [phonegap/phonegap-plugin-push#377]
I suspect this maybe an implementation issue but thought I would ask.
All pushes etc are working correctly except I have an odd behavior.

I have the app open but in the background and I receive a push notification.
If I reopen the app via the notification I end up getting two in app notifications being fired.

If I click on the app icon to reopen only one event is fired.

is there a way of detecting if the app was open when the notification was received and if so stop the second notification being fired?

Haven't tested on Android yet.

**Comment by macdonst** [comment]
@wallstudios that seems like expected behaviour. You have put content-available in your push so it will fire the background notification event handler. It should like you have put an alert in the push as well so it is showing up in the notification shade. If you click on that notification then another event will be fired. 

You can not send an alert as per (https://github.com/phonegap/phonegap-plugin-push#background-notifications-1) to make it a silent notification.

**Comment by Ska-K** [comment]
Same "problem" here. I understand that's the expected behaviour but there is no way to avoid the notification event to be fired when the alert is tap?

**Comment by macdonst** [comment]
@Ska-K No, there is no way to avoid the notification event from being fired twice. If you want to make it a pure silent notification then you should not provide an `alert` for iOS to show. The notification will still be delivered to the device but nothing will show up in the notification shade.

If you still want to see the notification in the shade then you can put a unique ID in the notification so you can check to see if the app has already processed it.
