### ISSUE TITLE
Process notifications in background

### ISSUE THREAD

**Issue by filoozom** [phonegap/phonegap-plugin-push#398]
I'd like to process some notifications in my app even if the user didn't click on it to open my app.
The ```.on('notification')``` works, but I only get the payload when either : 
- The app is opened via a click on the notification
- The app was already opened and in foreground.

Why doesn't the plugin execute ```PushPlugin.sendExtras(extras);``` on every message received (at least on the Android version) ?
Wouldn't it be better to send the payload to the app, show a notification and call a second ```.on('notification')``` when the user actually opens the notification ?
That way we could send push-to-sync requests.

Or am I missing something ?

**Comment by fredgalvao** [comment]
There's two things involved here:

- One is that when an app is not running at all on android (was never opened, or was forcedly closed through the launcher or "alt-tab") the event handlers are non-existing, and we still need to find a way to restore them in this scenario so that notification events can fire even if the app is completely dead. See [this issue](https://github.com/phonegap/phonegap-plugin-push/issues/211), [this one also](https://github.com/phonegap/phonegap-plugin-push/issues/158) and [this other one](https://github.com/phonegap/phonegap-plugin-push/issues/324), they explain better the situation, and why it's still not available.

-  The other is that we don't have a dedicated event for when a notification is **received on the device** in general, but only when it's **clicked by the user**. There is one type of notification hereby called [background notifications](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications) that gives you the option to skip from `receive -> display notification -> run click handler -> trigger 'notification'` to `receive -> trigger 'notification'` but in this case no notification will be shown to the user at all. The topic on splitting the events has been brought up on [this PR](https://github.com/phonegap/phonegap-plugin-push/pull/397) and on [this comment](https://github.com/phonegap/phonegap-plugin-push/issues/93#issuecomment-141408654).

You can always give your input on these options or simply +1 them so @macdonst knows what to prioritize.

**Comment by filoozom** [comment]
Thanks for the fast answer! I'll definitely take a look at these issues and PRs.
