### ISSUE TITLE
Android Marshmallow 6.0 push icon

### ISSUE THREAD

**Issue by adyz** [phonegap/phonegap-plugin-push#422]
I have an issue regarding the icon for push notifications in Android Marshmallow 6.0

On all other devices tested, the icon looks as wanted, but on Marshmallow the icon is just an white box.

I have the icon set generated with ionic `iconic resources`

My init looks like this:

	vv.push = PushNotification.init({

		"android": {
			"senderID": vv.params.googleGCMProjectNumber,
			"title":"Vivre",
			"icon": "icon"
		},
		"ios": {
			"alert": "true",
			"badge": "true",
			"sound": "true",
			"clearBadge": true
		}
	});

Do I need to change something in my config.xml or in the init or in the json set with the push service?

**Comment by fredgalvao** [comment]
What `targetSdkVersion` are you using (you can check `platforms/android/AndroidManifest.xml`)? Also, can you confirm that your icon works "as expected" on Android L(5.x)?

**Comment by adyz** [comment]
I have `<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />` in `AndroidManifest.xml`

With this setup and config, on my read device - Samsung Galaxy S4, it works as expected.

**Comment by adyz** [comment]
Here it is how the icons look: http://imgur.com/a/dBk7g

**Comment by adyz** [comment]
Also, in console, when I push I get: `Number format exception - Error parsing notId: Invalid int: "null"` are the two correlated? I've searched about this error and it looks like this does not interfere with the notification system.

**Comment by nicoabie** [comment]
Does the icon appears in ```platforms/android/resources ``` folder?

**Comment by adyz** [comment]
Yes, the `res` folder.

But I think the problem is that my icon is not transparent. I think I need to create the small one transparent and the large one from the external source. No sure how I'll handle this because my icon is not transparent. 

Damn material design. Any tips on this? Should I micro manage all icons?

**Comment by adyz** [comment]
Guys, since this is changed in android 6.0, wont be great to have a config where to specify the path to the small icon that is changed and leave the rest as it was?

**Comment by macdonst** [comment]
@adyz all of this is documented at:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images

I consider this issue to be closed. You use the `icon` parameter in the `init` method to specify the image with transparency you want to see in the push notification and the status bar. If you don't specify anything it will default to the apps main icon.

There is no sense fighting the Material guidelines as this has been a fact of life since Android 5.0. You'll have to work on an icon that has some transparency. Use the transparent pixels like the M in a Gmail icon to provide differentiation.
