### ISSUE TITLE
Xcode problem

### ISSUE THREAD

**Issue by jcus0006** [phonegap/phonegap-plugin-push#493]
I am using this plugin on a Cordova app meant to run cross platform on Android, WP, and iOS.
I am using a todo app called Backbonetodo. I meant to implement the registration and receiving of notifications from this app before trying to implement into the actual application I am developing.

Right now I am working on the iOS part.

I am getting these kind of error (over 20x) when trying to run the project from the iOS folder in Xcode (just copied the first 3 errors):

clang: error: no such file or directory: '/Users/Jurgen/Documents/Xcode/backbonetodo/BackboneToDo/platforms/ios/BackboneToDoPluginsphonegap-plugin-pushGCMLibrarieslibGGLCloudMessaging.a'
clang: error: no such file or directory: '/Users/Jurgen/Documents/Xcode/backbonetodo/BackboneToDo/platforms/ios/BackboneToDoPluginsphonegap-plugin-pushGCMLibrarieslibGGLCore.a'
clang: error: no such file or directory: '/Users/Jurgen/Documents/Xcode/backbonetodo/BackboneToDo/platforms/ios/BackboneToDoPluginsphonegap-plugin-pushGCMLibrarieslibGGLInstanceIDLib.a'

I have noticed that after the BackboneToDo in the string there seems to be no '/' and also after Plugins. 

It seems as if the way the location string is being created is not right. However, I don't think the issue is with that but could be more of a setting, something I am doing wrong, or something I am not doing that is causing the problem. (As with other things there does not seem to be a problem).

I tried to fix the location to absolute but it did not solve the problem. 

Did someone encounter the problem? Is there a fix to this? Is there something I missed? Does someone have a solution?

Thanks in advance.

**Comment by macdonst** [comment]
@jcus0006 what version of Xcode and Cordova-ios are you using?

**Comment by jcus0006** [comment]
XCode version 7.2

Cordova, how do I check? Cordova should have been working properly cause I had previously managed to run a cordova app from xcode on an ios device about 2 months ago. Recently, about 2 days ago, I tried setting up ionic and did not manage. Im thinking something I did by mistake could have ruined cordova or any other requirement for cordova apps to run?

Note I have never used xcode and this is all 100% new to me

**Comment by fredgalvao** [comment]
Run `cordova platform ls` from a terminal, that'll tell you which version of **cordova-ios** you have.

**Comment by jcus0006** [comment]
when doing this in a normal terminal window, I get cordova: command not found

from where should the terminal be opened? or it should get the version from anywhere?

**Comment by fredgalvao** [comment]
Your environment was not properly set up for cordova. It should be in your path, but it's not (the cmd couldn't find it).

How did you install cordova on your machine?

**Comment by jcus0006** [comment]
To be honest, initially I cannot remember if I had even installed cordova on my mac. In fact, I cannot understand how I had been able to run a cordova project on an iOS device through xCode by simply copying the Cordova app folder from the windows pc into the mac and running in XCode from the specific iOS platform. 

Around 2 days ago I was trying to set up Ionic as I know I am going to need it for a specific function on iOS. However, I didn't manage and some steps might not have been successfully installed. Some steps (cant remember which) returned errors such as that specific needed folders were not found. Could this have messed with the configuration of XCode and cordova?

Why could this happen?

I think I should start anew. Is there anyway to remove node.js, cordova etc, so that I can follow Visual studio's tutorial and start from the beginning? Perhaps if when trying to set up Ionic, this would solve the problem.

Any suggestions?

**Comment by fredgalvao** [comment]
# Cordova stuff

Copying a full cordova project (with it's platforms already added, that is) to another machine "works", but only as far as you can compile them on your own, if any native/shell code changes (as that's handled by IDEs such as XCode or Android Studio or Visual Studio). Now, if you made any changes to the cordova side of things (web code, that is. anything that lives in the **www** folder), none of these IDEs will properly propagate these changes to the final compile app by default, so that's where simply `copying a project over` doesn't completely work.

Now, on the topic of environment setup and installation, I'd suggest you install npm+node through whatever package management is available to you (apt-get on ubuntu, brew on mac, .exe on windows, or manually from the source on unix*), and then run the following:
`npm i -g cordova ionic`

Be warned, though, that these packages are not everything that's needed to actually run them successfully. You should check on their documentation for details on these.
Some links that should be time savers:
- [general installation details](http://cordova.apache.org/docs/en/latest/guide/cli/index.html)
- [ios installation details](http://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html)
- [android installation details](http://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html)
- [ionic installation details](http://ionicframework.com/getting-started/)

I wouldn't trust the IDE for everything on a cordova project's development cycle, but that's only my opinion (of a terminal monkey and linux poweruser-to-be).

# This plugin's stuff

Recently, changes have been made to the docs to clarify some cases and common errors on XCode when dealing with iOS compilation. You should check [them](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#ios-details) and try the solutions linked there.

I'll close this issue considering how unstable your environment settings are at the moment, but **don't hesitate** to reopen the issue if, even after fixing your cordova environment, these compilations issues are still present.

**Comment by jcus0006** [comment]
I fixed the problem. First of all I needed to re-install node. I had to install a remote agent to build the cordova iOS app from visual studio through node. Then, I added the ios-CFBundleIdentifier in the config to match the Bundle identifier name. Finally I had to fiddle around a bit with the provision and re-created a new certificate from Apple Developer, exported the .p12 file from the certificate in keychain and added it to the Azure portal notification hub configuration.

That got it up and running. Thank you for your help.
