### ISSUE TITLE
PushNotification is not defined

### ISSUE THREAD

**Issue by faustoct** [phonegap/phonegap-plugin-push#510]
I added PluginPush to my project 
cordova plugin add https://github.com/phonegap/phonegap-plugin-push
or
cordova plugin add phonegap-plugin-push

when I do console.log(PushNotification) I got this message: "PushNotification is not defined"

Does anyone know how to fix? Is it a bug?

**Comment by macdonst** [comment]
@faustoct Did you wait until you got the `deviceready` event before you tried to log `PushNotification`?

**Comment by faustoct** [comment]
Yes, I did. Everything is done on deviceready

**Comment by macdonst** [comment]
@faustoct run `cordova plugins` from the command line. Do you see phonegap-plugin-push in the list?

**Comment by faustoct** [comment]
Yes

fausto$ cordova plugins 
com.google.playservices 21.0.0 "Google Play Services for Android"
cordova-plugin-admobpro 2.8.3 "AdMob Plugin Pro"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-google-analytics 0.8.0 "Google Universal Analytics Plugin"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-whitelist 1.0.0 "Whitelist"
phonegap-plugin-push 1.5.2 "PushPlugin"

**Comment by faustoct** [comment]
versions info
MacBook-Pro:news fausto$ cordova -v
5.1.1
MacBook-Pro:news fausto$ phonegap -v
5.1.1-0.29.0

**Comment by fredgalvao** [comment]
I'd say there is a 95% chance that the issue here is a bad installation, which may have been caused by:

- a bug in cordova 5.1.1 (you can try updating to 5.4.1 and rebuilding or reinstalling the plugin)
- a buggy scenario in your project which made this plugin's code to not run at all (you can try reinstalling the plugin)


Can you try any of the mentioned above?

**Comment by faustoct** [comment]
Yes, I can.

**Comment by faustoct** [comment]
I re-installed and everything stopped working. Now I have to fix a lot of plugin issues, building, conflicts, etc. Probably will take more than expected.

**Comment by faustoct** [comment]
Still not working.

This is what I have tried

cordova plugin
cordova-plugin-admob 2.11.1 "AdMob Plugin Pro"
cordova-plugin-extension 1.1.4 "Cordova Plugin Extension"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-whitelist 1.0.0 "Whitelist"
phonegap-plugin-push 1.5.3 "PushPlugin"

cordova -v
5.4.1

config.xml I tried to add (and now is commented)
<gap:plugin name="com.adobe.phonegap.push.PushPlugin"/>

on index.html (and now I deleted)
<script type="text/javascript" src="push.js"></script>

I'm trying on localhost via "phonegap serve". Does it work in "localhost mode"?

**Comment by faustoct** [comment]
I created an apk and installed on my phone. It seems working. I'm going to test a bit more to make sure. 

Is there a way to test on "localhost mode"? It's painful all the time send the apk to my phone and install it.

**Comment by faustoct** [comment]
I'm gonna close it. It definitely doesn't work with "phonegap serve" neither localhost

**Comment by fredgalvao** [comment]
Oh, had I known you were trying to make it work with `serve` we'd both have saved a lot of time.

`phonegap serve` simulates your cordova application running on a browser, served from a local webserver. The thing is, all and any native code that needs to run (from cordova or plugins) need to be mocked through javascript to work on that mode, for there is no "native device" to run java or objective-C code. That's why this plugin (phonegap-plugin-push) didn't work: your browser doesn't know what to do when the js looks for the native side of himself.

**Comment by faustoct** [comment]
I know that is the wrong topic but how hard is to run native plugins locally?

**Comment by faustoct** [comment]
It could be documented.

**Comment by faustoct** [comment]
# phonegap-plugin-push doesn't work with phonegap serve nor running locally.

**Comment by fredgalvao** [comment]
It's technically impossible to **run** native code on a browser. What can be done is mocking: make a new version of the plugin javscript code that instead of asking for a native side, fakes a response to the user. Even then, you'd be limited to what can be faked and what cannot. You can't really fake a message being sent from GCM, for example.

**Comment by macdonst** [comment]
@faustoct oh, now I see what you are trying to do. The phonegap-plugin-push is not installed in PhoneGap Developer App. I've been working on a way to make this possible and hope to have some big news in the not too distant future.

**Comment by faustoct** [comment]
Great, best of luck in this improvement. A workaround I've done so far is: build a local apk and send to my phone via bluetooth. It has helped me.

`
cordova/clean
cordova build --release
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore <your-keystore> build/outputs/apk/android-release-unsigned.apk <your-alias>
zipalign -v 4 build/outputs/apk/android-release-unsigned.apk build/outputs/apk/<your-app-name>.apk
`

Enable bluetooth on phone and pc. Send a file. Install locally. Test your notification system.

**Comment by fredgalvao** [comment]
You can delegate your signing properties to a certain file so that gradle picks it up automatically for you. See docs [here](https://cordova.apache.org/docs/en/5.4.0/guide/platforms/android/tools.html), @"Signing the App".

With that, you can replace all of these commands with `cordova clean && cordova run android --device` with your device connected through USB and debugging enabled.

**Comment by faustoct** [comment]
thanks. I'll have a look!

**Comment by faustoct** [comment]
thanks. I'll have a look. Does PluginPush work this way?

**Comment by fredgalvao** [comment]
Any and every cordova plugin MUST work with that way of compiling/building, otherwise it's a bug.

**Comment by faustoct** [comment]
@fredgalvao thanks my friend for your advice. It works perfectly.

**Comment by dcere** [comment]
After having wasted a day and a half I found this issue and after creating the apk and installing it everything worked fine. So I am very very much for including those big bold letters somewhere in the documentation. Somewhere where people cannot miss it.
Since issues #328 and this one both found the same problem, maybe it is a good idea to put it clearly upfront. What do you think?
