### ISSUE TITLE
Phonegap build iOS GCM Registered but not receiving notification

### ISSUE THREAD

**Issue by ahlidap** [phonegap/phonegap-plugin-push#532]
Hi,

I've been using the plugin with GCM on Android with no major problems so far, but I can't get it to work for iOS.

I'm using Phonegap Build on my project.
When using the plugin to work with the native APNS servers, it seems to work OK, but now that I need to use Android GCM Service, I can't get it to work.

config.xml:

```
<gap:plugin name="phonegap-plugin-push" source="npm" version="1.5.3"/>
```

Also tried something like this (as seen here: https://github.com/phonegap/phonegap-plugin-push/issues/440#issuecomment-170683762 )
```
<gap:plugin name="phonegap-plugin-push" source="npm">
        <param name="SENDER_ID" value="265882065897"/>
        <param name="GOOGLE_APP_ID" value="1:265882065897:ios:fbcd21ebe894ee64"/>
    </gap:plugin>
```

Plugin init:
```javascript
pushNotification = PushNotification.init({
        ios: {
            senderID: GOOGLE_PROJECT_ID,
            gcmSandbox: true,
            alert: "true",
            badge: "true",
            sound: "false"
        }
    });
```

I've successfully uploaded .p12 file to google platform, with respective iOS App Bundle ID, activated cloud messaging and downloaded plist file (just in case, as I don't do local builds).

On registering I successfully get GCM ID in the following format:
```
lQipKUX0CyU:APA91bFFafKjEz2Ju2acoDJGz___A3_ZMWDLt4VYi8MQXkUXt3j653LDo8woWIpW4WCbprGBdgNcxdHV3B7U-yrrB4bcd4OqBr1A5SNvI-0Mi4KDosFxKoN1qciXqllXYNN8T6jvnKTe
```

Sending a payload like this to google service:
```
{
"to": "REGID",
    "data": {
      "message": "This is a Message!"
}
```

also tried APNS way like this:
```
{
"to": "REGID",
"aps":{"alert":"Hello from APNs Tester.","badge":"1"}
}
```

Both ways result in a successful post request to Google GCM Service, but no notification is received on iOS phone.

This is the code I have on both Android and iOS:
```
pushNotification.on('registration', function(data) {
        GCM = data.registrationId;
        console.log("SUPER GCM_ID = " + GCM); 
    });

    pushNotification.on('notification', function(data) {
        console.log('CHEGOU NOTIFICAÇAO');

        // Foreground
        if (data.additionalData.foreground) {
            buildPush(data);
            //navigator.notification.alert(data.message, null, messages.pushMessage);
        } 
    });

    pushNotification.on('error', function(e) {
        console.log('PUSH PLUGIN ERROR: ' + e.message);
    });
```

So, it successfully fires 'registration' event, but do not fire 'notification' or 'error' events.
Am I missing something?
I've tried before with APNS service and it works ok (of course without senderID and Sandbox options).

As I use my own database and code to send push to Android devices, it would be great to reuse that code, although I don't know if google converts GCM payload to APNS or if I need to send them in a separate way.

Thanks in advance.

**Comment by macdonst** [comment]
@ahlidap Yeah, when you push to an iOS device using GCM it just forwards your payload along to APNS. However, what I have noticed is that it is picky about the format you send. 

Try:

```
{
"to": "REGID",
    "notification": {
      "title": "This is a Title!",
      "body": "This is a Message!"
   }
}
```

which is a pain because that payload won't trigger your Android code as the OS will intercept it. You'd have to swap `notification

**Comment by ahlidap** [comment]
@macdonst Thanks for your help.
It's working now.
In fact, I missed this details from Google GCM Documentation:
https://developers.google.com/cloud-messaging/ios/client#http_post_request)

sorry.
Time to code!
Thanks again

**Comment by morioma** [comment]
Thank you both, I had the exact same problem. The format is the culprit.

Just some additional information here that could help others.
1, Somehow, I am using production instead of development when I am developing on my local ipad. So I am using gcmSandbox:false, this is confirmed when I use the OS X 'APN Tester Free' where I used prod key and chose 'ad-hoc/production'
2,  I didn't touch the plist file at all, I only have the SENDER_ID in my cordova config.xml. Basically, I ignored GOOGLE_APP_ID all together.
3, setting "priority":"high", and "content_available": true at root level helps. [Ref](http://stackoverflow.com/questions/31109514/making-gcm-work-for-ios-device-in-the-background/36784310#36784310).

**Comment by Assylkhan** [comment]
I cannot get it work. I use firebase console to sending push notification. Created app in firebase, uploaded p12 and got GoogleService-Info.plist. And paste it instead of another plist in cordova-plugin-fcm-config folder(I use this lib: https://github.com/stetro/cordova-plugin-fcm-config). My app's bundle id in developer.apple.com and id in config.xml match. I start phonegap server and see that no errors. And I've tried to send push notification in firebase console, but in my iphone I don't receive notifications. What am I doing wrong? Thnx

**Comment by Juangon180** [comment]
A mi me pasó lo mismo con phonegap-plugin-push y no pude solucionarlo.
para iOS desinstalé el plugin ¨phonegap-plugin-push¨ e instale el plugin ¨cordova-plugin-fcm¨ https://github.com/fechanique/cordova-plugin-fcm, y ya funcionaron las notificaciones para iOS.
