### ISSUE TITLE
Error: NotRigested by GCM with iOS

### ISSUE THREAD

**Issue by demiurga** [phonegap/phonegap-plugin-push#567]
Just like @trsdln said in #548 
> I am able to get device token using this push plugin. Then I register token on server side. After that I send my first notification using GCM API and got success response but there is no notification on device. When I am trying to send second (and for all next notifications too) I got response:
> ```js
> {"error": "NotRegistered"}
> ```

iOS: 9.1
cordova-ios: 3.9.2
plugin: 1.5.3

```coffee
PushNotification.init({
            android: {
              senderID: SENDER_ID
            },
            ios: {
              badge: true
              sound: true
              clearBadge: true
              senderID: SENDER_ID
              gcmSandbox: true
            },
            windows: {}
          });
```

It's works fine on android, any ideal with that?

**Comment by demiurga** [comment]
@macdonst do you have any ideal where the problem is? or I lost any information you need?

**Comment by macdonst** [comment]
@demiurga no idea, I tried to reproduce this today and could not.

**Comment by trsdln** [comment]
Looks like we made some mistake while setting up APNs/GCM

@macdonst Is there any instruction/instruction for this setup we can use?

**Comment by shaoyunli** [comment]
We are experiencing exactly same issue. I have checked the provisioning file and certificates but could not see if there is anything wrong in the configuration.

**Comment by macdonst** [comment]
Sorry all, GCM on iOS is like black magic. I can't even find the URL to enable GCM for iOS anymore. You'd think google would make it easier.

**Comment by shaoyunli** [comment]
@macdonst you can access https://developers.google.com/mobile/add to enable GCM for iOS. I have enabled the service for the app with App name and iOS bundle id. When enabling GCM for iOS, two certificates were uploaded. The two certificates are also bound to the iOS bundle id. The provisioning file was generated based on the iOS bundle id with the two certificates. I cannot see if there is anything I have done wrongly but am very frustrated it is just not working except the first time then 'NotRegistered' failure again. 

In the issue https://github.com/phonegap/phonegap-plugin-push/issues/115, @bruno-serfe mentioned, The following certificates are needed. 

- Google Cloud Messaging. (APNS .p12 cert) - (I understand the two certs needed to be uploaded to enable the service
- Make the push notification. (APNS .pem cert) - (Where do I need this .pem cert if I use node-gcm to send message on server. )

Do I miss to use the .pem cert so that the push notification does not work?

**Comment by shaoyunli** [comment]
@macdonst I have made some progress today to get the notification pushed to an iPad. I have not changed anything apart from adding an attribute **gcmSandbox: "true"**. After the change, the messages were sent successfully. However I don't understand why the message can be sent through GCM sandbox rather than production. Is it because the certificate of my app on the iPad is a development certificate? 

Beside, I used the server API Key which does not have GCM enabled for iOS. It looks like it doesn't matter to enable the service or not, and through GCM sandbox, the notifications can still be pushed to iOS devices. 

Dose it make any sense?

**Comment by macdonst** [comment]
@shaoyunli if you build your app as development then you need to set gcmSandbox:true. If you build your app for production then you need to set gcmSandbox:false.

**Comment by rkj1515** [comment]
I am getting successful registration Token
Your Default init json should be like  for iOs
            ios: {
                senderID: "XXXXX",
                "gcmSandbox": "true",//for Testing purpose
                "alert": "true",
                "badge": "true",
                "sound": "true",
                "priority": "high",
                clearBadge:"true"
            }

here is a trick for upload APNS certificate .p12
 follow [this](http://stackoverflow.com/questions/30602340/how-to-generate-valid-apns-certificate-p12-for-use-in-gcm-for-ios)
some time **export 2 time** gives error so download certificate separate and merge both using **cat cert.p12 key.p12 > cert_merged.p12** 
follow [this](http://stackoverflow.com/questions/31982238/gcm-certificate-configuration-not-working-or-ios upload your certificate)

you will get Registration token for APNS and GCM registration id both

**Comment by dtruel** [comment]
For me I found the issue was the `gcmSandbox:true`.  You also have to have the right development certificate uploaded to google.
