### ISSUE TITLE
delay on client side

### ISSUE THREAD

**Issue by alexislg2** [phonegap/phonegap-plugin-push#579]
Hey,
I'm using this plugins for one year now. I noticed something anoying: although most notifications arrive within seconds after they have been sent some of them take more than one minute. I first thought that was link to network/GCM/wifi/mobile carrier issues but then I made a test. I send GCM message to both my tablet and my smartphone simultaneously and my tablet always receive the notification with at least 10 seconds of delay compared to the smartphone.

They are both connected to the same wifi so I guess GCM message was received by both ~ simultaneously. My conclusion is that the delay is on client side

Any explenation? Anyone experienced such delays?

**Comment by macdonst** [comment]
@alexislg2 there is no quality of service guarantee with push notifications. There are many factors as to why the push arrives later on your device than on your tablet. Your Android device keeps a idle socket connection open with the GCM server to receive pushes. The pushes you send to GCM are rate limited so it may be that your push to the tablet goes out in a batch long before the one to your phone. Remember GCM is serving millions of phones out there.

Now, you may be thinking. Why don't I roll my own GCM like service for Android. Well, I can tell you for a fact since I've done it, it can be done. However, unless done amazingly well it can really kill your battery life. I really don't recommend anyone doing it.
