### ISSUE TITLE
iOs custom sound for push

### ISSUE THREAD

**Issue by MikeBazhenov** [phonegap/phonegap-plugin-push#607]
Hello!

I write file `beep.caf` to `/platform/ios/` in settings `sound: true`

And when i send push with data
```js

aps: {
      alert: 'Test',
      sound: 'beep.caf',
      payload: { info: 'test' }
    }

```
`beep.caf` not played, played default push sound..

**Comment by fredgalvao** [comment]
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound

> Note: when you specify the custom sound file name omit the file's extension.

**Comment by MikeBazhenov** [comment]
@fredgalvao it for android, i want custom sound on ios

**Comment by fredgalvao** [comment]
Oh, nevermind me. I derped on that `/ios` string.

**Comment by macdonst** [comment]
@MikeBazhenov well @fredgalvao sent you the wrong link:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound-1

but his comment.

> Note: when you specify the custom sound file name omit the file's extension.

is still valid and that's why you are not getting your custom sound.

**Comment by dtruel** [comment]
I'm having this issue too, except it's a little different for me because it only happens when I download from test flight to another device.

I am downloading the sound "siren.wav" to "Library/Sounds" on my device on startup.  When I build and run from my computer, the sound plays just fine.  When I upload my app to the app store and then install it on my test device the sound plays just fine.  But when I download the app to a new device, only the default sound plays!  I hooked up my old iPhone (running ios 8), and looked through the application data container, and sure enough, the sound had been downloaded properly and worked in iTunes.  The sound is there, but it still plays the default notification. I also had someone with ios 9 download it and they had the same issue.  Any idea why?

Thank You!

**Comment by macdonst** [comment]
@MikeBazhenov haven't heard back but I assume your problem was solved by removing the extension from the filename.

**Comment by dtruel** [comment]
I just gave up.  I think it only works on ios 9

**Comment by macdonst** [comment]
@dtruel if you are using GCM on iOS then you are running into #509

**Comment by pritish5** [comment]
is custom sound will play for enterprise IOS app?

**IOS**
```
"aps": {
		"alert": "Test sound",
		"sound": "sub.caf"
	}
```
