### ISSUE TITLE
Phonegap build doesn't put plugin in apk but in iOs is okay!!

### ISSUE THREAD

**Issue by pooya511** [phonegap/phonegap-plugin-push#636]
Hi ,

Everything works fine with ios. I wrote this at config.xml:

 plugin name="phonegap-plugin-push" source="npm"

When I make application template with phonegap build for iOs its okay and push notification works fine with my iPhone but phonegap build doesn't put the plugin into .apk application template. I wonder why?

**Comment by macdonst** [comment]
@pooya511 you didn't follow the issue template and you didn't give me any logs from PGB or any configuration files so I can only guess at what's wrong. That's why I created the issue template to cut down on back and forth. 

Did you follow?

https://github.com/phonegap/phonegap-plugin-push/blob/v1.6.x/docs/PHONEGAP_BUILD.md#including-the-plugin

**Comment by macdonst** [comment]
the PGB team has asked for people with issues regarding phonegap build please start an issue on the support forum: https://forums.adobe.com/community/phonegap/build

please include an app id of an app that can replicate this issue.
