### ISSUE TITLE
Device makes sound and vibrates, but notification not shown in alert

### ISSUE THREAD

**Issue by dtruel** [phonegap/phonegap-plugin-push#642]
### Expected Behaviour

Alert should show when notification recieved on Android
### Actual Behaviour

Phone vibrates and makes noise when notification is received, but no alert message pops up.  It just makes noise.  It is in the notification center, though.
#### Steps to Reproduce

In app

```
        var push = PushNotification.init({
            android: {
                senderID: "############",
                alert:"true",
                sound:"true",
                badge:"true",
                icon:true,
                vibrate:"true",
                forceShow:"true"
            },
```

Serverside:

```
$data = [
  "registration_ids" => [$gcm_id],
  "content_available" => true,
  "priority" => "high",
  "notification" => [
    "title" => "Alert",
    "body" => "Alert!!",
    "sound" => "siren"
  ]
];
```
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 5.1.1

**Comment by macdonst** [comment]
@dtruel send this instead:

```
$data = [
  "registration_ids" => [$gcm_id],
  "content_available" => true,
  "priority" => "high",
  "data" => [
    "title" => "Alert",
    "body" => "Alert!!",
    "sound" => "siren"
  ]
];
```

Close this issue if it works.

**Comment by dtruel** [comment]
I have tried that before and tried it again, and unfortunately when I change it to `data` from `notification` I don't get any title or body or sound.

**Comment by luiscvalmeida** [comment]
Something similar is happening to me.
```
var push = PushNotification.init({
                android: {
                  senderID: androidSenderId,
                  icon: 'white_icon',
                  iconColor: '#0F2F7F',
                  sound: true,
                  forceShow: true
                },
                ios: {
                  alert: true,
                  sound: true,
                  badge: true
                }
              });
```

As you see, I am using `forceShow` , and when I set this `true`, the notification (native) shows up, but the `push.on('notification')` event isn't firing any more. Once I set `forceShow` to `false` again, the native notification only shows when app closed / on background, and the `push.on('notification')` works as expected again.

Anyone with the same issue? I want `forceShow` to be true, but I want to catch up the `push.on('notification')` also.

**Comment by AdriVanHoudt** [comment]
The event will only be called once the user clicks on the notification. If it swiped away for example the event will never fire.

**Comment by luiscvalmeida** [comment]
That way we can not do anything with the notification a user receives while having the app opened, it should fire the native notification + the `push.on('notification')` event.

**Comment by AdriVanHoudt** [comment]
you mean you want to show the notification, get it internally and handle it and handle it again when the user clicks on it?

**Comment by luiscvalmeida** [comment]
Exactly, I think it's really important to keep firing the `push.on('notification')` event when we receive the notification, as you may want to do anything with it (in my case I have a bell icon in the top right corner on the screen and it needs to get a red badge circle, and I can't do that without the event call.

Ideally, the click on the notification would not call the `push.on('notification')` event (because the truth is we didn't receive the notification when clicking on it, we received it before), but could call another different event.

**Comment by AdriVanHoudt** [comment]
Well the event is for when the app recieves the notifications, this can be 2 cases
1 you send a notification that contains no info on how to show it, thus telling the device it is a message(e.g. just some data) and not something to show to the user. Since there is nothing to show the device and plugin will forward the notification to your app (via the event) to handle it
2 you send a notification with a title and message etc., the devices decides it needs to show the notification. Then when the user presses the notification, the plugin forwards the notification to your app (via the event) to let you handle it. Usually open a specific view

Calling the event twice for the same notification would be weird since it would mean that you receive a notification and without the user clicking on it you switch view or something. 
If you really want to show and handle the same notification I suggest sending it twice, once with properties to show it and the other with just data telling your app to show a red circle on your bell icon

I hope this was somewhat clear :P

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
