### ISSUE TITLE
Remove sender id from PushNotification init Android options

### ISSUE THREAD

**Issue by restarian** [phonegap/phonegap-plugin-push#689]
#### The sender id in version 1.6.0+ is now available as a plugin variable, thusly should be omitted from app front-end script.

```
[Notification_Peripheral] Plugin error with the PushNotification process {
  "0": Error: No value for senderID
    at fail (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:56:49)
    at Object.cordova.callbackFromNative (file:///android_asset/www/phonegap.js:293:52)
    at processMessage (file:///android_asset/www/phonegap.js:1079:17)
    at processMessages (file:///android_asset/www/phonegap.js:1102:9)
    at pollOnce (file:///android_asset/www/phonegap.js:971:9)
    at pollOnceFromOnlineEvent (file:///android_asset/www/phonegap.js:958:5)
}
```

**Comment by macdonst** [comment]
@surgemcgee Yes, that is the plan but I'm waiting until a 2.0.0 release as I don't want to make a breaking API change.

**Comment by jakub-g** [comment]
In fact just FYI it was already a breaking change with 1.6.0 release kind of.

I'm using ionic and a build script does `ionic state restore` to install platforms and plugins (which reads `package.json` and install stuff with proper versions and variables)

When I bumped version from 1.5.3 to 1.6.0 in `package.json` and let my scripts run, it failed due to missing SENDER_ID configuraton.

I had to change

```
 "phonegap-plugin-push@1.5.3",
```
to
```
{
  "variables": {
    "SENDER_ID": "........"
  },
  "locator": "phonegap-plugin-push@1.6.0",
  "id": "phonegap-plugin-push"
},
```

If someone had `^1.5.3` in `package.json`, or unspecified version, their automated CI build would take `1.6.0` and fail.

That's why I prefer strict versions in `package.json` to have control over the update process :)

**Comment by ujjal008** [comment]
Ionic Core: init
ionic.io.bundle.min.js:2 Ionic Core: searching for cordova.js
ionic.io.bundle.min.js:2 Ionic Core: attempting to mock plugins
ionic.io.bundle.min.js:2 Ionic Push: register

But when I install on device not get devicetoken. call back function not working:

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    alert("push")
    var push = new Ionic.Push({
      "debug": true
    });

    push.register(function(token) {
      alert(token);

      //alert("Device token:",token.token);
      push.saveToken(token);  // persist the token in the Ionic Platform
    });
  });
})

**Comment by macdonst** [comment]
Closing as it is part of released RC's.
