### ISSUE TITLE
Unable to install plugin on both iOS/Android

### ISSUE THREAD

**Issue by dilipsarkar** [phonegap/phonegap-plugin-push#693]
I was trying to verify the fix for issue` #688` but I'm unable to installed the plugin. I get the below error on both iOS and Android.

```
cordova plugin add CustomPlugins\phonegap-plugin-push-master
Error: Variable(s) missing (use: --variable SENDER_ID=value).

```
I'm using `cordova 5.4.1`. Please help.

**Comment by jakub-g** [comment]
See https://github.com/phonegap/phonegap-plugin-push/issues/689#issuecomment-195316034

when you install from command line, pass `--variable SENDER_ID=1234` as required. If you use Android and GCM, you already know sender id (and you already pass it in `android` config when registering the plugin). Otherwise put a fake value.

**Comment by dilipsarkar** [comment]
Thanks for your quick response. 

Just a clarification, does this mean we don't have to specify `senderID `for android while invoking `PushNotification.init()` API ?

```
var push = PushNotification.init({
    android: {
      senderID: "12345679
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    },
    windows: {}
});
```

**Comment by jakub-g** [comment]
in 1.6 you have to do it in both places, in 2.0 only in `package.json`

**Comment by dilipsarkar** [comment]
Great, thanks
