### ISSUE TITLE
Error - One of your plugins requires a parameter: SENDER_ID 

### ISSUE THREAD

**Issue by sreereddymenon** [phonegap/phonegap-plugin-push#711]
Iam using  https://build.phonegap.com/apps for builds.  After uploading source code to the site. It gives me  below error for Android build. 

> Error - One of your plugins requires a parameter: SENDER_ID - You can fix this here

 But in my config.xml  file .

```
<plugin name="phonegap-plugin-push" source="npm">
    <param name="SENDER_ID" value="123456789" />
</plugin>
```

and on 

```
var push = PushNotification.init({
                    "android": {
                        "senderID": "123456789"
                    },
                    "ios": {"alert": "true", "badge": "true", "sound": "true"},
                    "windows": {}
                });
```

can anybold help me to solve the issue. Thanks.

**Comment by netomia** [comment]
I can't remember where I found this, but maybe that's what you are looking for?

cordova plugin add phonegap-plugin-push --variable SENDER_ID=123456789

**Comment by macdonst** [comment]
@sreereddymenon that looks correct to me.

**Comment by ahlidap** [comment]
I can confirm that!
I've just opened this issue (don't know if it might be related).  https://github.com/phonegap/phonegap-plugin-push/issues/745

After modifying config.xml to update to cli 6.0.0 to see if I can get version 1.6.0 to work, PGB now gives me that error (although right now my problem is in iOS)

**Comment by solstice428** [comment]
I have been having this issue with exactly the same content. I installed with cli 6.1 Does this have to do with the cli version? It shouldn't affect the install right? I specify   
`  <preference name="phonegap-version"           value="cli-5.2.0" /> 
`
but i am still getting the same error from the build. I would also like to note that did install the plugin using the --variable SENDER_ID because it is required through the cli and I have 
"Android Support Library version 23 or greater
Android Support Repository version 20 or greater
Google Play Services version 27 or greater
Google Repository version 22 or greater" 
Installed as well. I would really appreciate any help with this. I havent attempted downgrading my cli version but I am kinda hoping to avoid that.

**Comment by solstice428** [comment]
@sreereddymenon any update on this issue? I have been having the same issue in phonegap build with the same content I tried installing the 1.6.0 version and the 1.5.2 just in case. I have everything installed in the android sdk manager, installing the plugin through the cli which requires the --variable SENDER_ID, and have the same config and js, even used the example www/ for the content portion to get something going.

**Comment by lakshaydulani** [comment]
any solution for this?

**Comment by nickwebha** [comment]
Also having this issue with PhoneGap Build. Looking for a solution.

**Comment by lakshaydulani** [comment]
Setting params worked.. Thanks
