### ISSUE TITLE
Error on notification with IOS 

### ISSUE THREAD

**Issue by Robiig** [phonegap/phonegap-plugin-push#723]
- App crashes on notification when in background.
- Nothing append when the app is not running.

- Works fine when app is running

I'm using GCM.

Cordova 6.0.0
Plugin-push 1.6
Iphone 5c IOS 9.2.1

-Everything Works fine with Android

**Comment by macdonst** [comment]
@Robiig I need more info to debug the problem. Please provide the details requested in the open issue template.

**Comment by s4lesman** [comment]
@macdonst I have the problem when the app is not running on iOS, here:

### Expected Behaviour

  Notification arriving always.
### Actual Behaviour

 Notifications only arrive when the app is running (foreground and background). If the app is not running, no notification gets to the device notification panel.

### Reproduce Scenario (including but not limited to)

  Im using node-gcm to send notifications from my api to GCM, I have the certificates on GCM and notifications only go through when the app is running. Working perfectly on Android though.

#### Steps to Reproduce 

  force quit the app and Push a notification through GCM to ios

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
  iPhone 5s iOS 9.3

#### Cordova CLI version and cordova platform version

   Cordova 6.0.0
   Cordova ios 4.1.0

#### Plugin version

    phonegap-plugin-push 1.6.1

#### Sample Push Data Payload

   The default, I'm only changing the notification and data objects

#### Sample Code that illustrates the problem
 
```
  sender = new gcm.Sender(settings.gcm.API_KEY)
  message = new gcm.Message()

  message.addNotification 'title', 'test app'
  message.addNotification 'body', 'test msg'
  message.addNotification 'icon', 'logo'
  message.addData 'content-available', '1'
  message.addData 'priority', 'high'
```

#### Logs taken while reproducing problem
   nothing useful

**Comment by macdonst** [comment]
@s4lesman yes, if you kill the app on iOS and are using GCM to send the message you won't get the push. I believe there is another issue open that describes this and I'm not sure what I can do about it.

**Comment by s4lesman** [comment]
@macdonst I thought GCM communicated with APNS and pushes would go through.. do you have any idea why this happens? Is there any known workaround?

thanks.. I couldn't find the other issue, so I decided to post my problem here.

**Comment by macdonst** [comment]
@s4lesman I believe, and I may be wrong, that GCM on iOS needs a persistent connection so that may be causing the problem. Yes, GCM is supposed to send over APNS and it does but some of this stuff is straight up magic.

**Comment by s4lesman** [comment]
@macdonst what's the workaround? Not using GCM for iOS and going directly for APNS? I read the docs, it says the plugin supports APNS, but I couldnt find any further info.. whats your expert's advice? 

Thank you for you time!

**Comment by macdonst** [comment]
@s4lesman I like using APNS for iOS better than GCM.

**Comment by macdonst** [comment]
Closing, nothing back from original poster.
