### ISSUE TITLE
on('registration') not run in android

### ISSUE THREAD

**Issue by irianvillalba** [phonegap/phonegap-plugin-push#800]
### Expected Behaviour

Receive RegistrationId android device

### Actual Behaviour

the handler on ( ' registration ' ) is not executed , and the device has the correct permissions to register the device

### Reproduce Scenario (including but not limited to)

1) installed phonegap-plugin-push
2) installing dependencies
3) execute this code in intro app

    ionic.Platform.ready(function() {
    try {
	
		push.on('registration', function(data) {
				var alertPopup = $ionicPopup.alert({
				  title: 'Cliente',
				  template: data.registrationId
				});
		});	
    }
    catch (err) {
		//vazio
    }
  })

4) execute ionic run -l -c -s and run in android device samsung note 3

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 4.4.3
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
samsung note 3
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@irianvillalba did you call the init method of the push plugin?

**Comment by subhash8108** [comment]
Same issue on my apps.

I have used init method, but proper working. 

Cordova Version: 6.1.1
Android platform version: 5.1.1

I have check apps on android version 4.4, below my code
var app = {
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() { alert('hhhh');
        var push = PushNotification.init({
            "android": {
                "senderID": "XXXXXXXXXXXX"
            },
            "ios": {
                "alert": "true",
                "badge": "true",
                "sound": "true"
            },
            "windows": {}
        });
		push.on('registration', function(data) {
            $$("#Registered_PushId").val(data.registrationId);
        });
    }
};
app.initialize();

This code working on android up to 4.4 version... please suggest me

**Comment by macdonst** [comment]
@subhash8108 pretty sure you are running into #366 and you will need to update Google Play Services on the device where it isn't working.

**Comment by subhash8108** [comment]
![ipmsgclip_s_1461563418_0](https://cloud.githubusercontent.com/assets/542535/14774829/ddfb602e-0ad7-11e6-9934-00664ded785e.png)


Already install and updated.... 

![ipmsgclip_s_1461563556_0](https://cloud.githubusercontent.com/assets/542535/14774845/0f38c1fe-0ad8-11e6-9b22-e1ceaf05027a.png)

**Comment by macdonst** [comment]
@subhash8108 no, look at Google Play Services on the phone. I'm betting it is out of date and needs to be upgraded.

**Comment by deoxen0n2** [comment]
In my case it's not working on both Android and iOS. Both devices are granted Push permissions.

Android version: `6.0.1` (Nexus 5x)

```
$ cordova -v
6.1.1
$ cordova platform version
android 5.1.1
ios 4.1.1
```

`.init()` is called before running anything. `error` event does not fire either.

**Comment by macdonst** [comment]
Closing, inactivity

**Comment by GHR-Arash** [comment]
is this solved ? i have similar problem

**Comment by mohanchalla** [comment]
Hi @macdonst I am getting the following error
adb logcat | grep PushPlugin

11-09 15:51:21.257 12360 12579 V PushPlugin: execute: action=init
11-09 15:51:21.262 12360 12610 V PushPlugin: execute: data=[{"senderID":"540369641811"}]
11-09 15:51:21.277 12360 12610 E PushPlugin: execute: Got JSON Exception No value for android

**Comment by ntkzwane** [comment]
Hi @macdonst I am still experiencing this issue. I'm experiencing this issue for only android (working fine on iOS 4.3.0). The on('registration') event is never fired.

I am using `cordova@6.4.0` and building for `android@6.0.0`
I've installed `phonegap-plugin-push@1.9.0` alongside the `cordova-plugin-google-analytics`.
I've also removed the `cordova-google-play-services` plugin since it constantly gave me the error around multiple declarations of the `com.google.android.gms` package.

I've installed the required items through the Android SDK (see screenshot below):
![selection_270](https://cloud.githubusercontent.com/assets/9074285/20171036/9ae4492a-a737-11e6-8899-4d1dd93a21ff.png)

and I'm using my `config.xml` file to install the plugin, and specified the SENDER_ID as part of that like so:
```
<plugin name="phonegap-plugin-push" spec="1.9.0">
    <param name="SENDER_ID" value="XXXXXXX" />
</plugin>
```

Steps to reproduce (starting from a clean project with no platform added):
1. `add the plugins to `config.xml`
2. `cordova platform add android`
2. `cordova run android`

This is what the code looks like where I make use of the plugin:
```
push = PushNotification.init({
        "android": { "senderID": config.gcmSenderId, "icon": "notification_icon", "iconColor": "#0197e2" },
                "ios": { "alert": "true", "badge": "true", "sound": "true" }, "windows": {}
});

push.on('registration', function (data) {
        console.log(data.registrationId);
});

push.on('notification', function (message) {
        console.log(message);
});

push.on('error', function (e) {
        console.log(e);
});
```

For reference, this is the complete list of plugins I am using:
```
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-x-toast 2.5.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.0 "PushPlugin"
```

Note: I've tried all sorts of different permutations of the three plugins (`phonegap-plugin-push`, `cordova-plugin-google-analytics` and `cordova-google-play-services`) and concluded that `cordova-google-play-services` was a common denominator for me with either the **MultiDex** or **More than one library with name** issue, thus resulted in removing it completely.
