### ISSUE TITLE
can't not get DeviceToken.

### ISSUE THREAD

**Issue by gitHubLie** [phonegap/phonegap-plugin-push#842]
Hi,i have problem  ,look this img.
![2016-04-27 6 56 16](https://cloud.githubusercontent.com/assets/15965246/14850181/dd7dcdac-0ca9-11e6-9aaa-052d641ae332.png)
phonegap-plugin-push can't get  tokenId on ios .
I not know why?  A few days ago is ok .but now it not working .
don't call this "didRegisterForRemoteNotificationsWithDeviceToken" function. please help me .
but this plugin call two times. 

Thanks for you .

**Comment by casahuga** [comment]
+1

**Comment by cidus** [comment]
This just started happening to me also. It was working flawlessly a few days ago.
PushNotification.init call is successful, iOS asks for confirmation.
However, push.on('registration) is never called.
I get the same messages on Xcode.

I thought maybe the culprit was the recent node update? 5.11, so I downgraded, still no luck.

Maybe Apple changed something on their side?
```
ionic info

Your system information:

Cordova CLI: 6.1.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

ionic plugin
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-media 2.3.0 "Media"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-plugin-push 1.6.0 "PushPlugin"

```
Xcode

```
2016-04-27 09:19:59.019 myApp[10132:4520879] Start push configuration
2016-04-27 09:19:59.019 myApp[10132:4520879] on registration
2016-04-27 09:19:59.019 myApp[10132:4520879] on notification
2016-04-27 09:19:59.059 myApp[10132:4520991] Push Plugin register called
2016-04-27 09:19:59.059 myApp[10132:4520991] PushPlugin.register: setting badge to false
2016-04-27 09:19:59.059 myApp[10132:4520991] PushPlugin.register: clear badge is set to 0
2016-04-27 09:19:59.059 myApp[10132:4520991] PushPlugin.register: better button setup
2016-04-27 09:19:59.061 myApp[10132:4520991] GCM Sender ID (null)
2016-04-27 09:19:59.061 myApp[10132:4520991] Using APNS Notification
2016-04-27 09:20:05.405 myApp[10132:4520879] active
2016-04-27 09:20:05.406 myApp[10132:4520879] PushPlugin skip clear badge
```

My PushNotification code

```
   $ionicPlatform.ready(function() {
        console.log('Start push configuration');
        var push = PushNotification.init({
          android: {
              senderID: "XXX",
          },
          ios: {
              alert: true,
              badge: true,
              sound: true,
          },
          windows: {}
        });
        push.on('error', function(data) {
          console.log('ERROR ' + data);
        });
        push.on('registration', function(data) {
          console.log("cordovaPush.register token: " + data.registrationId);
          var token = data.registrationId;
          storeDeviceToken(token);
        });
        push.on('notification', function (notification) {
            console.log(JSON.stringify([notification]));
            if (ionic.Platform.isAndroid()) {
                handleAndroid(notification);
            }
            else if (ionic.Platform.isIOS()) {
                handleIOS(notification);
            }
        });
      });
    }
```

**Comment by andersonfelizari** [comment]
+1

**Comment by cidus** [comment]
I removed the plugin and added it from this repo in order to update to 1.6.3... still no luck.

**Comment by Infinity-FS** [comment]
+1

**Comment by KODerFunk** [comment]
Panic mode in my startup. Release day!

**Comment by casahuga** [comment]
Doing some debugging in the objective C code, I can figure that the problem it's there, because the calls:

- didRegisterForRemoteNotificationsWithDeviceToken
- didFailToRegisterForRemoteNotificationsWithError
- registerWithToken

Are never call. So, the problem should be in the implementation of objective C code. 

Otherwise I have a lot of warnings in PushPlugin.h and PushPlugin.m:

![issue_push_plugin](https://cloud.githubusercontent.com/assets/12170527/14857381/60387700-0c9c-11e6-8537-62b6ee1a2ac5.png)

**Comment by macdonst** [comment]
I've spun up new apps on iOS 9.3.1 and 8.4.1 and I can't reproduce this. Generally, when didRegisterForRemoteNotificationsWithDeviceToken is not called it is a network connection problem or the proper certificates for the app are not installed. 

@casahuga those warnings are safe to ignore. Most are from Google's GCM library for iOS.

**Comment by Meg4mi** [comment]
+1 here. Same bug. It was working few days ago. Nothing has changed in my application.

**Comment by kevld** [comment]
I have the same problem too, but an old app in the store is still working (I get the token)
Yesterday, some apple services were unstable ( possible to check apple's services states here https://developer.apple.com/system-status/ )
So the problem is maybe on Apple's side
Hope it helps in the future...

**Comment by evtaylor** [comment]
+1 Also having this issue. Worked fine a few days ago, but today push.on('registration) is never called on iOS.

**Comment by casahuga** [comment]
@macdonst thank you for your answer :). I want to share the warnings in order to have more information to resolve these problem. 

Same status than @kevld, we have more apps in the store that use push notifications, all working as expected.

**Comment by ayomide101** [comment]
I've also been having this problem on my app too. Funny thing, it sometimes works and then again, it doesn't. It's quite frustrating, I've combed and debugged all my codes to no avail. From the discussions and my observations, the problem is clearly from Apple APN itself, I hope this is resolved real soon. Launch day is approaching....

**Comment by macdonst** [comment]
Yeah folks, I don't think there is much I can do about this one as it seems to be Apple APN service which is the root cause of the problem.

**Comment by andersonfelizari** [comment]
working again...

**Comment by gitHubLie** [comment]
thanks working again.  but i don't way ?
