### ISSUE TITLE
(iOS) No way of detecting if notification was opened by tapping in the NC 

### ISSUE THREAD

**Issue by Compulsed** [phonegap/phonegap-plugin-push#890]
It appears that you can infer whether the application was pulled to the foreground in Android by the additionalData.foreground property (checking whether it is false), and the handler is only ran when the application is in or brought into the foreground.

Though on iOS it appears that the notifications are handled in the background **AND** when you click the application with exactly the same data objects.

Is it possible to ignore the handler when you get the notification? or programmatically recognise which is which?

Is this intended behaviour, am I missing something?

**Comment by macdonst** [comment]
@Compulsed `data.additionalData.foreground` should be available on iOS as well. Depending on what you send as a payload the notification event may be called in the background. Can you post a sample of the push payload you send?

**Comment by Compulsed** [comment]
@macdonst My problem is push.on('notification', callback) is called on iOS when I receive the notification and when I click on the notification within the NC. This would be fine, typically except for the fact I am unable to tell the difference between when a notification is receive and when the notification is clicked.

(I believe you already understand this, but just to clarify increase I was ambiguous)

![image](https://cloud.githubusercontent.com/assets/1109278/15313194/148956e2-1c4d-11e6-8a8d-9e463bf7f4b5.png)
This is the same for both clicking on the notification and receiving it.

**Comment by macdonst** [comment]
@Compulsed yeah you get two events because of `content-available`. The only thing you can really do is to put a unique identifier in the push payload and check to see if you've already handled the event. You really should use a unique ID and call push.finish(id) to let the OS know you are done handling the event per: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#background-notifications-1
