### ISSUE TITLE
Use "this" in callback function "on"

### ISSUE THREAD

**Issue by diiidiii** [phonegap/phonegap-plugin-push#914]
#### My Problem
I want to use this in the push.on() callback function but it is always undefined. Below are version infos and my code.
I want to save the registrationId with angular http in my database. Also i want to save it in my local sql storage (this.storage.query()...). There i also need "this" but in the callback function it is undefined. 
Maybe someone can help me how to solve my problem

#### Cordova CLI version and cordova platform version
Cordova CLI: 5.4.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.5.0

#### Sample Code that illustrates the problem
```
import {App, IonicApp, Platform, Storage, SqlStorage} from 'ionic-angular';
import {Http} from 'angular2/http';
import {StatusBar, Push} from 'ionic-native';

@App({
    templateUrl: 'build/app.html',
    config: {} // http://ionicframework.com/docs/v2/api/config/Config/
})
class MyApp {
    static get parameters() {
        return [[IonicApp], [Platform], [Http]];
    }

  constructor(app, platform, http) {
        this.app = app;
        this.platform = platform;
	this.http = http;
        this.storage = new Storage(SqlStorage);
        ...
        this.initializeApp();
  }

initializeApp() {
        this.platform.ready().then(() => {
			
            var push = Push.init({
				android: {
					"senderID": "",
					"forceShow": "true"
				},
				ios: {
					alert: "true",
					badge: "true",
					sound: "true"
				},
				windows: {}
			});

			push.on('registration', function (data) {				
				this.storage.query("INSERT INTO table VALUES (" + data.registrationId + ")");
			});

            StatusBar.styleDefault();
        });
    }
```

**Comment by crazy77** [comment]
I fixed this problem by below.

let that=this;
push.on('registration', function (data) {               
    that.storage.query("INSERT INTO table VALUES (" + data.registrationId + ")");
});

**Comment by diiidiii** [comment]
Many many thanks ♥
Its works perfect ;)

**Comment by fredgalvao** [comment]
## This is not really an issue with the plugin itself. That should've been posted somewhere else, as it's a javascript/typescript question.

However:

Although @crazy77 's solution work, by scoping a variable with the value of `this` into the function, it's important to note the "best/recomended" solution for typescript ([check docs](https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript)):

```js
push.on('registration', function (data) {               
    this.storage.query("INSERT INTO table VALUES (" + data.registrationId + ")");
});
```

You're using a full function in this event, and full functions create scope, that's why the `this` variable inside it doesn't mean the same  `this` from outside it. What you could use is fat arrow functions, which are already used in your code (so I'm assuming you know they exist):

```typescript
this.platform.ready().then(() => {
...
});
```


So, to conclude, you could've fixed your code using a registration handler like this:

```js
push.on('registration', (data) => {               
    this.storage.query("INSERT INTO table VALUES (" + data.registrationId + ")");
});
```

You can read more on the exact issue you've experienced [here](https://www.typescriptlang.org/docs/handbook/functions.html#lambdas-and-using-this).
