### ISSUE TITLE
Status bar notification not getting clear

### ISSUE THREAD

**Issue by pallaviMN** [phonegap/phonegap-plugin-push#986]
#### Steps to Reproduce 

1)Launch the application & bring it to background
2) Send notification to device with "Content Available" flag as "1"
3)Now status bar notification will appear
4) Do not click on status bar notification
5)Directly launch the app from background to foreground. As "Content Avalibale" flag is "1", " push.on('notification', function (data) " gets triggered without clicking on status bar notification.
6)Read the notification (not clicking from status bar)
7)After reading it, Click on status bar notification
8)Now again the notification will trigger " push.on('notification', function (data) " with same data.
9)When "Content Avalibale" flag is "1", ststus bar notification should gets cleared when the user reads it without clicking status bar notifications

#### Cordova CLI version and cordova platform version

    cordova --version                                     6.2.0
    cordova platform version android            5.0.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by macdonst** [comment]
@pallaviMN no, what you are describing is the expected behaviour. The notification does not get cleared until the user interacts with it. When sending a message with `content-available: 1` you can omit the title/message so it doesn't show up in the notification center otherwise you need to click the notification to dismiss.
