### ISSUE TITLE
The docs says specifying an icon for Android is optional but displays a default icon

### ISSUE THREAD

**Issue by pke** [phonegap/phonegap-plugin-push#991]
### Expected Behaviour

No icon to be displayed in the push notification

### Actual Behaviour

a gray rectangle is displayed as icon

### Reproduce Scenario (including but not limited to)

Use the example configuration from the docs. No icon specified, no additional resources copied.

So either the copying of the logo.png to the android platform folder is mandatory and not written out in the docs as such (it should say *required* resources instead of *additional* then) or something else is broken

Why does the plugin not use any of the apps default icons configured for Android anyway in config.xml?

**Comment by macdonst** [comment]
@pke did you read the docs on [Android Icon's](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images)? Does you default icon have any transparent pixels in it? If not that would be the reason why you are seeing the grey rectangle. This is why I mention to read the [Android icon design guidelines](https://material.google.com/style/icons.html#).

So in fact the plugin does use the apps default icon. The problem is the default icon is usually not in a format that looks good for notifications. That is why you have the option of providing a different icon to be used. It's not mandatory because without the icon it does not prevent the functionality from working.

Make sense?

**Comment by pke** [comment]
Sorry, @macdonst I missed the payload doc! I just browsed the readme and tested the push notification. You are correct, my icon does not contain transparent pixels. Strange that Android wont display it just as it is then. Without transparency.
So how do I reference the alternative icon? Which path is to be used?

**Comment by pke** [comment]
@macdonst The MD docs you linked to do not explain the size of the icon required for push notifications.

**Comment by macdonst** [comment]
@pke _Product icons are 48dp, with 1dp edges
System icons are 24dp_

**Comment by pke** [comment]
Ah they are called `System icons`. No word of "notification" in the whole document. Not a very good documentation for newcomers. Thanks for the help.
